int fgl_getkey(void);
void trim(char *s);
void popint(int *s);
void popdub(double *s);
void popflo(float *s);
void popquote(char *s, int size);
void popstring(char *s, int size);
void retquote(char *s);
void pushint(int a);
void retint(int a);
void pushshort(short a);
void pushlong(long a);
void popvchar(char *x, int y);
void retdub(double *x);
void retflo(float *a);
void A4GL_strip(char *s);
void retshort(short x);
void poplong(long *x);
void popdate(long *x);
void retlong(long x);
void retdate(long x);
void pushquote(char *s, int n);
void popdtime(void *vx);
void retdtime(void *vx);
void retdec(void *vx);
void popdec(void *vx);
void popshort(short *x);
void retstring(char *s);
int rgetkey(void);
void fgl_fatal(char *mod, long ln, long stat);
int fgl_call(int (*func_ptr)(int), int n);
void popdate_native(void *x);
void retdate_native(void *x, short indic);
int pushlocator(void *x);
int _locate(void *b, int x, int y, char *z);

