adbschema: adbschema.4gl table.4gl grant.4gl
	4glpc --make-compile adbschema.4gl grant.4gl table.4gl -o adbschema

clean:
	rm adbschema adbschema.ao adbschema.c adbschema.glb adbschema.h grant.ao grant.c grant.glb grant.h table.ao table.c table.glb table.h
