
all:
	$(MAKE) -C attributes
	$(MAKE) -C clear_form
	$(MAKE) -C clear_window
	$(MAKE) -C close_form
	$(MAKE) -C close_window
	$(MAKE) -C current_window
	$(MAKE) -C display
	$(MAKE) -C display_array
	$(MAKE) -C display_at
	$(MAKE) -C display_form
	$(MAKE) -C empty_program
	$(MAKE) -C error
	$(MAKE) -C input
	$(MAKE) -C input_array
	$(MAKE) -C menu
	$(MAKE) -C message
	$(MAKE) -C open_window
	$(MAKE) -C prompt
	$(MAKE) -C scroll
	$(MAKE) -C simple_form
	$(MAKE) -C sleep

clean:
	$(MAKE) -C attributes clean
	$(MAKE) -C clear_form clean
	$(MAKE) -C clear_window clean
	$(MAKE) -C close_window clean
	$(MAKE) -C close_form clean
	$(MAKE) -C current_window clean
	$(MAKE) -C display clean
	$(MAKE) -C display_array clean
	$(MAKE) -C display_at clean
	$(MAKE) -C display_form clean
	$(MAKE) -C empty_program clean
	$(MAKE) -C error clean
	$(MAKE) -C input clean
	$(MAKE) -C input_array clean
	$(MAKE) -C menu clean
	$(MAKE) -C message clean
	$(MAKE) -C open_window clean
	$(MAKE) -C prompt clean
	$(MAKE) -C scroll clean
	$(MAKE) -C simple_form clean
	$(MAKE) -C sleep clean
