

like.4ae: like.4gl
	$(FGLC) like.4gl -o like.4ae

compile: like.4ae
	
run: like.4ae
	sh ./run_like

ansi_sql_compat:
	@echo "1"


sql_features_used:		; @echo "DATABASE_USED CREATE_TEMP_TABLE CURSOR_SELECT FOREACH UI_DISPLAY_LINE_MODE DISPLAY EXIT_PROGRAM_EXPR CLOSE_CURSOR DROP_TABLE "

