
DATABASE test1

MAIN
	WHENEVER ERROR CONTINUE
	DROP TABLE xpto
	WHENEVER ERROR STOP
	CREATE TABLE xpto (
	  firstColumn SMALLINT,
		secondColumn CHAR(10)
	)

  REVOKE ALL ON xpto FROM PUBLIC
  GRANT ALL ON xpto TO PUBLIC
  REVOKE ALL PRIVILEGES ON xpto FROM PUBLIC
  GRANT ALL PRIVILEGES ON xpto TO PUBLIC
	DROP TABLE xpto
END MAIN
