
rg2.4ae: rg2.4gl
	$(FGLC) rg2.4gl -o rg2.4ae

compile: rg2.4ae
	
run: rg2.4ae
	sh ./run_rg2

ansi_sql_compat:
	@echo "1"


sql_features_used:		; @echo "DATABASE_USED DEFINE_DATETIME DDL_DATETIME CREATE_TEMP_TABLE UI_DISPLAY_LINE_MODE DISPLAY ANSI_INSERT INITIALIZE_NULL   DISPLAY_FORM"

