
MAIN
  OPEN WINDOW w_name AT 3,3 WITH 10 ROWS, 75 COLUMNS 
	  ATTRIBUTE (
		  WHITE,YELLOW,MAGENTA,CYAN,GREEN,BLUE,BLACK,NORMAL,BOLD,DIM,
      REVERSE, BORDER, COMMENT LINE 10, FORM LINE 2, MENU LINE 1,
			MESSAGE LINE 5, PROMPT LINE 5
		)
END MAIN
