
MAIN
   CREATE DATABASE xpto
	 CLOSE DATABASE
   DROP DATABASE xpto
   CREATE DATABASE xpto WITH BUFFERED LOG
	 CLOSE DATABASE
   DROP DATABASE xpto
   CREATE DATABASE xpto WITH LOG MODE ANSI
	 CLOSE DATABASE
   DROP DATABASE xpto
   CREATE DATABASE xpto IN rootdbs WITH LOG MODE ANSI
	 CLOSE DATABASE
   DROP DATABASE xpto
END MAIN



