
g2.4ae: g2.4gl 
	${FGLC} g2.4gl -o g2.4ae

compile: g2.4ae 
	
run: g2.4ae
	sh ./run_g2

ansi_sql_compat:
	@echo "1"

desc:
	@echo "Another simple report test"

sql_features_used:		; @echo "DATABASE_USED DEFINE_CHAR DEFINE_INTEGER IFX_SYSTABLES CURSOR_SELECT USE_REPORT FOREACH UI_DISPLAY_LINE_MODE DISPLAY IF EXIT_PROGRAM_EXPR REPORT_ORDER_BY REPORT_FIRST_PAGE_HEADER ON_EVERY_ROW "

