
MAIN
  OPTIONS DISPLAY ATTRIBUTE 
	  (
		  WHITE,YELLOW,MAGENTA,CYAN,GREEN,BLUE,BLACK,RED,NORMAL,BOLD,DIM,
			INVISIBLE,NORMAL,REVERSE,BLINK,UNDERLINE
		)
  OPTIONS DISPLAY ATTRIBUTE (FORM)
  OPTIONS DISPLAY ATTRIBUTE (WINDOW)
END MAIN
