
testdt.4ae: testdt.4gl
	$(FGLC) testdt.4gl -o testdt.4ae

compile: testdt.4ae
	
run: testdt.4ae
	sh ./run_testdt

ansi_sql_compat:
	@echo "1"


sql_features_used:		; @echo "DATABASE_USED CREATE_TEMP_TABLE CURSOR_SELECT FOREACH UI_DISPLAY_LINE_MODE DISPLAY EXIT_PROGRAM_EXPR CLOSE_CURSOR DROP_TABLE "

