

MAIN
  OPEN FORM f_xpto FROM "xpto"
	DISPLAY FORM f_xpto
	  ATTRIBUTE (
		  WHITE,YELLOW,MAGENTA,CYAN,GREEN,BLUE,BLACK,RED,NORMAL,BOLD,DIM,
			INVISIBLE,NORMAL,REVERSE,BLINK,UNDERLINE
		)
	CLOSE FORM f_xpto
END MAIN
