
rep.4ae: rep.4gl
	$(FGLC) rep.4gl -o rep.4ae

compile: rep.4ae
	
run: rep.4ae
	sh ./run_rep

ansi_sql_compat:
	@echo "1"


sql_features_used:		; @echo "DATABASE_USED CREATE_TEMP_TABLE CURSOR_SELECT FOREACH UI_DISPLAY_LINE_MODE DISPLAY EXIT_PROGRAM_EXPR CLOSE_CURSOR DROP_TABLE "

