
/**
 * @file
 * The main test file for the new 4gl parser of fgldocumenter.
 * This file was generated by genTestSuite.pl
 */

//#include <cppunit/CompilerOutputter.h>
//#include <cppunit/extensions/TestFactoryRegistry.h>
//#include <cppunit/ui/text/TestRunner.h>
#include <cppunit/ui/text/TestRunner.h>
#include "GenFglTest.h"


int main( int argc, char **argv)
{
  CppUnit::TextUi::TestRunner runner;
  runner.addTest( GenFglTest::suite() );
  runner.run();
  return 0;
}

