#########################################################################
#			helpfile.msg
#
#   Demonstration and testing help file for Aubit 4gl compiler. For ussage
#   and compiling, please see manual.
#
# Note:
#		DO NOT USE "^" as a first letter in the line !
#		do not use "|" at all
#
#
##########################################################################
.1

This message will appear under help number 1

.2

This message will appear under help number 2

...etc...


