
testna.4ae: testna.4gl
	$(FGLC) testna.4gl -o testna.4ae

compile: testna.4ae
	
run: testna.4ae
	sh ./run_testna

ansi_sql_compat:
	@echo "1"


sql_features_used:		; @echo "DATABASE_USED DEFINE_INTEGER DEFINE_CHAR CREATE_TEMP_TABLE ANSI_INSERT CURSOR_SELECT_FOR_UPDATE CURSOR_SELECT FOREACH UPDATE_COLUMN_EQ_VALUE_LIST UPDATE_WHERE_CURRENT_OF ORDER_BY UI_DISPLAY_LINE_MODE DISPLAY "

