
DATABASE test1

MAIN
	DEFINE strWhere CHAR(128)

	OPEN WINDOW w_ AT 2,2 WITH FORM "sysu" ATTRIBUTE(BORDER)
	CONSTRUCT BY NAME strWhere ON sysusers.*
		ON KEY (CONTROL-N)
	    NEXT FIELD NEXT
		ON KEY (CONTROL-P)
	    NEXT FIELD PREVIOUS
		ON KEY (CONTROL-G)
	    NEXT FIELD priority
		ON KEY (CONTROL-T)
	    NEXT FIELD username
		ON KEY (CONTROL-Y)
		  EXIT CONSTRUCT
		ON KEY (CONTROL-B)
		  CONTINUE CONSTRUCT
	END CONSTRUCT
	CLOSE WINDOW w_
	DISPLAY "Where ", strWhere clipped
END MAIN
