DATABASE test1


FUNCTION test_whenever()
  DEFINE i SMALLINT
database test1
	WHENEVER WARNING GOTO warningLabel
	SELECT count(*) INTO i FROM SYSTABLES
	WHENEVER WARNING GOTO :warningLabel
	SELECT count(*) INTO i FROM SYSTABLES
	WHENEVER WARNING GOTO warningLabel
	SELECT count(*) INTO i FROM SYSTABLES
	WHENEVER WARNING GO TO :warningLabel
	SELECT count(*) INTO i FROM SYSTABLES
  RETURN

LABEL warningLabel:
  display "ERROR"
END FUNCTION
