######################################################################
# Automatically generated by qmake (2.01a) Mi. Jan 25 14:47:46 2012
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../..
INCLUDEPATH += . ../..

# Input
HEADERS += test_fgl.h \
           include/fgl.h
SOURCES += test_fgl.cpp \
           include/fgl.cpp \
