zero.4ae: zero.4gl
	${FGLC} zero.4gl -o zero.4ae

compile: zero.4ae

run: compile
	sh run_zero
	

ansi_sql_compat:
	@echo "1"


sql_features_used:		; @echo "DATABASE_USED CREATE_TEMP_TABLE CURSOR_SELECT FOREACH UI_DISPLAY_LINE_MODE DISPLAY EXIT_PROGRAM_EXPR CLOSE_CURSOR DROP_TABLE "

