
MAIN
	 DEFINE strMesg CHAR(30)
	 LET strMesg = "Hello message world"

   MESSAGE strMesg
	  ATTRIBUTE ( WHITE,YELLOW,MAGENTA,CYAN,GREEN,BLUE,BLACK,RED,NORMAL,BOLD, INVISIBLE,NORMAL,REVERSE,BLINK,UNDERLINE)
   MESSAGE strMesg
	  ATTRIBUTE ( WHITE,YELLOW,MAGENTA,CYAN,GREEN,BLUE,BLACK,RED,NORMAL,DIM, INVISIBLE,NORMAL,REVERSE,BLINK,UNDERLINE)
END MAIN
