

rg1.4ae: rg1.4gl
	$(FGLC) rg1.4gl -o rg1.4ae

compile: rg1.4ae
	
run: rg1.4ae
	sh ./run_rg1

ansi_sql_compat:
	@echo "1"


sql_features_used:		; @echo "DATABASE_USED DEFINE_DATETIME DDL_DATETIME CREATE_TEMP_TABLE UI_DISPLAY_LINE_MODE DISPLAY ANSI_INSERT INITIALIZE_NULL "

