 
const int token_group_132[]={CLOSE_SQUARE,-1};
 
const int token_group_27[]={SEMICOLON,EXCLUSIVE,-1};
 
const int token_group_145[]={INTO_TEMP,FOR_UPDATE_OF,SEMICOLON,ORDER,FOR_UPDATE,-1};
 
const int token_group_70[]={ALL,YEAR,OPEN_BRACKET,NUMBER_VALUE,XMIN,KW_DOT,ANY,KW_DOW,SOME,INT_VALUE,KW_ROWID,EXISTS,AVG,CASE,KW_TODAY,INTERVAL_VALUE,KW_NOT,KW_FALSE,KW_DATE,NOT_EXISTS,KW_SUM,EXTEND,WEEKDAY,NAMED,MDY,KW_SELECT,QUESTION_MARK,COUNT_MULTIPLY,KW_TRUE,KW_MULTIPLY,DATETIME_VALUE,USER,TIME,MARK_VAR,CHAR_VALUE,MONTH,KW_PLUS,KW_CURRENT,KW_MINUS,XMAX,COUNT,DAY,-1};
 
const int token_group_8[]={FOR_UPDATE_OF,SEMICOLON,FOR_UPDATE,-1};
 
const int token_group_84[]={WHEN,ELSE,END,-1};
 
const int token_group_13[]={OPEN_BRACKET,-1};
 
const int token_group_81[]={EQUAL,-1};
 
const int token_group_63[]={FOREIGN_KEY,PRIMARY_KEY,CHECK,UNIQUE,DISTINCT,-1};
 
const int token_group_144[]={KW_SELECT,ALL,UNIQUE,DISTINCT,-1};
 
const int token_group_82[]={END_MARK_VAR,-1};
 
const int token_group_87[]={KW_ROWID,NAMED,KW_MULTIPLY,-1};
 
const int token_group_76[]={KW_DOT,COLON,-1};
 
const int token_group_59[]={UNITS_MINUTE,YEAR,EQUAL,UNITS_HOUR,WHEN,KW_THEN,UNITS_SECOND,SEMICOLON,UNITS_YEAR,WITH_CHECK_OPTION,NOT_ILIKE,KW_COMMA,UNION,KW_ESCAPE,MINUTE,IS_NULL,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,WHERE_CURRENT_OF,KW_AS,DOUBLE_COLON,KW_DIVIDE,SECOND,GREATER_THAN,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,MATCHES,KW_IN,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ORDER,FROM,KW_ON,KW_MULTIPLY,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,MONTH,KW_AND,KW_PLUS,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,INNER_JOIN,HOUR,FOR_UPDATE_OF,GROUP_BY,GREATER_THAN_EQ,CREATE_VIEW,NOT_LIKE,LESS_THAN_EQ,IS_NOT_NULL,UNITS_DAY,FRACTION,DAY,-1};
 
const int token_group_150[]={GRANT,KW_DOT,KW_COMMA,INTO_TEMP,CREATE_VIEW,COLON,DESC,ATSIGN,FOR_UPDATE_OF,SEMICOLON,UNION,ASC,REVOKE,WITH_CHECK_OPTION,ORDER,OPEN_SQUARE,HAVING,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_119[]={KW_PLUS,KW_MOD,KW_MINUS,KW_MULTIPLY,KW_DIVIDE,CLOSE_BRACKET,-1};
 
const int token_group_114[]={KW_COMMA,CLOSE_SQUARE,-1};
 
const int token_group_23[]={INSHARE,INEXCLUSIVE,-1};
 
const int token_group_98[]={GREATER_THAN,EQUAL,LESS_THAN,GREATER_THAN_EQ,NOT_MATCHES,IS_NULL,NOT_ILIKE,LESS_THAN_EQ,NOT_LIKE,IS_NOT_NULL,TILDE,NOT_EQUAL,MATCHES,ILIKE,BETWEEN,NOT_IN,LIKE,KW_IN,CLOSE_BRACKET,KW_NOT,-1};
 
const int token_group_154[]={INTO_TEMP,FOR_UPDATE_OF,SEMICOLON,FOR_UPDATE,-1};
 
const int token_group_143[]={GRANT,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,UNION,REVOKE,WITH_CHECK_OPTION,ORDER,HAVING,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_139[]={LEFT_JOIN,GRANT,KW_COMMA,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,INNER_JOIN,WHERE,UNION,REVOKE,WITH_CHECK_OPTION,ORDER,HAVING,GROUP_BY,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_38[]={NAMED,FOREIGN_KEY,OPEN_BRACKET,PRIMARY_KEY,CHECK,UNIQUE,DISTINCT,-1};
 
const int token_group_1[]={-1,-1};
 
const int token_group_24[]={KW_DOT,-1};
 
const int token_group_115[]={GRANT,LEFT_JOIN,KW_COMMA,INTO_TEMP,CREATE_VIEW,KW_ESCAPE,FOR_UPDATE_OF,SEMICOLON,KW_ON,INNER_JOIN,WHERE,UNION,REVOKE,WITH_CHECK_OPTION,KW_AND,ORDER,KW_OR,KW_THEN,HAVING,GROUP_BY,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_64[]={KW_COMMA,SEMICOLON,CONSTRAINT,-1};
 
const int token_group_7[]={SEMICOLON,-1};
 
const int token_group_106[]={UNITS_HOUR,KW_COMMA,UNITS_YEAR,KW_PLUS,DOUBLE_COLON,UNITS_MONTH,KW_MINUS,UNITS_SECOND,KW_MULTIPLY,UNITS_MINUTE,KW_DIVIDE,UNITS_DAY,-1};
 
const int token_group_130[]={KW_COMMA,KW_PLUS,KW_MOD,CLOSE_SQUARE,KW_MINUS,KW_MULTIPLY,KW_DIVIDE,CLOSE_BRACKET,-1};
 
const int token_group_157[]={LEFT_JOIN,KW_COMMA,INNER_JOIN,CLOSE_BRACKET,-1};
 
const int token_group_31[]={INT_VALUE,-1};
 
const int token_group_138[]={UNITS_HOUR,KW_COMMA,UNITS_YEAR,KW_PLUS,DOUBLE_COLON,UNITS_MONTH,KW_MINUS,UNITS_SECOND,KW_MULTIPLY,UNITS_MINUTE,KW_DIVIDE,CLOSE_BRACKET,UNITS_DAY,-1};
 
const int token_group_105[]={KW_COMMA,-1};
 
const int token_group_68[]={KW_DOT,KW_COMMA,COLON,ATSIGN,OPEN_SQUARE,CLOSE_BRACKET,-1};
 
const int token_group_9[]={WITH_LOG_IN,-1};
 
const int token_group_67[]={TO_NOT_CLUSTER,COLON,SEMICOLON,KW_ON,TO_CLUSTER,-1};
 
const int token_group_52[]={NOT_NULL_UNIQUE,OPEN_BRACKET,INEXCLUSIVE,SEMICOLON,WITH_CHECK_OPTION,KW_COMMA,UNION,DISTINCT,XSET_ident_DOT_MULTIPLY_EQUAL_OPEN_BRACKET,INSHARE,PRIMARY_KEY,XSET,LEFT_JOIN,CLOSE_BRACKET,KW_TO,WHERE_CURRENT_OF,KW_AS,COLON,UNIQUE,XSET_MULTIPLY_EQUAL,NAMED,XSET_OPEN_BRACKET,REFERENCES,CHECK,KW_IN,KW_SELECT,KW_FOR,HAVING,REVOKE,ORDER,FROM,XSET_MULTIPLY_EQUAL_OPEN_BRACKET,KW_ON,GRANT,INTO_TEMP,WHERE,XSET_ident_DOT_MULTIPLY_EQUAL,VALUES,BEFORE,FOR_UPDATE,INNER_JOIN,FOR_UPDATE_OF,CONSTRAINT,GROUP_BY,CREATE_VIEW,NOT_NULL,-1};
 
const int token_group_60[]={KW_COMMA,CLOSE_BRACKET,-1};
 
const int token_group_48[]={ALL,YEAR,OPEN_BRACKET,NUMBER_VALUE,XMIN,KW_DOT,ANY,KW_DOW,SOME,INT_VALUE,KW_ROWID,AVG,CASE,KW_TODAY,INTERVAL_VALUE,KW_NULL,KW_FALSE,KW_DATE,KW_SUM,EXTEND,WEEKDAY,NAMED,MDY,QUESTION_MARK,COUNT_MULTIPLY,KW_TRUE,KW_MULTIPLY,DATETIME_VALUE,USER,TIME,MARK_VAR,CHAR_VALUE,MONTH,KW_PLUS,KW_CURRENT,KW_MINUS,XMAX,COUNT,DAY,-1};
 
const int token_group_46[]={NAMED,CHAR_VALUE,PUBLIC,-1};
 
const int token_group_49[]={NAMED,ATSIGN,-1};
 
const int token_group_101[]={FROM,KW_COMMA,INTO_TEMP,FOR_UPDATE_OF,SEMICOLON,UNION,ORDER,FOR_UPDATE,-1};
 
const int token_group_11[]={NOT_NULL_UNIQUE,OPEN_BRACKET,INEXCLUSIVE,KW_DOT,ATSIGN,SEMICOLON,WITH_CHECK_OPTION,KW_COMMA,UNION,DISTINCT,XSET_ident_DOT_MULTIPLY_EQUAL_OPEN_BRACKET,INSHARE,PRIMARY_KEY,XSET,LEFT_JOIN,CLOSE_BRACKET,KW_TO,WHERE_CURRENT_OF,KW_AS,COLON,UNIQUE,XSET_MULTIPLY_EQUAL,NAMED,XSET_OPEN_BRACKET,REFERENCES,CHECK,KW_IN,KW_SELECT,KW_FOR,HAVING,REVOKE,ORDER,FROM,XSET_MULTIPLY_EQUAL_OPEN_BRACKET,KW_ON,GRANT,INTO_TEMP,WHERE,XSET_ident_DOT_MULTIPLY_EQUAL,VALUES,BEFORE,FOR_UPDATE,INNER_JOIN,FOR_UPDATE_OF,CONSTRAINT,GROUP_BY,CREATE_VIEW,NOT_NULL,-1};
 
const int token_group_83[]={CLOSE_BRACKET,-1};
 
const int token_group_33[]={XSET_OPEN_BRACKET,XSET,XSET_ident_DOT_MULTIPLY_EQUAL,XSET_MULTIPLY_EQUAL,XSET_ident_DOT_MULTIPLY_EQUAL_OPEN_BRACKET,XSET_MULTIPLY_EQUAL_OPEN_BRACKET,-1};
 
const int token_group_158[]={GRANT,KW_COMMA,INTO_TEMP,CREATE_VIEW,DESC,FOR_UPDATE_OF,SEMICOLON,UNION,ASC,REVOKE,WITH_CHECK_OPTION,ORDER,OPEN_SQUARE,HAVING,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_26[]={KW_TO,-1};
 
const int token_group_121[]={NOT_NULL,KW_COMMA,SEMICOLON,BEFORE,PRIMARY_KEY,CHECK,NOT_NULL_UNIQUE,UNIQUE,CONSTRAINT,CLOSE_BRACKET,DISTINCT,REFERENCES,-1};
 
const int token_group_79[]={KW_COMMA,WHERE_CURRENT_OF,SEMICOLON,WHERE,-1};
 
const int token_group_43[]={KW_AS,-1};
 
const int token_group_47[]={INDEX,ALTER,KW_DELETE,KW_SELECT,KW_UPDATE,KW_INSERT,-1};
 
const int token_group_100[]={KW_DOT,KW_COMMA,CLOSE_BRACKET,-1};
 
const int token_group_91[]={UNITS_MINUTE,NOT_NULL_UNIQUE,OPEN_BRACKET,EQUAL,UNITS_HOUR,WHEN,KW_THEN,UNITS_SECOND,DEFAULT_TODAY,SEMICOLON,UNITS_YEAR,WITH_CHECK_OPTION,NOT_ILIKE,KW_COMMA,UNION,DISTINCT,DEFAULT_USER,KW_ESCAPE,IS_NULL,PRIMARY_KEY,DEFAULT_NULL,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,WHERE_CURRENT_OF,KW_AS,DOUBLE_COLON,KW_DIVIDE,GREATER_THAN,UNIQUE,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,REFERENCES,MATCHES,CHECK,KW_IN,DEFAULT,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ORDER,FROM,KW_ON,KW_MULTIPLY,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,KW_AND,BEFORE,KW_PLUS,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,INNER_JOIN,FOR_UPDATE_OF,GROUP_BY,GREATER_THAN_EQ,CREATE_VIEW,NOT_LIKE,LESS_THAN_EQ,NOT_NULL,IS_NOT_NULL,UNITS_DAY,-1};
 
const int token_group_35[]={ALL,YEAR,OPEN_BRACKET,NUMBER_VALUE,XMIN,KW_DOT,ANY,KW_DOW,SOME,INT_VALUE,KW_ROWID,AVG,CASE,KW_TODAY,CLOSE_BRACKET,INTERVAL_VALUE,KW_FALSE,KW_DATE,KW_SUM,EXTEND,WEEKDAY,NAMED,MDY,QUESTION_MARK,COUNT_MULTIPLY,KW_TRUE,KW_MULTIPLY,DATETIME_VALUE,USER,TIME,MARK_VAR,CHAR_VALUE,MONTH,KW_PLUS,KW_CURRENT,KW_MINUS,XMAX,COUNT,DAY,-1};
 
const int token_group_92[]={NOT_NULL,DEFAULT_NULL,KW_COMMA,SEMICOLON,BEFORE,PRIMARY_KEY,CHECK,NOT_NULL_UNIQUE,UNIQUE,DEFAULT_TODAY,DEFAULT_USER,DEFAULT,CLOSE_BRACKET,DISTINCT,REFERENCES,-1};
 
const int token_group_104[]={DAY,UNITS_HOUR,KW_COMMA,MONTH,UNITS_YEAR,KW_PLUS,DOUBLE_COLON,HOUR,SECOND,UNITS_MONTH,YEAR,KW_MINUS,UNITS_SECOND,KW_MULTIPLY,FRACTION,MINUTE,UNITS_MINUTE,KW_DIVIDE,UNITS_DAY,-1};
 
const int token_group_73[]={GRANT,LEFT_JOIN,KW_COMMA,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,KW_ON,INNER_JOIN,WHERE,UNION,REVOKE,WITH_CHECK_OPTION,KW_AND,ORDER,KW_OR,KW_THEN,HAVING,GROUP_BY,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_102[]={NAMED,FROM,GRANT,KW_COMMA,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,UNION,REVOKE,WITH_CHECK_OPTION,ORDER,KW_AS,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_65[]={KW_BYTE,VARCHAR,KW_DATE,KW_CHAR,SMALLINT,KW_FLOAT,MONEY,SMALLFLOAT,KW_TEXT,NVARCHAR,NCHAR,INTEGER,KW_DECIMAL,DOUBLE_PRECISION,REAL,TIMESTAMP,DATETIME,SERIAL8,INTERVAL,TIME,SERIAL,-1};
 
const int token_group_2[]={NAMED,-1};
 
const int token_group_50[]={KW_DOT,KW_COMMA,SEMICOLON,-1};
 
const int token_group_137[]={EQUAL,KW_COMMA,OPEN_SQUARE,CLOSE_BRACKET,-1};
 
const int token_group_120[]={REFERENCES,-1};
 
const int token_group_116[]={UNITS_HOUR,GRANT,LEFT_JOIN,KW_COMMA,INTO_TEMP,CREATE_VIEW,UNITS_YEAR,KW_ESCAPE,KW_PLUS,FOR_UPDATE_OF,SEMICOLON,UNITS_MONTH,KW_ON,INNER_JOIN,UNITS_SECOND,KW_MINUS,WHERE,UNION,KW_MULTIPLY,REVOKE,WITH_CHECK_OPTION,KW_AND,ORDER,UNITS_MINUTE,KW_OR,KW_THEN,HAVING,GROUP_BY,KW_DIVIDE,UNITS_DAY,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_45[]={OPEN_BRACKET,KW_SELECT,VALUES,-1};
 
const int token_group_113[]={KW_COMMA,OPEN_SQUARE,CLOSE_BRACKET,-1};
 
const int token_group_62[]={UNITS_MINUTE,EQUAL,UNITS_HOUR,WHEN,KW_THEN,UNITS_SECOND,SEMICOLON,UNITS_YEAR,WITH_CHECK_OPTION,NOT_ILIKE,KW_COMMA,UNION,KW_ESCAPE,IS_NULL,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,WHERE_CURRENT_OF,KW_AS,DOUBLE_COLON,KW_DIVIDE,GREATER_THAN,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,MATCHES,KW_IN,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ORDER,FROM,KW_ON,KW_MULTIPLY,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,KW_AND,KW_PLUS,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,INNER_JOIN,FOR_UPDATE_OF,GROUP_BY,GREATER_THAN_EQ,CREATE_VIEW,NOT_LIKE,LESS_THAN_EQ,IS_NOT_NULL,UNITS_DAY,-1};
 
const int token_group_152[]={GRANT,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,UNION,REVOKE,WITH_CHECK_OPTION,ORDER,KW_OR,HAVING,GROUP_BY,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_124[]={KW_DOT,NUMBER_VALUE,INT_VALUE,-1};
 
const int token_group_80[]={EQUAL,KW_COMMA,KW_DOT,OPEN_SQUARE,CLOSE_BRACKET,-1};
 
const int token_group_69[]={KW_SELECT,-1};
 
const int token_group_12[]={KW_IN,-1};
 
const int token_group_161[]={GRANT,LEFT_JOIN,KW_COMMA,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,KW_ON,INNER_JOIN,WHERE,UNION,REVOKE,WITH_CHECK_OPTION,ORDER,KW_OR,HAVING,GROUP_BY,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_159[]={KW_COMMA,INTO_TEMP,FOR_UPDATE_OF,SEMICOLON,FOR_UPDATE,-1};
 
const int token_group_22[]={WHERE_CURRENT_OF,SEMICOLON,WHERE,-1};
 
const int token_group_3[]={NAMED,CHAR_VALUE,-1};
 
const int token_group_20[]={KW_FOR,-1};
 
const int token_group_5[]={RESOURCE,INDEX,ALTER,KW_DELETE,DBA,KW_SELECT,CONNECT,ALL,KW_UPDATE,KW_INSERT,ALL_PRIVILEGES,-1};
 
const int token_group_89[]={UNITS_MINUTE,OPEN_BRACKET,NOT_NULL_UNIQUE,EQUAL,UNITS_HOUR,WHEN,KW_THEN,UNITS_SECOND,DEFAULT_TODAY,SEMICOLON,UNITS_YEAR,WITH_CHECK_OPTION,NOT_ILIKE,KW_COMMA,UNION,DISTINCT,DEFAULT_USER,KW_ESCAPE,IS_NULL,PRIMARY_KEY,DEFAULT_NULL,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,WHERE_CURRENT_OF,KW_AS,DOUBLE_COLON,KW_DIVIDE,GREATER_THAN,UNIQUE,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,REFERENCES,MATCHES,CHECK,KW_IN,DEFAULT,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ORDER,FROM,KW_ON,KW_MULTIPLY,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,KW_AND,BEFORE,KW_PLUS,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,INNER_JOIN,FOR_UPDATE_OF,GROUP_BY,GREATER_THAN_EQ,CREATE_VIEW,NOT_LIKE,LESS_THAN_EQ,NOT_NULL,IS_NOT_NULL,UNITS_DAY,-1};
 
const int token_group_28[]={KW_COMMA,OPEN_BRACKET,KW_ON,-1};
 
const int token_group_148[]={NAMED,KW_ROWID,CHAR_VALUE,-1};
 
const int token_group_10[]={NOT_NULL_UNIQUE,OPEN_BRACKET,INEXCLUSIVE,KW_DOT,SEMICOLON,WITH_CHECK_OPTION,KW_COMMA,UNION,DISTINCT,XSET_ident_DOT_MULTIPLY_EQUAL_OPEN_BRACKET,INSHARE,PRIMARY_KEY,XSET,LEFT_JOIN,CLOSE_BRACKET,KW_TO,WHERE_CURRENT_OF,KW_AS,UNIQUE,XSET_MULTIPLY_EQUAL,NAMED,XSET_OPEN_BRACKET,REFERENCES,CHECK,KW_IN,KW_SELECT,KW_FOR,HAVING,REVOKE,ORDER,FROM,XSET_MULTIPLY_EQUAL_OPEN_BRACKET,KW_ON,GRANT,INTO_TEMP,WHERE,XSET_ident_DOT_MULTIPLY_EQUAL,VALUES,BEFORE,FOR_UPDATE,INNER_JOIN,FOR_UPDATE_OF,CONSTRAINT,GROUP_BY,CREATE_VIEW,NOT_NULL,-1};
 
const int token_group_17[]={TO_NOT_CLUSTER,COLON,ATSIGN,SEMICOLON,KW_ON,TO_CLUSTER,-1};
 
const int token_group_14[]={MODIFY_NEXT_SIZE,ADD_CONSTRAINT,LOCK_MODE_PAGE,DROP_CONSTRAINT,LOCK_MODE_ROW,ADD,MODIFY,DROP,-1};
 
const int token_group_126[]={FROM,INTO_TEMP,FOR_UPDATE_OF,SEMICOLON,UNION,ORDER,FOR_UPDATE,-1};
 
const int token_group_51[]={SEMICOLON,MODE_ANSI,-1};
 
const int token_group_128[]={FROM,KW_COMMA,CLOSE_BRACKET,-1};
 
const int token_group_88[]={KW_COMMA,CONSTRAINT,CLOSE_BRACKET,-1};
 
const int token_group_147[]={NAMED,CHAR_VALUE,OUTER,-1};
 
const int token_group_122[]={USING_BTREE,SEMICOLON,USING_RTREE,FILLFACTOR,KW_IN,-1};
 
const int token_group_151[]={GRANT,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,UNION,REVOKE,WITH_CHECK_OPTION,ORDER,KW_OR,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_146[]={NAMED,OPEN_BRACKET,CHAR_VALUE,-1};
 
const int token_group_112[]={LOCK_MODE_PAGE,EXTENT_SIZE,SEMICOLON,LOCK_MODE_ROW,WITH_NO_LOG,NEXT_SIZE,KW_IN,-1};
 
const int token_group_133[]={GRANT,FROM,KW_COMMA,CREATE_VIEW,SEMICOLON,REVOKE,WITH_CHECK_OPTION,-1};
 
const int token_group_127[]={UNITS_MINUTE,EQUAL,UNITS_HOUR,WHEN,KW_THEN,UNITS_SECOND,SEMICOLON,UNITS_YEAR,WITH_CHECK_OPTION,NOT_ILIKE,KW_COMMA,UNION,KW_ESCAPE,IS_NULL,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,WHERE_CURRENT_OF,KW_AS,DOUBLE_COLON,KW_DIVIDE,GREATER_THAN,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,MATCHES,KW_IN,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ORDER,FROM,KW_ON,KW_MULTIPLY,OPEN_SQUARE,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,KW_AND,KW_PLUS,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,INNER_JOIN,FOR_UPDATE_OF,GROUP_BY,GREATER_THAN_EQ,CREATE_VIEW,NOT_LIKE,LESS_THAN_EQ,IS_NOT_NULL,UNITS_DAY,-1};
 
const int token_group_54[]={UNITS_MINUTE,EQUAL,UNITS_HOUR,WHEN,KW_THEN,KW_DOT,UNITS_SECOND,SEMICOLON,UNITS_YEAR,WITH_CHECK_OPTION,NOT_ILIKE,KW_COMMA,UNION,KW_ESCAPE,IS_NULL,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,WHERE_CURRENT_OF,KW_AS,DOUBLE_COLON,KW_DIVIDE,GREATER_THAN,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,MATCHES,KW_IN,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ORDER,FROM,KW_ON,KW_MULTIPLY,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,KW_AND,KW_PLUS,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,INNER_JOIN,FOR_UPDATE_OF,GROUP_BY,GREATER_THAN_EQ,CREATE_VIEW,NOT_LIKE,LESS_THAN_EQ,IS_NOT_NULL,UNITS_DAY,-1};
 
const int token_group_36[]={FOREIGN_KEY,OPEN_BRACKET,PRIMARY_KEY,CHECK,UNIQUE,DISTINCT,-1};
 
const int token_group_109[]={KW_DOT,NUMBER_VALUE,CHAR_VALUE,INT_VALUE,KW_CURRENT,-1};
 
const int token_group_58[]={SOME,DAY,NAMED,KW_ROWID,KW_DOT,KW_DATE,COUNT,KW_SUM,AVG,KW_FALSE,KW_TRUE,MONTH,QUESTION_MARK,EXTEND,WEEKDAY,USER,OPEN_BRACKET,DATETIME_VALUE,NUMBER_VALUE,KW_DOW,YEAR,CHAR_VALUE,MARK_VAR,COUNT_MULTIPLY,KW_MULTIPLY,KW_TODAY,ALL,CASE,MDY,XMIN,INTERVAL_VALUE,INT_VALUE,ANY,XMAX,TIME,KW_CURRENT,-1};
 
const int token_group_29[]={FROM,-1};
 
const int token_group_136[]={INTO_TEMP,FOR_UPDATE_OF,SEMICOLON,UNION,ORDER,FOR_UPDATE,-1};
 
const int token_group_42[]={NAMED,ATSIGN,CHAR_VALUE,-1};
 
const int token_group_118[]={WITH_GRANT_OPTION,GRANT,KW_COMMA,CREATE_VIEW,SEMICOLON,REVOKE,KW_AS,-1};
 
const int token_group_117[]={NAMED,KW_DOT,QUESTION_MARK,NUMBER_VALUE,KW_SELECT,KW_MINUS,CHAR_VALUE,MARK_VAR,INT_VALUE,KW_CURRENT,-1};
 
const int token_group_53[]={UNITS_MINUTE,OPEN_BRACKET,EQUAL,UNITS_HOUR,WHEN,KW_THEN,KW_DOT,UNITS_SECOND,SEMICOLON,UNITS_YEAR,WITH_CHECK_OPTION,NOT_ILIKE,KW_COMMA,UNION,KW_ESCAPE,IS_NULL,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,WHERE_CURRENT_OF,KW_AS,DOUBLE_COLON,KW_DIVIDE,GREATER_THAN,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,MATCHES,KW_IN,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ORDER,FROM,KW_ON,KW_MULTIPLY,OPEN_SQUARE,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,KW_AND,KW_PLUS,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,INNER_JOIN,FOR_UPDATE_OF,GROUP_BY,GREATER_THAN_EQ,CREATE_VIEW,NOT_LIKE,LESS_THAN_EQ,IS_NOT_NULL,UNITS_DAY,-1};
 
const int token_group_32[]={ALL,YEAR,OPEN_BRACKET,NUMBER_VALUE,XMIN,KW_DOT,ANY,KW_DOW,SOME,INT_VALUE,KW_ROWID,DISTINCT,AVG,CASE,KW_TODAY,INTERVAL_VALUE,KW_FALSE,KW_DATE,KW_SUM,UNIQUE,EXTEND,WEEKDAY,NAMED,MDY,QUESTION_MARK,COUNT_MULTIPLY,KW_TRUE,KW_MULTIPLY,DATETIME_VALUE,USER,TIME,MARK_VAR,CHAR_VALUE,MONTH,KW_PLUS,KW_CURRENT,KW_MINUS,XMAX,COUNT,DAY,-1};
 
const int token_group_99[]={IS_NULL,IS_NOT_NULL,BETWEEN,-1};
 
const int token_group_61[]={UNITS_MINUTE,EQUAL,UNITS_HOUR,WHEN,KW_THEN,KW_DOT,UNITS_SECOND,SEMICOLON,UNITS_YEAR,WITH_CHECK_OPTION,NOT_ILIKE,KW_COMMA,UNION,KW_ESCAPE,IS_NULL,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,WHERE_CURRENT_OF,KW_AS,DOUBLE_COLON,KW_DIVIDE,GREATER_THAN,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,MATCHES,KW_IN,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ORDER,FROM,KW_ON,KW_MULTIPLY,OPEN_SQUARE,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,KW_AND,KW_PLUS,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,INNER_JOIN,FOR_UPDATE_OF,GROUP_BY,GREATER_THAN_EQ,CREATE_VIEW,NOT_LIKE,LESS_THAN_EQ,IS_NOT_NULL,UNITS_DAY,-1};
 
const int token_group_18[]={KW_ON,-1};
 
const int token_group_56[]={ALL,YEAR,OPEN_BRACKET,NUMBER_VALUE,XMIN,KW_DOT,ANY,KW_DOW,SOME,INT_VALUE,KW_ROWID,AVG,CASE,KW_TODAY,INTERVAL_VALUE,KW_FALSE,KW_DATE,KW_SUM,EXTEND,WEEKDAY,NAMED,MDY,KW_SELECT,QUESTION_MARK,COUNT_MULTIPLY,KW_TRUE,KW_MULTIPLY,DATETIME_VALUE,USER,TIME,MARK_VAR,CHAR_VALUE,MONTH,KW_PLUS,KW_CURRENT,KW_MINUS,XMAX,COUNT,DAY,-1};
 
const int token_group_44[]={ALL,YEAR,OPEN_BRACKET,NUMBER_VALUE,XMIN,KW_DOT,ANY,KW_DOW,SOME,INT_VALUE,KW_ROWID,EXISTS,AVG,CASE,KW_TODAY,INTERVAL_VALUE,KW_NOT,KW_FALSE,KW_DATE,NOT_EXISTS,KW_SUM,EXTEND,WEEKDAY,NAMED,MDY,QUESTION_MARK,COUNT_MULTIPLY,KW_TRUE,KW_MULTIPLY,DATETIME_VALUE,USER,TIME,MARK_VAR,CHAR_VALUE,MONTH,KW_PLUS,KW_CURRENT,KW_MINUS,XMAX,COUNT,DAY,-1};
 
const int token_group_103[]={DAY,MONTH,HOUR,SECOND,YEAR,FRACTION,MINUTE,-1};
 
const int token_group_149[]={GRANT,KW_COMMA,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,UNION,REVOKE,WITH_CHECK_OPTION,ORDER,HAVING,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_74[]={GREATER_THAN,EQUAL,LESS_THAN,GREATER_THAN_EQ,NOT_MATCHES,IS_NULL,NOT_ILIKE,LESS_THAN_EQ,NOT_LIKE,IS_NOT_NULL,TILDE,NOT_EQUAL,MATCHES,ILIKE,BETWEEN,NOT_IN,LIKE,KW_IN,KW_NOT,-1};
 
const int token_group_95[]={NAMED,KW_MULTIPLY,-1};
 
const int token_group_55[]={UNITS_MINUTE,YEAR,NOT_NULL_UNIQUE,EQUAL,UNITS_HOUR,WHEN,KW_THEN,UNITS_SECOND,SEMICOLON,UNITS_YEAR,WITH_CHECK_OPTION,NOT_ILIKE,KW_COMMA,UNION,DISTINCT,KW_ESCAPE,MINUTE,IS_NULL,PRIMARY_KEY,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,WHERE_CURRENT_OF,KW_AS,DOUBLE_COLON,KW_DIVIDE,SECOND,GREATER_THAN,UNIQUE,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,REFERENCES,MATCHES,CHECK,KW_IN,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ORDER,FROM,KW_ON,KW_MULTIPLY,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,MONTH,KW_AND,BEFORE,KW_PLUS,FOR_UPDATE,NOT_MATCHES,HOUR,END,KW_MINUS,INNER_JOIN,FOR_UPDATE_OF,GROUP_BY,GREATER_THAN_EQ,CREATE_VIEW,NOT_LIKE,LESS_THAN_EQ,NOT_NULL,IS_NOT_NULL,FRACTION,DAY,UNITS_DAY,-1};
 
const int token_group_140[]={NAMED,GRANT,LEFT_JOIN,KW_COMMA,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,KW_ON,INNER_JOIN,WHERE,UNION,REVOKE,WITH_CHECK_OPTION,ORDER,KW_AS,HAVING,GROUP_BY,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_160[]={KW_COMMA,INTO_TEMP,DESC,FOR_UPDATE_OF,SEMICOLON,ASC,FOR_UPDATE,-1};
 
const int token_group_134[]={NAMED,KW_DOT,QUESTION_MARK,NUMBER_VALUE,KW_MINUS,CHAR_VALUE,MARK_VAR,INT_VALUE,KW_CURRENT,-1};
 
const int token_group_57[]={WHEN,ELSE,-1};
 
const int token_group_75[]={KW_SELECT,VALUES,-1};
 
const int token_group_0[]={CREATE_SCHEMA,SQLSLMW,SQLSICR,SQLSICS,CREATE_UC_IDX,CREATE_DATABASE,DROP_AUDIT_FOR,LOCK_TABLE,EXECUTE_PROCEDURE,DELETE_FROM,CREATE_TABLE,SEMICOLON,INSERT_INTO,RENCOL,START_DATABASE,CREATE_SYNONYM,DATABASE,RECOVER_TABLE,ROLLFORWARD_DATABASE,UNLOCK_TABLE,ROLLBACK_W,SQLSEON,RENTAB,ALTER_INDEX,DROP_SYNONYM,UPDATESTATS,KW_UPDATE,COMMIT_W,KW_SELECT,SQLSIDR,CREATE_AUDIT_FOR,REVOKE,BEGIN_WORK,ALTER_TABLE,SET_BUFFERED_LOG,CREATE_IDX,CREATE_TEMP_TABLE,DROP_TRIGGER,SQLSLMNW,GRANT,CREATE_C_IDX,SQLSEOFF,DROP_DATABASE,DROP_INDEX,DROP_VIEW,DROP_TABLE,CREATE_VIEW,UPDATESTATS_T,SET_LOG,SQLSIRR,SET_CONSTRAINTS_ALL_IMMEDIATE,CREATE_U_IDX,-1};
 
const int token_group_30[]={KW_COMMA,KW_ON,-1};
 
const int token_group_34[]={CHAR_VALUE,-1};
 
const int token_group_141[]={NAMED,KW_ROWID,ATSIGN,CHAR_VALUE,INT_VALUE,-1};
 
const int token_group_96[]={GRANT,CREATE_VIEW,SEMICOLON,WITH_CHECK_OPTION,REVOKE,-1};
 
const int token_group_123[]={SEMICOLON,WITH_NO_LOG,-1};
 
const int token_group_85[]={OPEN_BRACKET,KW_TO,-1};
 
const int token_group_71[]={ALL,YEAR,OPEN_BRACKET,NUMBER_VALUE,XMIN,KW_DOT,ANY,KW_DOW,SOME,INT_VALUE,KW_ROWID,EXISTS,AVG,CASE,KW_TODAY,INTERVAL_VALUE,KW_FALSE,KW_DATE,NOT_EXISTS,KW_SUM,EXTEND,WEEKDAY,NAMED,MDY,QUESTION_MARK,COUNT_MULTIPLY,KW_TRUE,KW_MULTIPLY,DATETIME_VALUE,USER,TIME,MARK_VAR,CHAR_VALUE,MONTH,KW_PLUS,KW_CURRENT,KW_MINUS,XMAX,COUNT,DAY,-1};
 
const int token_group_125[]={KW_AND,-1};
 
const int token_group_21[]={OPEN_BRACKET,KW_AS,-1};
 
const int token_group_93[]={EXTENT_SIZE,LOCK_MODE_PAGE,SEMICOLON,LOCK_MODE_ROW,WITH_NO_LOG,NEXT_SIZE,KW_IN,-1};
 
const int token_group_72[]={SEMICOLON,KW_OR,-1};
 
const int token_group_142[]={GRANT,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,UNION,REVOKE,WITH_CHECK_OPTION,ORDER,GROUP_BY,HAVING,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_129[]={KW_PLUS,CLOSE_SQUARE,KW_MOD,KW_MINUS,KW_MULTIPLY,KW_DIVIDE,-1};
 
const int token_group_108[]={KW_COMMA,KW_PLUS,CLOSE_SQUARE,KW_MOD,KW_MINUS,KW_MULTIPLY,KW_DIVIDE,-1};
 
const int token_group_6[]={ALL,YEAR,OPEN_BRACKET,NUMBER_VALUE,XMIN,KW_DOT,ANY,KW_DOW,SOME,KW_ROWID,INT_VALUE,DISTINCT,AVG,CASE,KW_TODAY,INTERVAL_VALUE,KW_FALSE,KW_DATE,KW_SUM,UNIQUE,EXTEND,WEEKDAY,NAMED,MDY,QUESTION_MARK,COUNT_MULTIPLY,KW_TRUE,KW_MULTIPLY,DATETIME_VALUE,USER,TIME,MARK_VAR,CHAR_VALUE,MONTH,KW_PLUS,KW_FIRST,KW_CURRENT,KW_MINUS,XMAX,COUNT,DAY,-1};
 
const int token_group_16[]={TO_NOT_CLUSTER,TO_CLUSTER,-1};
 
const int token_group_86[]={KW_PLUS,OPEN_BRACKET,KW_MINUS,INT_VALUE,-1};
 
const int token_group_41[]={NAMED,FOREIGN_KEY,PRIMARY_KEY,CHECK,UNIQUE,DISTINCT,-1};
 
const int token_group_78[]={SOME,DAY,NAMED,KW_ROWID,KW_DOT,KW_DATE,COUNT,KW_SUM,AVG,KW_FALSE,KW_TRUE,MONTH,QUESTION_MARK,EXTEND,WEEKDAY,USER,KW_PLUS,OPEN_BRACKET,DATETIME_VALUE,NUMBER_VALUE,KW_DOW,YEAR,KW_MINUS,CHAR_VALUE,MARK_VAR,COUNT_MULTIPLY,KW_MULTIPLY,KW_TODAY,ALL,CASE,MDY,XMIN,INTERVAL_VALUE,INT_VALUE,ANY,XMAX,TIME,KW_CURRENT,-1};
 
const int token_group_77[]={GRANT,KW_COMMA,CREATE_VIEW,SEMICOLON,REVOKE,-1};
 
const int token_group_15[]={TO_NOT_CLUSTER,KW_DOT,SEMICOLON,KW_ON,TO_CLUSTER,-1};
 
const int token_group_155[]={LEFT_JOIN,KW_COMMA,KW_ON,INNER_JOIN,-1};
 
const int token_group_37[]={NAMED,OPEN_BRACKET,-1};
 
const int token_group_19[]={GRANT,CREATE_VIEW,REVOKE,-1};
 
const int token_group_94[]={LOCK_MODE_PAGE,EXTENT_SIZE,SEMICOLON,LOCK_MODE_ROW,NEXT_SIZE,KW_IN,-1};
 
const int token_group_25[]={KW_DOT,COLON,ATSIGN,-1};
 
const int token_group_156[]={FOR_UPDATE_OF,SEMICOLON,WITH_NO_LOG,FOR_UPDATE,-1};
 
const int token_group_111[]={KW_COMMA,DESC,ASC,CLOSE_BRACKET,-1};
 
const int token_group_40[]={GRANT,CREATE_VIEW,SEMICOLON,REVOKE,-1};
 
const int token_group_135[]={GRANT,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,UNION,WHERE,REVOKE,WITH_CHECK_OPTION,ORDER,GROUP_BY,HAVING,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_90[]={UNITS_MINUTE,YEAR,NOT_NULL_UNIQUE,EQUAL,UNITS_HOUR,WHEN,KW_THEN,UNITS_SECOND,DEFAULT_TODAY,SEMICOLON,UNITS_YEAR,WITH_CHECK_OPTION,NOT_ILIKE,KW_COMMA,UNION,DISTINCT,DEFAULT_USER,KW_ESCAPE,MINUTE,IS_NULL,PRIMARY_KEY,DEFAULT_NULL,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,WHERE_CURRENT_OF,KW_AS,DOUBLE_COLON,KW_DIVIDE,SECOND,GREATER_THAN,UNIQUE,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,REFERENCES,MATCHES,CHECK,KW_IN,DEFAULT,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ORDER,FROM,KW_ON,KW_MULTIPLY,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,MONTH,KW_AND,BEFORE,KW_PLUS,FOR_UPDATE,NOT_MATCHES,HOUR,END,KW_MINUS,INNER_JOIN,FOR_UPDATE_OF,GROUP_BY,GREATER_THAN_EQ,CREATE_VIEW,NOT_LIKE,LESS_THAN_EQ,NOT_NULL,IS_NOT_NULL,FRACTION,DAY,UNITS_DAY,-1};
 
const int token_group_153[]={KW_BY,-1};
 
const int token_group_131[]={NOT_NULL,KW_COMMA,OPEN_BRACKET,SEMICOLON,BEFORE,PRIMARY_KEY,CHECK,NOT_NULL_UNIQUE,UNIQUE,CLOSE_BRACKET,DISTINCT,REFERENCES,CONSTRAINT,-1};
 
const int token_group_110[]={NOT_NULL,KW_COMMA,SEMICOLON,BEFORE,PRIMARY_KEY,CHECK,NOT_NULL_UNIQUE,UNIQUE,DISTINCT,CLOSE_BRACKET,REFERENCES,-1};
 
const int token_group_107[]={KW_THEN,KW_OR,-1};
 
const int token_group_66[]={KW_COMMA,SEMICOLON,BEFORE,CLOSE_BRACKET,-1};
 
const int token_group_39[]={KW_COMMA,SEMICOLON,-1};
 
const int token_group_97[]={KW_OR,CLOSE_BRACKET,-1};
 
const int token_group_4[]={SEMICOLON,INT_VALUE,-1};
 
#include "mk_sstates_1.h"
static int SQLPARSE_allow_token_state(int yystate,int yytoken) {
int a;
int c;
const int *token_group;
  if (yytoken<0) return 1;
  token_group=token_groups[yystate];
  a=0;
  c=token_group[a];
  while (c>=0) {
    if (c==yytoken) return 1;
    c=token_group[++a];
  }
  return 0;
}
