 
const int token_group_137[]={CLOSE_SQUARE,-1};
 
const int token_group_28[]={SEMICOLON,EXCLUSIVE,-1};
 
const int token_group_150[]={INTO_TEMP,FOR_UPDATE_OF,SEMICOLON,ORDER,FOR_UPDATE,-1};
 
const int token_group_9[]={FOR_UPDATE_OF,SEMICOLON,FOR_UPDATE,-1};
 
const int token_group_51[]={ALL,YEAR,INTO,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,ATSIGN,KW_DOW,ANY,SOME,DATETIME,EXCLUSIVE,EXISTS,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,KW_UPDATE,CHECK,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ADD,KW_DELETE,ILIKE,GRANT,LIKE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,HOUR,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_88[]={WHEN,ELSE,END,-1};
 
const int token_group_14[]={OPEN_BRACKET,-1};
 
const int token_group_85[]={EQUAL,-1};
 
const int token_group_65[]={FOREIGN_KEY,PRIMARY_KEY,CHECK,UNIQUE,DISTINCT,-1};
 
const int token_group_149[]={KW_SELECT,ALL,UNIQUE,DISTINCT,-1};
 
const int token_group_33[]={ALL,YEAR,INTO,OPEN_BRACKET,DESC,MONEY,NUMBER_VALUE,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,ANY,KW_DOW,SOME,DATETIME,KW_ROWID,INT_VALUE,EXISTS,EXCLUSIVE,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,KW_TODAY,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,INTERVAL_VALUE,KW_NOT,BETWEEN,KW_TO,KW_AS,KW_FALSE,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,KW_TEXT,ELSE,WEEKDAY,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,MDY,KW_IN,DEFAULT,KW_FOR,HAVING,QUESTION_MARK,REVOKE,COUNT_MULTIPLY,ASC,DELIMITER,KW_TRUE,ADD,KW_DELETE,KW_MULTIPLY,USER,DATETIME_VALUE,ILIKE,TIME,GRANT,LIKE,MARK_VAR,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_PLUS,KW_CURRENT,KW_DECIMAL,KW_MINUS,HOUR,CONSTRAINT,DROP,KW_BYTE,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_86[]={END_MARK_VAR,-1};
 
const int token_group_80[]={KW_DOT,COLON,-1};
 
const int token_group_55[]={UNITS_MINUTE,ALL,YEAR,INTO,OPEN_BRACKET,EQUAL,DESC,MONEY,UNITS_HOUR,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,UNITS_SECOND,ANY,KW_DOW,SEMICOLON,UNITS_YEAR,SOME,DATETIME,WITH_CHECK_OPTION,NOT_ILIKE,EXISTS,EXCLUSIVE,KW_COMMA,UNION,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,IS_NULL,VARCHAR,XSET,DATABASE,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,WHERE_CURRENT_OF,KW_AS,MODIFY,NVARCHAR,DOUBLE_COLON,KW_DIVIDE,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,GREATER_THAN,UNIQUE,EXTEND,SMALLINT,KW_TEXT,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ASC,DELIMITER,ORDER,FROM,KW_ON,ADD,KW_DELETE,KW_MULTIPLY,OPEN_SQUARE,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,REAL,MONTH,KW_AND,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,HOUR,INNER_JOIN,FOR_UPDATE_OF,CONSTRAINT,GROUP_BY,GREATER_THAN_EQ,DROP,KW_BYTE,CREATE_VIEW,XMAX,NOT_LIKE,SMALLFLOAT,KW_BY,LESS_THAN_EQ,KW_INSERT,IS_NOT_NULL,DAY,COUNT,UNITS_DAY,FRACTION,-1};
 
const int token_group_95[]={UNITS_MINUTE,ALL,YEAR,INTO,NOT_NULL_UNIQUE,OPEN_BRACKET,EQUAL,DESC,MONEY,UNITS_HOUR,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,UNITS_SECOND,ANY,KW_DOW,DEFAULT_TODAY,SEMICOLON,UNITS_YEAR,SOME,DATETIME,WITH_CHECK_OPTION,NOT_ILIKE,EXISTS,EXCLUSIVE,KW_COMMA,UNION,AVG,DISTINCT,DEFAULT_USER,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,IS_NULL,VARCHAR,PRIMARY_KEY,DEFAULT_NULL,XSET,DATABASE,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,WHERE_CURRENT_OF,KW_AS,MODIFY,NVARCHAR,DOUBLE_COLON,KW_DIVIDE,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,GREATER_THAN,UNIQUE,EXTEND,SMALLINT,KW_TEXT,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ASC,DELIMITER,ORDER,FROM,KW_ON,ADD,KW_DELETE,KW_MULTIPLY,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,REAL,MONTH,KW_AND,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,HOUR,INNER_JOIN,FOR_UPDATE_OF,GROUP_BY,CONSTRAINT,GREATER_THAN_EQ,DROP,KW_BYTE,CREATE_VIEW,XMAX,NOT_LIKE,SMALLFLOAT,KW_BY,LESS_THAN_EQ,NOT_NULL,KW_INSERT,IS_NOT_NULL,DAY,COUNT,FRACTION,UNITS_DAY,-1};
 
const int token_group_54[]={ALL,YEAR,INTO,OPEN_BRACKET,NOT_NULL_UNIQUE,DESC,MONEY,INEXCLUSIVE,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,ANY,KW_DOW,SEMICOLON,SOME,DATETIME,WITH_CHECK_OPTION,EXISTS,EXCLUSIVE,KW_COMMA,UNION,AVG,DISTINCT,XSET_ident_DOT_MULTIPLY_EQUAL_OPEN_BRACKET,INSHARE,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,PRIMARY_KEY,XSET,DATABASE,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,WHERE_CURRENT_OF,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,COLON,UNIQUE,EXTEND,XSET_MULTIPLY_EQUAL,SMALLINT,KW_TEXT,ELSE,NAMED,XSET_OPEN_BRACKET,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,KW_SELECT,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ORDER,FROM,XSET_MULTIPLY_EQUAL_OPEN_BRACKET,KW_ON,ADD,KW_DELETE,ILIKE,GRANT,LIKE,INTO_TEMP,WHERE,REAL,XSET_ident_DOT_MULTIPLY_EQUAL,MONTH,VALUES,BEFORE,KW_DECIMAL,FOR_UPDATE,HOUR,INNER_JOIN,FOR_UPDATE_OF,CONSTRAINT,GROUP_BY,DROP,KW_BYTE,CREATE_VIEW,XMAX,SMALLFLOAT,KW_BY,NOT_NULL,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_156[]={GRANT,KW_DOT,KW_COMMA,INTO_TEMP,CREATE_VIEW,COLON,DESC,ATSIGN,FOR_UPDATE_OF,SEMICOLON,UNION,ASC,REVOKE,WITH_CHECK_OPTION,ORDER,OPEN_SQUARE,HAVING,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_124[]={KW_PLUS,KW_MOD,KW_MINUS,KW_MULTIPLY,KW_DIVIDE,CLOSE_BRACKET,-1};
 
const int token_group_118[]={KW_COMMA,CLOSE_SQUARE,-1};
 
const int token_group_59[]={UNITS_MINUTE,ALL,YEAR,INTO,EQUAL,DESC,MONEY,UNITS_HOUR,XMIN,NCHAR,INTERVAL,WHEN,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,UNITS_SECOND,ANY,KW_DOW,SEMICOLON,UNITS_YEAR,SOME,DATETIME,WITH_CHECK_OPTION,NOT_ILIKE,EXISTS,EXCLUSIVE,KW_COMMA,UNION,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,IS_NULL,VARCHAR,XSET,DATABASE,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,WHERE_CURRENT_OF,KW_AS,MODIFY,NVARCHAR,DOUBLE_COLON,KW_DIVIDE,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,GREATER_THAN,UNIQUE,EXTEND,SMALLINT,KW_TEXT,NOT_EQUAL,ELSE,NAMED,TILDE,NOT_IN,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ASC,DELIMITER,ORDER,FROM,KW_ON,ADD,KW_DELETE,KW_MULTIPLY,OPEN_SQUARE,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,REAL,MONTH,KW_AND,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,HOUR,INNER_JOIN,FOR_UPDATE_OF,CONSTRAINT,GROUP_BY,GREATER_THAN_EQ,DROP,KW_BYTE,CREATE_VIEW,XMAX,NOT_LIKE,SMALLFLOAT,KW_BY,LESS_THAN_EQ,KW_INSERT,IS_NOT_NULL,DAY,COUNT,UNITS_DAY,FRACTION,-1};
 
const int token_group_24[]={INSHARE,INEXCLUSIVE,-1};
 
const int token_group_102[]={GREATER_THAN,EQUAL,LESS_THAN,GREATER_THAN_EQ,NOT_MATCHES,IS_NULL,NOT_ILIKE,LESS_THAN_EQ,NOT_LIKE,IS_NOT_NULL,TILDE,NOT_EQUAL,MATCHES,ILIKE,BETWEEN,NOT_IN,LIKE,KW_IN,CLOSE_BRACKET,KW_NOT,-1};
 
const int token_group_160[]={INTO_TEMP,FOR_UPDATE_OF,SEMICOLON,FOR_UPDATE,-1};
 
const int token_group_154[]={ALL,YEAR,INTO,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOW,ANY,SOME,DATETIME,KW_ROWID,EXCLUSIVE,EXISTS,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ADD,KW_DELETE,ILIKE,GRANT,LIKE,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,HOUR,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_148[]={GRANT,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,UNION,REVOKE,WITH_CHECK_OPTION,ORDER,HAVING,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_144[]={LEFT_JOIN,GRANT,KW_COMMA,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,INNER_JOIN,WHERE,UNION,REVOKE,WITH_CHECK_OPTION,ORDER,HAVING,GROUP_BY,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_99[]={ALL,YEAR,INTO,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOW,ANY,SOME,DATETIME,EXCLUSIVE,EXISTS,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,KW_UPDATE,CHECK,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ADD,KW_DELETE,KW_MULTIPLY,ILIKE,GRANT,LIKE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,HOUR,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_1[]={-1,-1};
 
const int token_group_91[]={ALL,YEAR,INTO,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOW,ANY,SOME,DATETIME,KW_ROWID,EXCLUSIVE,EXISTS,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ADD,KW_DELETE,KW_MULTIPLY,ILIKE,GRANT,LIKE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,HOUR,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_25[]={KW_DOT,-1};
 
const int token_group_119[]={GRANT,LEFT_JOIN,KW_COMMA,INTO_TEMP,CREATE_VIEW,KW_ESCAPE,FOR_UPDATE_OF,SEMICOLON,KW_ON,INNER_JOIN,WHERE,UNION,REVOKE,WITH_CHECK_OPTION,KW_AND,ORDER,KW_OR,KW_THEN,HAVING,GROUP_BY,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_66[]={KW_COMMA,SEMICOLON,CONSTRAINT,-1};
 
const int token_group_7[]={ALL,YEAR,INTO,OPEN_BRACKET,DESC,MONEY,NUMBER_VALUE,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,ANY,KW_DOW,SOME,DATETIME,KW_ROWID,INT_VALUE,EXISTS,EXCLUSIVE,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,KW_TODAY,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,INTERVAL_VALUE,KW_NOT,BETWEEN,KW_TO,KW_AS,KW_FALSE,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,KW_TEXT,ELSE,WEEKDAY,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,MDY,KW_IN,DEFAULT,KW_FOR,HAVING,QUESTION_MARK,REVOKE,COUNT_MULTIPLY,ASC,DELIMITER,KW_TRUE,ADD,KW_DELETE,KW_MULTIPLY,USER,DATETIME_VALUE,ILIKE,TIME,GRANT,LIKE,MARK_VAR,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_PLUS,KW_FIRST,KW_CURRENT,KW_DECIMAL,KW_MINUS,HOUR,CONSTRAINT,DROP,KW_BYTE,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_8[]={SEMICOLON,-1};
 
const int token_group_93[]={UNITS_MINUTE,ALL,YEAR,INTO,OPEN_BRACKET,NOT_NULL_UNIQUE,EQUAL,DESC,MONEY,UNITS_HOUR,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,UNITS_SECOND,ANY,KW_DOW,DEFAULT_TODAY,SEMICOLON,UNITS_YEAR,SOME,DATETIME,WITH_CHECK_OPTION,NOT_ILIKE,EXISTS,EXCLUSIVE,KW_COMMA,UNION,AVG,DISTINCT,DEFAULT_USER,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,IS_NULL,VARCHAR,PRIMARY_KEY,DEFAULT_NULL,XSET,DATABASE,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,WHERE_CURRENT_OF,KW_AS,MODIFY,NVARCHAR,DOUBLE_COLON,KW_DIVIDE,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,GREATER_THAN,UNIQUE,EXTEND,SMALLINT,KW_TEXT,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ASC,DELIMITER,ORDER,FROM,KW_ON,ADD,KW_DELETE,KW_MULTIPLY,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,REAL,MONTH,KW_AND,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,HOUR,INNER_JOIN,FOR_UPDATE_OF,GROUP_BY,CONSTRAINT,GREATER_THAN_EQ,DROP,KW_BYTE,CREATE_VIEW,XMAX,NOT_LIKE,SMALLFLOAT,KW_BY,LESS_THAN_EQ,NOT_NULL,KW_INSERT,IS_NOT_NULL,DAY,COUNT,UNITS_DAY,FRACTION,-1};
 
const int token_group_74[]={EQUAL,GREATER_THAN,UNITS_HOUR,KW_DOT,LESS_THAN,IS_NULL,GREATER_THAN_EQ,NOT_MATCHES,UNITS_YEAR,KW_PLUS,NOT_ILIKE,DOUBLE_COLON,OPEN_BRACKET,LESS_THAN_EQ,UNITS_MONTH,KW_MINUS,NOT_LIKE,IS_NOT_NULL,UNITS_SECOND,TILDE,KW_MULTIPLY,NOT_EQUAL,MATCHES,ILIKE,OPEN_SQUARE,BETWEEN,UNITS_MINUTE,KW_DIVIDE,NOT_IN,LIKE,KW_IN,KW_NOT,CLOSE_BRACKET,UNITS_DAY,-1};
 
const int token_group_42[]={ALL,YEAR,INTO,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOW,ANY,SOME,DATETIME,EXCLUSIVE,EXISTS,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,PRIMARY_KEY,VARCHAR,XSET,DATABASE,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,KW_UPDATE,CHECK,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,FOREIGN_KEY,ADD,KW_DELETE,ILIKE,GRANT,LIKE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,HOUR,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_110[]={UNITS_HOUR,KW_COMMA,UNITS_YEAR,KW_PLUS,DOUBLE_COLON,UNITS_MONTH,KW_MINUS,UNITS_SECOND,KW_MULTIPLY,UNITS_MINUTE,KW_DIVIDE,UNITS_DAY,-1};
 
const int token_group_135[]={KW_COMMA,KW_PLUS,KW_MOD,CLOSE_SQUARE,KW_MINUS,KW_MULTIPLY,KW_DIVIDE,CLOSE_BRACKET,-1};
 
const int token_group_163[]={LEFT_JOIN,KW_COMMA,INNER_JOIN,CLOSE_BRACKET,-1};
 
const int token_group_32[]={INT_VALUE,-1};
 
const int token_group_151[]={ALL,YEAR,INTO,OPEN_BRACKET,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOW,ANY,SOME,DATETIME,EXCLUSIVE,EXISTS,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ADD,KW_DELETE,ILIKE,GRANT,LIKE,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,HOUR,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_143[]={UNITS_HOUR,KW_COMMA,UNITS_YEAR,KW_PLUS,DOUBLE_COLON,UNITS_MONTH,KW_MINUS,UNITS_SECOND,KW_MULTIPLY,UNITS_MINUTE,KW_DIVIDE,CLOSE_BRACKET,UNITS_DAY,-1};
 
const int token_group_109[]={KW_COMMA,-1};
 
const int token_group_71[]={KW_DOT,KW_COMMA,COLON,ATSIGN,OPEN_SQUARE,CLOSE_BRACKET,-1};
 
const int token_group_10[]={WITH_LOG_IN,-1};
 
const int token_group_70[]={TO_NOT_CLUSTER,COLON,SEMICOLON,KW_ON,TO_CLUSTER,-1};
 
const int token_group_62[]={KW_COMMA,CLOSE_BRACKET,-1};
 
const int token_group_67[]={KW_BYTE,KW_DATE,VARCHAR,KW_CHAR,SMALLINT,OPEN_BRACKET,MONEY,KW_FLOAT,KW_TEXT,INTEGER,NVARCHAR,NCHAR,SMALLFLOAT,KW_DECIMAL,REAL,DOUBLE_PRECISION,TIMESTAMP,SERIAL8,DATETIME,INTERVAL,TIME,SERIAL,-1};
 
const int token_group_56[]={UNITS_MINUTE,ALL,YEAR,INTO,EQUAL,DESC,MONEY,UNITS_HOUR,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,UNITS_SECOND,ANY,KW_DOW,SEMICOLON,UNITS_YEAR,SOME,DATETIME,WITH_CHECK_OPTION,NOT_ILIKE,EXISTS,EXCLUSIVE,KW_COMMA,UNION,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,IS_NULL,VARCHAR,XSET,DATABASE,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,WHERE_CURRENT_OF,KW_AS,MODIFY,NVARCHAR,DOUBLE_COLON,KW_DIVIDE,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,GREATER_THAN,UNIQUE,EXTEND,SMALLINT,KW_TEXT,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ASC,DELIMITER,ORDER,FROM,KW_ON,ADD,KW_DELETE,KW_MULTIPLY,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,REAL,MONTH,KW_AND,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,HOUR,INNER_JOIN,FOR_UPDATE_OF,CONSTRAINT,GROUP_BY,GREATER_THAN_EQ,DROP,KW_BYTE,CREATE_VIEW,XMAX,NOT_LIKE,SMALLFLOAT,KW_BY,LESS_THAN_EQ,KW_INSERT,IS_NOT_NULL,DAY,COUNT,UNITS_DAY,FRACTION,-1};
 
const int token_group_105[]={FROM,KW_COMMA,INTO_TEMP,FOR_UPDATE_OF,SEMICOLON,UNION,ORDER,FOR_UPDATE,-1};
 
const int token_group_87[]={CLOSE_BRACKET,-1};
 
const int token_group_34[]={XSET_OPEN_BRACKET,XSET,XSET_ident_DOT_MULTIPLY_EQUAL,XSET_MULTIPLY_EQUAL,XSET_ident_DOT_MULTIPLY_EQUAL_OPEN_BRACKET,XSET_MULTIPLY_EQUAL_OPEN_BRACKET,-1};
 
const int token_group_164[]={GRANT,KW_COMMA,INTO_TEMP,CREATE_VIEW,DESC,FOR_UPDATE_OF,SEMICOLON,UNION,ASC,REVOKE,WITH_CHECK_OPTION,ORDER,OPEN_SQUARE,HAVING,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_121[]={ALL,YEAR,INTO,DESC,MONEY,NUMBER_VALUE,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,KW_DOW,ANY,SOME,DATETIME,INT_VALUE,EXCLUSIVE,EXISTS,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,KW_SELECT,DEFAULT,KW_FOR,HAVING,QUESTION_MARK,REVOKE,ASC,DELIMITER,ADD,KW_DELETE,ILIKE,GRANT,LIKE,MARK_VAR,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,KW_CURRENT,HOUR,KW_MINUS,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_27[]={KW_TO,-1};
 
const int token_group_126[]={NOT_NULL,KW_COMMA,SEMICOLON,BEFORE,PRIMARY_KEY,CHECK,NOT_NULL_UNIQUE,UNIQUE,CONSTRAINT,CLOSE_BRACKET,DISTINCT,REFERENCES,-1};
 
const int token_group_83[]={KW_COMMA,WHERE_CURRENT_OF,SEMICOLON,WHERE,-1};
 
const int token_group_44[]={KW_AS,-1};
 
const int token_group_49[]={INDEX,ALTER,KW_DELETE,KW_SELECT,KW_UPDATE,KW_INSERT,-1};
 
const int token_group_104[]={KW_DOT,KW_COMMA,CLOSE_BRACKET,-1};
 
const int token_group_94[]={UNITS_MINUTE,ALL,YEAR,INTO,NOT_NULL_UNIQUE,EQUAL,DESC,MONEY,UNITS_HOUR,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,UNITS_SECOND,ANY,KW_DOW,DEFAULT_TODAY,SEMICOLON,UNITS_YEAR,SOME,DATETIME,WITH_CHECK_OPTION,NOT_ILIKE,EXISTS,EXCLUSIVE,KW_COMMA,UNION,AVG,DISTINCT,DEFAULT_USER,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,IS_NULL,VARCHAR,PRIMARY_KEY,DEFAULT_NULL,XSET,DATABASE,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,WHERE_CURRENT_OF,KW_AS,MODIFY,NVARCHAR,DOUBLE_COLON,KW_DIVIDE,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,GREATER_THAN,UNIQUE,EXTEND,SMALLINT,KW_TEXT,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ASC,DELIMITER,ORDER,FROM,KW_ON,ADD,KW_DELETE,KW_MULTIPLY,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,REAL,MONTH,KW_AND,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,HOUR,INNER_JOIN,FOR_UPDATE_OF,GROUP_BY,CONSTRAINT,GREATER_THAN_EQ,DROP,KW_BYTE,CREATE_VIEW,XMAX,NOT_LIKE,SMALLFLOAT,KW_BY,LESS_THAN_EQ,NOT_NULL,KW_INSERT,IS_NOT_NULL,DAY,COUNT,UNITS_DAY,FRACTION,-1};
 
const int token_group_39[]={ALL,YEAR,INTO,OPEN_BRACKET,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOW,ANY,SOME,DATETIME,EXCLUSIVE,EXISTS,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,PRIMARY_KEY,VARCHAR,XSET,DATABASE,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,KW_UPDATE,CHECK,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,FOREIGN_KEY,ADD,KW_DELETE,ILIKE,GRANT,LIKE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,HOUR,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_36[]={INTO,ALL,YEAR,OPEN_BRACKET,DESC,MONEY,NUMBER_VALUE,NCHAR,XMIN,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,ANY,KW_DOW,SOME,DATETIME,INT_VALUE,KW_ROWID,EXISTS,EXCLUSIVE,DISTINCT,AVG,KW_FLOAT,KW_ESCAPE,CASE,KW_TODAY,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,CLOSE_BRACKET,INTERVAL_VALUE,KW_NOT,BETWEEN,KW_TO,KW_AS,KW_FALSE,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,WEEKDAY,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,MDY,KW_IN,DEFAULT,KW_FOR,HAVING,QUESTION_MARK,REVOKE,COUNT_MULTIPLY,ASC,DELIMITER,KW_TRUE,ADD,KW_DELETE,KW_MULTIPLY,DATETIME_VALUE,USER,ILIKE,GRANT,TIME,LIKE,MARK_VAR,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,KW_CURRENT,HOUR,KW_MINUS,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,FRACTION,COUNT,DAY,-1};
 
const int token_group_152[]={ALL,YEAR,INTO,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOW,ANY,SOME,DATETIME,EXCLUSIVE,EXISTS,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ADD,KW_DELETE,ILIKE,GRANT,OUTER,LIKE,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,HOUR,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_132[]={UNITS_MINUTE,ALL,YEAR,INTO,EQUAL,DESC,MONEY,UNITS_HOUR,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,UNITS_SECOND,ANY,KW_DOW,SEMICOLON,UNITS_YEAR,SOME,DATETIME,WITH_CHECK_OPTION,NOT_ILIKE,EXISTS,EXCLUSIVE,KW_COMMA,UNION,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,IS_NULL,VARCHAR,XSET,DATABASE,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,WHERE_CURRENT_OF,KW_AS,MODIFY,NVARCHAR,DOUBLE_COLON,KW_DIVIDE,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,GREATER_THAN,UNIQUE,EXTEND,SMALLINT,KW_TEXT,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ASC,DELIMITER,ORDER,FROM,KW_ON,ADD,KW_DELETE,KW_MULTIPLY,OPEN_SQUARE,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,REAL,MONTH,KW_AND,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,HOUR,INNER_JOIN,FOR_UPDATE_OF,CONSTRAINT,GROUP_BY,GREATER_THAN_EQ,DROP,KW_BYTE,CREATE_VIEW,XMAX,NOT_LIKE,SMALLFLOAT,KW_BY,LESS_THAN_EQ,KW_INSERT,IS_NOT_NULL,DAY,COUNT,UNITS_DAY,FRACTION,-1};
 
const int token_group_82[]={INTO,ALL,YEAR,OPEN_BRACKET,DESC,MONEY,NUMBER_VALUE,NCHAR,XMIN,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,ANY,KW_DOW,SOME,DATETIME,INT_VALUE,KW_ROWID,EXISTS,EXCLUSIVE,DISTINCT,AVG,KW_FLOAT,KW_ESCAPE,CASE,KW_TODAY,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,INTERVAL_VALUE,KW_NOT,BETWEEN,KW_TO,KW_AS,KW_FALSE,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,WEEKDAY,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,MDY,KW_IN,DEFAULT,KW_FOR,HAVING,QUESTION_MARK,REVOKE,COUNT_MULTIPLY,ASC,DELIMITER,KW_TRUE,ADD,KW_DELETE,KW_MULTIPLY,DATETIME_VALUE,USER,ILIKE,GRANT,TIME,LIKE,MARK_VAR,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,KW_CURRENT,HOUR,KW_MINUS,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,FRACTION,COUNT,DAY,-1};
 
const int token_group_96[]={NOT_NULL,DEFAULT_NULL,KW_COMMA,SEMICOLON,BEFORE,PRIMARY_KEY,CHECK,NOT_NULL_UNIQUE,UNIQUE,DEFAULT_TODAY,DEFAULT_USER,DEFAULT,CLOSE_BRACKET,DISTINCT,REFERENCES,-1};
 
const int token_group_108[]={DAY,UNITS_HOUR,KW_COMMA,MONTH,UNITS_YEAR,KW_PLUS,DOUBLE_COLON,HOUR,SECOND,UNITS_MONTH,YEAR,KW_MINUS,UNITS_SECOND,KW_MULTIPLY,FRACTION,MINUTE,UNITS_MINUTE,KW_DIVIDE,UNITS_DAY,-1};
 
const int token_group_77[]={GRANT,LEFT_JOIN,KW_COMMA,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,KW_ON,INNER_JOIN,WHERE,UNION,REVOKE,WITH_CHECK_OPTION,KW_AND,ORDER,KW_OR,KW_THEN,HAVING,GROUP_BY,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_38[]={ALL,YEAR,INTO,OPEN_BRACKET,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOW,ANY,SOME,DATETIME,EXCLUSIVE,EXISTS,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,KW_UPDATE,CHECK,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ADD,KW_DELETE,ILIKE,GRANT,LIKE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,HOUR,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_68[]={KW_BYTE,VARCHAR,KW_DATE,KW_CHAR,SMALLINT,KW_FLOAT,MONEY,SMALLFLOAT,KW_TEXT,NVARCHAR,NCHAR,INTEGER,KW_DECIMAL,DOUBLE_PRECISION,REAL,TIMESTAMP,DATETIME,SERIAL8,INTERVAL,TIME,SERIAL,-1};
 
const int token_group_45[]={NAMED,-1};
 
const int token_group_52[]={KW_DOT,KW_COMMA,SEMICOLON,-1};
 
const int token_group_12[]={ALL,YEAR,INTO,OPEN_BRACKET,NOT_NULL_UNIQUE,DESC,MONEY,INEXCLUSIVE,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,ATSIGN,ANY,KW_DOW,SEMICOLON,SOME,DATETIME,WITH_CHECK_OPTION,EXISTS,EXCLUSIVE,KW_COMMA,UNION,AVG,DISTINCT,XSET_ident_DOT_MULTIPLY_EQUAL_OPEN_BRACKET,INSHARE,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,PRIMARY_KEY,XSET,DATABASE,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,WHERE_CURRENT_OF,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,COLON,UNIQUE,EXTEND,XSET_MULTIPLY_EQUAL,SMALLINT,KW_TEXT,ELSE,NAMED,XSET_OPEN_BRACKET,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,KW_SELECT,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ORDER,FROM,XSET_MULTIPLY_EQUAL_OPEN_BRACKET,KW_ON,ADD,KW_DELETE,ILIKE,GRANT,LIKE,INTO_TEMP,WHERE,REAL,XSET_ident_DOT_MULTIPLY_EQUAL,MONTH,VALUES,BEFORE,KW_DECIMAL,FOR_UPDATE,HOUR,INNER_JOIN,FOR_UPDATE_OF,CONSTRAINT,GROUP_BY,DROP,KW_BYTE,CREATE_VIEW,XMAX,SMALLFLOAT,KW_BY,NOT_NULL,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_142[]={EQUAL,KW_COMMA,OPEN_SQUARE,CLOSE_BRACKET,-1};
 
const int token_group_125[]={REFERENCES,-1};
 
const int token_group_120[]={UNITS_HOUR,GRANT,LEFT_JOIN,KW_COMMA,INTO_TEMP,CREATE_VIEW,UNITS_YEAR,KW_ESCAPE,KW_PLUS,FOR_UPDATE_OF,SEMICOLON,UNITS_MONTH,KW_ON,INNER_JOIN,UNITS_SECOND,KW_MINUS,WHERE,UNION,KW_MULTIPLY,REVOKE,WITH_CHECK_OPTION,KW_AND,ORDER,UNITS_MINUTE,KW_OR,KW_THEN,HAVING,GROUP_BY,KW_DIVIDE,UNITS_DAY,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_57[]={UNITS_MINUTE,ALL,YEAR,INTO,NOT_NULL_UNIQUE,EQUAL,DESC,MONEY,UNITS_HOUR,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,UNITS_SECOND,ANY,KW_DOW,SEMICOLON,UNITS_YEAR,SOME,DATETIME,WITH_CHECK_OPTION,NOT_ILIKE,EXISTS,EXCLUSIVE,KW_COMMA,UNION,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,IS_NULL,VARCHAR,PRIMARY_KEY,XSET,DATABASE,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,WHERE_CURRENT_OF,KW_AS,MODIFY,NVARCHAR,DOUBLE_COLON,KW_DIVIDE,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,GREATER_THAN,UNIQUE,EXTEND,SMALLINT,KW_TEXT,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ASC,DELIMITER,ORDER,FROM,KW_ON,ADD,KW_DELETE,KW_MULTIPLY,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,REAL,MONTH,KW_AND,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,HOUR,INNER_JOIN,FOR_UPDATE_OF,CONSTRAINT,GROUP_BY,GREATER_THAN_EQ,DROP,KW_BYTE,CREATE_VIEW,XMAX,NOT_LIKE,SMALLFLOAT,KW_BY,LESS_THAN_EQ,NOT_NULL,KW_INSERT,IS_NOT_NULL,DAY,COUNT,UNITS_DAY,FRACTION,-1};
 
const int token_group_47[]={OPEN_BRACKET,KW_SELECT,VALUES,-1};
 
const int token_group_117[]={KW_COMMA,OPEN_SQUARE,CLOSE_BRACKET,-1};
 
const int token_group_158[]={GRANT,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,UNION,REVOKE,WITH_CHECK_OPTION,ORDER,KW_OR,HAVING,GROUP_BY,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_129[]={KW_DOT,NUMBER_VALUE,INT_VALUE,-1};
 
const int token_group_84[]={EQUAL,KW_COMMA,KW_DOT,OPEN_SQUARE,CLOSE_BRACKET,-1};
 
const int token_group_72[]={KW_SELECT,-1};
 
const int token_group_58[]={INTO,ALL,YEAR,OPEN_BRACKET,DESC,MONEY,NUMBER_VALUE,NCHAR,XMIN,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,ANY,KW_DOW,SOME,DATETIME,INT_VALUE,KW_ROWID,EXISTS,EXCLUSIVE,DISTINCT,AVG,KW_FLOAT,KW_ESCAPE,CASE,KW_TODAY,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,INTERVAL_VALUE,KW_NOT,BETWEEN,KW_TO,KW_AS,KW_FALSE,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,WEEKDAY,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,MDY,KW_IN,KW_SELECT,DEFAULT,KW_FOR,HAVING,QUESTION_MARK,REVOKE,COUNT_MULTIPLY,ASC,DELIMITER,KW_TRUE,ADD,KW_DELETE,KW_MULTIPLY,DATETIME_VALUE,USER,ILIKE,GRANT,TIME,LIKE,MARK_VAR,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,KW_CURRENT,HOUR,KW_MINUS,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,FRACTION,COUNT,DAY,-1};
 
const int token_group_13[]={KW_IN,-1};
 
const int token_group_167[]={GRANT,LEFT_JOIN,KW_COMMA,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,KW_ON,INNER_JOIN,WHERE,UNION,REVOKE,WITH_CHECK_OPTION,ORDER,KW_OR,HAVING,GROUP_BY,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_165[]={KW_COMMA,INTO_TEMP,FOR_UPDATE_OF,SEMICOLON,FOR_UPDATE,-1};
 
const int token_group_23[]={WHERE_CURRENT_OF,SEMICOLON,WHERE,-1};
 
const int token_group_5[]={NAMED,CHAR_VALUE,-1};
 
const int token_group_21[]={KW_FOR,-1};
 
const int token_group_122[]={ALL,YEAR,INTO,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOW,ANY,SEMICOLON,SOME,WITH_CHECK_OPTION,DATETIME,EXCLUSIVE,EXISTS,KW_COMMA,UNION,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,KW_UPDATE,CHECK,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ORDER,FROM,ADD,KW_DELETE,ILIKE,GRANT,LIKE,INTO_TEMP,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,FOR_UPDATE,FOR_UPDATE_OF,HOUR,CONSTRAINT,KW_BYTE,CREATE_VIEW,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,FRACTION,COUNT,-1};
 
const int token_group_6[]={RESOURCE,INDEX,ALTER,KW_DELETE,DBA,KW_SELECT,CONNECT,ALL,KW_UPDATE,KW_INSERT,ALL_PRIVILEGES,-1};
 
const int token_group_29[]={KW_COMMA,OPEN_BRACKET,KW_ON,-1};
 
const int token_group_18[]={TO_NOT_CLUSTER,COLON,ATSIGN,SEMICOLON,KW_ON,TO_CLUSTER,-1};
 
const int token_group_15[]={MODIFY_NEXT_SIZE,ADD_CONSTRAINT,LOCK_MODE_PAGE,DROP_CONSTRAINT,LOCK_MODE_ROW,ADD,MODIFY,DROP,-1};
 
const int token_group_131[]={FROM,INTO_TEMP,FOR_UPDATE_OF,SEMICOLON,UNION,ORDER,FOR_UPDATE,-1};
 
const int token_group_53[]={SEMICOLON,MODE_ANSI,-1};
 
const int token_group_133[]={FROM,KW_COMMA,CLOSE_BRACKET,-1};
 
const int token_group_92[]={KW_COMMA,CONSTRAINT,CLOSE_BRACKET,-1};
 
const int token_group_145[]={ALL,YEAR,INTO,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOW,ANY,SEMICOLON,SOME,DATETIME,WITH_CHECK_OPTION,EXISTS,EXCLUSIVE,UNION,KW_COMMA,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ORDER,KW_ON,ADD,KW_DELETE,ILIKE,GRANT,LIKE,INTO_TEMP,WHERE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,FOR_UPDATE,HOUR,INNER_JOIN,FOR_UPDATE_OF,CONSTRAINT,GROUP_BY,KW_BYTE,DROP,CREATE_VIEW,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_127[]={USING_BTREE,SEMICOLON,USING_RTREE,FILLFACTOR,KW_IN,-1};
 
const int token_group_60[]={INTO,ALL,YEAR,OPEN_BRACKET,DESC,MONEY,NUMBER_VALUE,NCHAR,XMIN,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,ANY,KW_DOW,SOME,DATETIME,INT_VALUE,KW_ROWID,EXISTS,EXCLUSIVE,DISTINCT,AVG,KW_FLOAT,KW_ESCAPE,CASE,KW_TODAY,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,INTERVAL_VALUE,KW_NOT,BETWEEN,KW_TO,KW_AS,KW_FALSE,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,WEEKDAY,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,MDY,KW_IN,DEFAULT,KW_FOR,HAVING,QUESTION_MARK,REVOKE,COUNT_MULTIPLY,ASC,DELIMITER,KW_TRUE,ADD,KW_DELETE,KW_MULTIPLY,DATETIME_VALUE,USER,ILIKE,GRANT,TIME,LIKE,MARK_VAR,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,KW_CURRENT,HOUR,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,FRACTION,COUNT,DAY,-1};
 
const int token_group_157[]={GRANT,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,UNION,REVOKE,WITH_CHECK_OPTION,ORDER,KW_OR,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_116[]={LOCK_MODE_PAGE,EXTENT_SIZE,SEMICOLON,LOCK_MODE_ROW,WITH_NO_LOG,NEXT_SIZE,KW_IN,-1};
 
const int token_group_106[]={ALL,YEAR,INTO,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOW,ANY,SEMICOLON,SOME,DATETIME,WITH_CHECK_OPTION,EXISTS,EXCLUSIVE,UNION,KW_COMMA,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ORDER,FROM,ADD,KW_DELETE,ILIKE,GRANT,LIKE,INTO_TEMP,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,FOR_UPDATE,HOUR,FOR_UPDATE_OF,CONSTRAINT,KW_BYTE,DROP,CREATE_VIEW,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_3[]={ALL,YEAR,INTO,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOW,ANY,SOME,DATETIME,EXCLUSIVE,EXISTS,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,KW_UPDATE,CHECK,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ADD,KW_DELETE,ILIKE,GRANT,LIKE,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,HOUR,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_138[]={GRANT,FROM,KW_COMMA,CREATE_VIEW,SEMICOLON,REVOKE,WITH_CHECK_OPTION,-1};
 
const int token_group_37[]={FOREIGN_KEY,OPEN_BRACKET,PRIMARY_KEY,CHECK,UNIQUE,DISTINCT,-1};
 
const int token_group_113[]={KW_DOT,NUMBER_VALUE,CHAR_VALUE,INT_VALUE,KW_CURRENT,-1};
 
const int token_group_64[]={UNITS_MINUTE,ALL,YEAR,INTO,EQUAL,DESC,MONEY,UNITS_HOUR,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,UNITS_SECOND,ANY,KW_DOW,SEMICOLON,UNITS_YEAR,SOME,DATETIME,WITH_CHECK_OPTION,NOT_ILIKE,EXISTS,EXCLUSIVE,KW_COMMA,UNION,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,IS_NULL,VARCHAR,XSET,DATABASE,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,WHERE_CURRENT_OF,KW_AS,MODIFY,NVARCHAR,DOUBLE_COLON,KW_DIVIDE,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,GREATER_THAN,UNIQUE,EXTEND,SMALLINT,KW_TEXT,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ASC,DELIMITER,ORDER,FROM,KW_ON,ADD,KW_DELETE,KW_MULTIPLY,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,REAL,MONTH,KW_AND,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,HOUR,INNER_JOIN,FOR_UPDATE_OF,CONSTRAINT,GROUP_BY,GREATER_THAN_EQ,DROP,KW_BYTE,CREATE_VIEW,XMAX,NOT_LIKE,SMALLFLOAT,KW_BY,LESS_THAN_EQ,KW_INSERT,IS_NOT_NULL,DAY,COUNT,UNITS_DAY,FRACTION,-1};
 
const int token_group_30[]={FROM,-1};
 
const int token_group_141[]={INTO_TEMP,FOR_UPDATE_OF,SEMICOLON,UNION,ORDER,FOR_UPDATE,-1};
 
const int token_group_123[]={WITH_GRANT_OPTION,GRANT,KW_COMMA,CREATE_VIEW,SEMICOLON,REVOKE,KW_AS,-1};
 
const int token_group_103[]={IS_NULL,IS_NOT_NULL,BETWEEN,-1};
 
const int token_group_19[]={KW_ON,-1};
 
const int token_group_107[]={DAY,MONTH,HOUR,SECOND,YEAR,FRACTION,MINUTE,-1};
 
const int token_group_155[]={GRANT,KW_COMMA,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,UNION,REVOKE,WITH_CHECK_OPTION,ORDER,HAVING,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_78[]={GREATER_THAN,EQUAL,LESS_THAN,GREATER_THAN_EQ,NOT_MATCHES,IS_NULL,NOT_ILIKE,LESS_THAN_EQ,NOT_LIKE,IS_NOT_NULL,TILDE,NOT_EQUAL,MATCHES,ILIKE,BETWEEN,NOT_IN,LIKE,KW_IN,KW_NOT,-1};
 
const int token_group_50[]={INTO,ALL,YEAR,OPEN_BRACKET,DESC,MONEY,NUMBER_VALUE,NCHAR,XMIN,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,ANY,KW_DOW,SOME,DATETIME,INT_VALUE,KW_ROWID,EXISTS,EXCLUSIVE,DISTINCT,AVG,KW_FLOAT,KW_ESCAPE,CASE,KW_TODAY,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,INTERVAL_VALUE,KW_NOT,BETWEEN,KW_TO,KW_AS,KW_NULL,KW_FALSE,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,WEEKDAY,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,MDY,KW_IN,DEFAULT,KW_FOR,HAVING,QUESTION_MARK,REVOKE,COUNT_MULTIPLY,ASC,DELIMITER,KW_TRUE,ADD,KW_DELETE,KW_MULTIPLY,DATETIME_VALUE,USER,ILIKE,GRANT,TIME,LIKE,MARK_VAR,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,KW_CURRENT,HOUR,KW_MINUS,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,FRACTION,COUNT,DAY,-1};
 
const int token_group_166[]={KW_COMMA,INTO_TEMP,DESC,FOR_UPDATE_OF,SEMICOLON,ASC,FOR_UPDATE,-1};
 
const int token_group_61[]={UNITS_MINUTE,ALL,INTO,YEAR,EQUAL,DESC,MONEY,UNITS_HOUR,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,UNITS_SECOND,ANY,KW_DOW,SEMICOLON,UNITS_YEAR,SOME,DATETIME,WITH_CHECK_OPTION,NOT_ILIKE,EXISTS,EXCLUSIVE,KW_COMMA,UNION,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,RESOURCE,MINUTE,FILLFACTOR,DBA,IS_NULL,VARCHAR,XSET,DATABASE,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,WHERE_CURRENT_OF,KW_AS,MODIFY,NVARCHAR,DOUBLE_COLON,KW_DIVIDE,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,GREATER_THAN,UNIQUE,EXTEND,SMALLINT,KW_TEXT,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ASC,DELIMITER,ORDER,FROM,KW_ON,ADD,KW_DELETE,KW_MULTIPLY,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,REAL,MONTH,KW_AND,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,INNER_JOIN,HOUR,FOR_UPDATE_OF,GROUP_BY,CONSTRAINT,GREATER_THAN_EQ,DROP,KW_BYTE,CREATE_VIEW,XMAX,NOT_LIKE,SMALLFLOAT,KW_BY,LESS_THAN_EQ,KW_INSERT,IS_NOT_NULL,COUNT,UNITS_DAY,FRACTION,DAY,-1};
 
const int token_group_146[]={ALL,YEAR,INTO,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,ATSIGN,KW_DOW,ANY,SOME,DATETIME,INT_VALUE,KW_ROWID,EXCLUSIVE,EXISTS,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ADD,KW_DELETE,ILIKE,GRANT,LIKE,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,HOUR,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_79[]={KW_SELECT,VALUES,-1};
 
const int token_group_0[]={CREATE_SCHEMA,SQLSLMW,SQLSICR,SQLSICS,CREATE_UC_IDX,CREATE_DATABASE,DROP_AUDIT_FOR,LOCK_TABLE,EXECUTE_PROCEDURE,DELETE_FROM,CREATE_TABLE,SEMICOLON,INSERT_INTO,RENCOL,START_DATABASE,CREATE_SYNONYM,DATABASE,RECOVER_TABLE,ROLLFORWARD_DATABASE,UNLOCK_TABLE,ROLLBACK_W,SQLSEON,RENTAB,ALTER_INDEX,DROP_SYNONYM,UPDATESTATS,KW_UPDATE,COMMIT_W,KW_SELECT,SQLSIDR,CREATE_AUDIT_FOR,REVOKE,BEGIN_WORK,ALTER_TABLE,SET_BUFFERED_LOG,CREATE_IDX,CREATE_TEMP_TABLE,DROP_TRIGGER,SQLSLMNW,GRANT,CREATE_C_IDX,SQLSEOFF,DROP_DATABASE,DROP_INDEX,DROP_VIEW,DROP_TABLE,CREATE_VIEW,UPDATESTATS_T,SET_LOG,SQLSIRR,SET_CONSTRAINTS_ALL_IMMEDIATE,CREATE_U_IDX,-1};
 
const int token_group_31[]={KW_COMMA,KW_ON,-1};
 
const int token_group_35[]={CHAR_VALUE,-1};
 
const int token_group_100[]={GRANT,CREATE_VIEW,SEMICOLON,WITH_CHECK_OPTION,REVOKE,-1};
 
const int token_group_153[]={ALL,YEAR,INTO,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOW,ANY,SEMICOLON,SOME,WITH_CHECK_OPTION,DATETIME,EXCLUSIVE,EXISTS,KW_COMMA,UNION,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,LEFT_JOIN,XSET,DATABASE,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,KW_UPDATE,CHECK,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ORDER,KW_ON,ADD,KW_DELETE,ILIKE,GRANT,LIKE,INTO_TEMP,WHERE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,FOR_UPDATE,FOR_UPDATE_OF,INNER_JOIN,HOUR,GROUP_BY,CONSTRAINT,KW_BYTE,CREATE_VIEW,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,FRACTION,COUNT,-1};
 
const int token_group_128[]={SEMICOLON,WITH_NO_LOG,-1};
 
const int token_group_89[]={OPEN_BRACKET,KW_TO,-1};
 
const int token_group_2[]={ALL,YEAR,INTO,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOW,ANY,SOME,DATETIME,EXCLUSIVE,EXISTS,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,KW_UPDATE,CHECK,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ADD,KW_DELETE,ILIKE,GRANT,LIKE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,HOUR,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,FRACTION,COUNT,-1};
 
const int token_group_130[]={KW_AND,-1};
 
const int token_group_22[]={OPEN_BRACKET,KW_AS,-1};
 
const int token_group_97[]={EXTENT_SIZE,LOCK_MODE_PAGE,SEMICOLON,LOCK_MODE_ROW,WITH_NO_LOG,NEXT_SIZE,KW_IN,-1};
 
const int token_group_76[]={SEMICOLON,KW_OR,-1};
 
const int token_group_46[]={INTO,ALL,YEAR,OPEN_BRACKET,DESC,MONEY,NUMBER_VALUE,NCHAR,XMIN,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,ANY,KW_DOW,SOME,DATETIME,INT_VALUE,KW_ROWID,EXCLUSIVE,EXISTS,DISTINCT,AVG,KW_FLOAT,KW_ESCAPE,CASE,KW_TODAY,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,INTERVAL_VALUE,KW_NOT,BETWEEN,KW_TO,KW_AS,KW_FALSE,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,NOT_EXISTS,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,WEEKDAY,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,MDY,KW_IN,DEFAULT,KW_FOR,HAVING,QUESTION_MARK,REVOKE,COUNT_MULTIPLY,ASC,DELIMITER,KW_TRUE,ADD,KW_DELETE,KW_MULTIPLY,DATETIME_VALUE,USER,ILIKE,GRANT,TIME,LIKE,MARK_VAR,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,KW_CURRENT,HOUR,KW_MINUS,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,FRACTION,COUNT,DAY,-1};
 
const int token_group_147[]={GRANT,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,UNION,REVOKE,WITH_CHECK_OPTION,ORDER,GROUP_BY,HAVING,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_48[]={ALL,YEAR,INTO,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOW,ANY,SOME,DATETIME,EXCLUSIVE,EXISTS,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ADD,KW_DELETE,ILIKE,GRANT,LIKE,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,PUBLIC,HOUR,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_134[]={KW_PLUS,CLOSE_SQUARE,KW_MOD,KW_MINUS,KW_MULTIPLY,KW_DIVIDE,-1};
 
const int token_group_112[]={KW_COMMA,KW_PLUS,CLOSE_SQUARE,KW_MOD,KW_MINUS,KW_MULTIPLY,KW_DIVIDE,-1};
 
const int token_group_17[]={TO_NOT_CLUSTER,TO_CLUSTER,-1};
 
const int token_group_90[]={KW_PLUS,OPEN_BRACKET,KW_MINUS,INT_VALUE,-1};
 
const int token_group_11[]={ALL,YEAR,INTO,OPEN_BRACKET,NOT_NULL_UNIQUE,DESC,MONEY,INEXCLUSIVE,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,ANY,KW_DOW,SEMICOLON,SOME,DATETIME,WITH_CHECK_OPTION,EXISTS,EXCLUSIVE,KW_COMMA,UNION,AVG,DISTINCT,XSET_ident_DOT_MULTIPLY_EQUAL_OPEN_BRACKET,INSHARE,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,PRIMARY_KEY,XSET,DATABASE,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,WHERE_CURRENT_OF,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,XSET_MULTIPLY_EQUAL,SMALLINT,KW_TEXT,ELSE,NAMED,XSET_OPEN_BRACKET,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,KW_SELECT,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ORDER,FROM,XSET_MULTIPLY_EQUAL_OPEN_BRACKET,KW_ON,ADD,KW_DELETE,ILIKE,GRANT,LIKE,INTO_TEMP,WHERE,REAL,XSET_ident_DOT_MULTIPLY_EQUAL,MONTH,VALUES,BEFORE,KW_DECIMAL,FOR_UPDATE,HOUR,INNER_JOIN,FOR_UPDATE_OF,CONSTRAINT,GROUP_BY,DROP,KW_BYTE,CREATE_VIEW,XMAX,SMALLFLOAT,KW_BY,NOT_NULL,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_81[]={GRANT,KW_COMMA,CREATE_VIEW,SEMICOLON,REVOKE,-1};
 
const int token_group_16[]={TO_NOT_CLUSTER,KW_DOT,SEMICOLON,KW_ON,TO_CLUSTER,-1};
 
const int token_group_161[]={LEFT_JOIN,KW_COMMA,KW_ON,INNER_JOIN,-1};
 
const int token_group_73[]={INTO,ALL,YEAR,OPEN_BRACKET,DESC,MONEY,NUMBER_VALUE,NCHAR,XMIN,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,ANY,KW_DOW,SOME,DATETIME,INT_VALUE,KW_ROWID,EXCLUSIVE,EXISTS,DISTINCT,AVG,KW_FLOAT,KW_ESCAPE,CASE,KW_TODAY,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,INTERVAL_VALUE,KW_NOT,BETWEEN,KW_TO,KW_AS,KW_FALSE,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,NOT_EXISTS,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,WEEKDAY,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,MDY,KW_IN,KW_SELECT,DEFAULT,KW_FOR,HAVING,QUESTION_MARK,REVOKE,COUNT_MULTIPLY,ASC,DELIMITER,KW_TRUE,ADD,KW_DELETE,KW_MULTIPLY,DATETIME_VALUE,USER,ILIKE,GRANT,TIME,LIKE,MARK_VAR,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,KW_CURRENT,HOUR,KW_MINUS,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,FRACTION,COUNT,DAY,-1};
 
const int token_group_20[]={GRANT,CREATE_VIEW,REVOKE,-1};
 
const int token_group_98[]={LOCK_MODE_PAGE,EXTENT_SIZE,SEMICOLON,LOCK_MODE_ROW,NEXT_SIZE,KW_IN,-1};
 
const int token_group_139[]={ALL,YEAR,INTO,DESC,MONEY,NUMBER_VALUE,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,KW_DOW,ANY,SOME,DATETIME,INT_VALUE,EXCLUSIVE,EXISTS,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,QUESTION_MARK,REVOKE,ASC,DELIMITER,ADD,KW_DELETE,ILIKE,GRANT,LIKE,MARK_VAR,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,KW_CURRENT,HOUR,KW_MINUS,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_43[]={ALL,YEAR,INTO,DESC,MONEY,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,ATSIGN,KW_DOW,ANY,SOME,DATETIME,EXCLUSIVE,EXISTS,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,VARCHAR,XSET,DATABASE,KW_NOT,BETWEEN,KW_TO,KW_AS,MODIFY,NVARCHAR,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,UNIQUE,EXTEND,SMALLINT,ELSE,KW_TEXT,NAMED,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,REVOKE,ASC,DELIMITER,ADD,KW_DELETE,ILIKE,GRANT,LIKE,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_DECIMAL,HOUR,CONSTRAINT,KW_BYTE,DROP,XMAX,SMALLFLOAT,KW_BY,KW_INSERT,DAY,COUNT,FRACTION,-1};
 
const int token_group_26[]={KW_DOT,COLON,ATSIGN,-1};
 
const int token_group_162[]={FOR_UPDATE_OF,SEMICOLON,WITH_NO_LOG,FOR_UPDATE,-1};
 
const int token_group_115[]={KW_COMMA,DESC,ASC,CLOSE_BRACKET,-1};
 
const int token_group_41[]={GRANT,CREATE_VIEW,SEMICOLON,REVOKE,-1};
 
const int token_group_140[]={GRANT,INTO_TEMP,CREATE_VIEW,FOR_UPDATE_OF,SEMICOLON,UNION,WHERE,REVOKE,WITH_CHECK_OPTION,ORDER,GROUP_BY,HAVING,CLOSE_BRACKET,FOR_UPDATE,-1};
 
const int token_group_75[]={UNITS_MINUTE,INTO,ALL,YEAR,OPEN_BRACKET,EQUAL,DESC,MONEY,UNITS_HOUR,NUMBER_VALUE,NCHAR,XMIN,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,UNITS_SECOND,KW_DOT,ANY,KW_DOW,UNITS_YEAR,SOME,DATETIME,NOT_ILIKE,INT_VALUE,KW_ROWID,EXCLUSIVE,EXISTS,DISTINCT,AVG,KW_FLOAT,KW_ESCAPE,CASE,KW_TODAY,MINUTE,RESOURCE,FILLFACTOR,IS_NULL,DBA,VARCHAR,XSET,DATABASE,CLOSE_BRACKET,INTERVAL_VALUE,KW_NOT,BETWEEN,KW_TO,KW_AS,KW_FALSE,DOUBLE_COLON,MODIFY,NVARCHAR,KW_DIVIDE,KW_DATE,SERIAL,INTEGER,INDEX,NOT_EXISTS,KW_SUM,SECOND,GREATER_THAN,UNIQUE,EXTEND,SMALLINT,ELSE,NOT_EQUAL,KW_TEXT,WEEKDAY,NAMED,TILDE,NOT_IN,REFERENCES,MATCHES,CHECK,KW_UPDATE,MDY,KW_IN,DEFAULT,KW_FOR,HAVING,QUESTION_MARK,UNITS_MONTH,LESS_THAN,REVOKE,COUNT_MULTIPLY,ASC,DELIMITER,KW_TRUE,ADD,KW_DELETE,KW_MULTIPLY,OPEN_SQUARE,DATETIME_VALUE,USER,ILIKE,GRANT,TIME,LIKE,MARK_VAR,CHAR_VALUE,REAL,MONTH,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,KW_CURRENT,NOT_MATCHES,HOUR,KW_MINUS,GREATER_THAN_EQ,CONSTRAINT,KW_BYTE,DROP,NOT_LIKE,XMAX,SMALLFLOAT,KW_BY,LESS_THAN_EQ,IS_NOT_NULL,KW_INSERT,UNITS_DAY,FRACTION,COUNT,DAY,-1};
 
const int token_group_159[]={KW_BY,-1};
 
const int token_group_63[]={UNITS_MINUTE,ALL,YEAR,INTO,EQUAL,DESC,MONEY,UNITS_HOUR,XMIN,NCHAR,WHEN,INTERVAL,KW_THEN,CONNECT,ALTER,KW_CHAR,KW_DOT,UNITS_SECOND,ANY,KW_DOW,SEMICOLON,UNITS_YEAR,SOME,DATETIME,WITH_CHECK_OPTION,NOT_ILIKE,EXISTS,EXCLUSIVE,KW_COMMA,UNION,AVG,DISTINCT,CASE,KW_FLOAT,KW_ESCAPE,MINUTE,RESOURCE,FILLFACTOR,DBA,IS_NULL,VARCHAR,XSET,DATABASE,LEFT_JOIN,CLOSE_BRACKET,KW_NOT,BETWEEN,KW_TO,WHERE_CURRENT_OF,KW_AS,MODIFY,NVARCHAR,DOUBLE_COLON,KW_DIVIDE,KW_DATE,SERIAL,INTEGER,INDEX,KW_SUM,SECOND,GREATER_THAN,UNIQUE,EXTEND,SMALLINT,KW_TEXT,ELSE,NOT_EQUAL,NAMED,TILDE,NOT_IN,REFERENCES,MATCHES,CHECK,KW_UPDATE,KW_IN,DEFAULT,KW_FOR,HAVING,UNITS_MONTH,LESS_THAN,REVOKE,ASC,DELIMITER,ORDER,FROM,KW_ON,ADD,KW_DELETE,KW_MULTIPLY,OPEN_SQUARE,ILIKE,KW_OR,GRANT,LIKE,INTO_TEMP,WHERE,REAL,MONTH,KW_AND,VALUES,BEFORE,KW_PLUS,KW_DECIMAL,FOR_UPDATE,NOT_MATCHES,END,KW_MINUS,HOUR,INNER_JOIN,FOR_UPDATE_OF,CONSTRAINT,GROUP_BY,GREATER_THAN_EQ,DROP,KW_BYTE,CREATE_VIEW,XMAX,NOT_LIKE,SMALLFLOAT,KW_BY,LESS_THAN_EQ,KW_INSERT,IS_NOT_NULL,DAY,COUNT,UNITS_DAY,FRACTION,-1};
 
const int token_group_136[]={NOT_NULL,KW_COMMA,OPEN_BRACKET,SEMICOLON,BEFORE,PRIMARY_KEY,CHECK,NOT_NULL_UNIQUE,UNIQUE,CLOSE_BRACKET,DISTINCT,REFERENCES,CONSTRAINT,-1};
 
const int token_group_114[]={NOT_NULL,KW_COMMA,SEMICOLON,BEFORE,PRIMARY_KEY,CHECK,NOT_NULL_UNIQUE,UNIQUE,DISTINCT,CLOSE_BRACKET,REFERENCES,-1};
 
const int token_group_111[]={KW_THEN,KW_OR,-1};
 
const int token_group_69[]={KW_COMMA,SEMICOLON,BEFORE,CLOSE_BRACKET,-1};
 
const int token_group_40[]={KW_COMMA,SEMICOLON,-1};
 
const int token_group_101[]={KW_OR,CLOSE_BRACKET,-1};
 
const int token_group_4[]={SEMICOLON,INT_VALUE,-1};
 
#include "mk_sstates_1.h"
static int SQLPARSE_allow_token_state(int yystate,int yytoken) {
int a;
int c;
const int *token_group;
  if (yytoken<0) return 1;
  token_group=token_groups[yystate];
  a=0;
  c=token_group[a];
  while (c>=0) {
    if (c==yytoken) return 1;
    c=token_group[++a];
  }
  return 0;
}
