

m1.4ae: m1.4gl
	$(FGLC) m1.4gl -o m1.4ae

compile: m1.4ae
	
run: m1.4ae
	sh ./run_m1

ansi_sql_compat:
	@echo "1"

desc:
	@echo "4J$ style dynamic array handling"

sql_features_used:		; @echo "DATABASE_USED DEFINE_SMALLINT CREATE_TEMP_TABLE DEFINE_CHAR PREPARE CURSOR_SELECT SCROLL_CURSOR OPEN_CURSOR "

