head	1.1;
access;
symbols;
locks; strict;
comment	@# @;


1.1
date	88.09.09.12.31.46;	author john;	state Exp;
branches;
next	;


desc
@@


1.1
log
@Initial revision
@
text
@# @@(#)$Id: phlpchk1.msg,v 1.1 2002-06-14 05:03:46 afalout Exp $
# @@(#)Sphinx Informix Tools: test help file stack
# @@(#)Help messages

.100
HELP FILE NUMBER 1, MESSAGE 100

$RCSfile: phlpchk1.msg,v $ version $Revision: 1.1 $ dated $Date: 2002-06-14 05:03:46 $

@
