 
const int token_group_121[]={EQUAL,SEMICOLON,COMMA,COMPRESS,NONCOMPRESS,-1};
 
const int token_group_85[]={CLOSE_SQUARE,-1};
 
const int token_group_21[]={NAMED,OPEN_BRACKET,OPEN_BRACE,-1};
 
const int token_group_68[]={EQUAL,TYPE,KWNOT,SEMICOLON,COMMA,ALLOWING,OPEN_SQUARE,-1};
 
const int token_group_56[]={NAMED,KW_END,ATTRIBUTES,COLON,COMMA,-1};
 
const int token_group_33[]={KW_EDIT,NAMED,KW_IMAGE,KW_DATEEDIT,KW_BROWSER,KW_CHECKBOX,KW_COMBOBOX,KW_END,INSTRUCTIONS,KW_TEXTEDIT,KW_BUTTONEDIT,KW_LABEL,KW_PROGRESSBAR,-1};
 
const int token_group_59[]={COMMA,GREATERTHAN,-1};
 
const int token_group_43[]={OPEN_BRACKET,-1};
 
const int token_group_50[]={EQUAL,-1};
 
const int token_group_113[]={LISTBOX,-1};
 
const int token_group_131[]={JOINING,COMMA,DOT,-1};
 
const int token_group_102[]={EQUAL,SEMICOLON,COMMA,-1};
 
const int token_group_19[]={NUMBER_VALUE,-1};
 
const int token_group_23[]={EQUAL,NAMED,KW_END,ATTRIBUTES,COMMA,-1};
 
const int token_group_97[]={EQUAL,STAR,KWAND,KWBETWEEN,KWNOTNULLCHK,KWNOT,LESSTHAN,COMPARISON,KWOR,COMMA,GREATERTHAN,KWIN,DIVIDE,KWNULLCHK,PLUS,LIKE,MINUS,CLOSE_BRACKET,-1};
 
const int token_group_126[]={KW_VARIABLE,KW_FIXED,-1};
 
const int token_group_22[]={OPEN_BRACKET,KW_PAGE,-1};
 
const int token_group_58[]={NAMED,KW_IF,KW_LET,COMMA,KW_BEGIN,GREATERTHAN,DOT,KW_NEXTFIELD,KW_ABORT,KW_CALL,COMMENTS,-1};
 
const int token_group_133[]={COLON,COMMA,TO,CLOSE_BRACKET,-1};
 
const int token_group_125[]={NUMBER_VALUE,CHAR_VALUE,SQL_VAR,-1};
 
const int token_group_98[]={EQUAL,TYPE,KWNOT,SEMICOLON,COMMA,OPEN_SQUARE,-1};
 
const int token_group_2[]={-1,-1};
 
const int token_group_3[]={KW_SCREEN,CHARACTER_ENCODING,KW_SCREEN_TITLE,KW_LAYOUT,-1};
 
const int token_group_35[]={OPEN_BRACE,-1};
 
const int token_group_87[]={NAMED,COMMA,FORMONLY,CLOSE_BRACKET,-1};
 
const int token_group_112[]={KW_VALUEMIN,REQUIRED,CONFIG,PROGRAM,KW_AUTOSCALE,KW_RIGHT,KW_VALUECHECKED,KW_STRETCH_BOTH,KW_HIDDEN,NOENTRY,KW_WANTTABS,FORMAT,AUTONEXT,SQLONLY,REVERSE,KW_ACTION,KW_FONTPITCH,KW_ZEROFILL,KW_SCROLLBARS_H,KW_SCROLLBARS_BOTH,KW_IMAGE,KW_TEXT,COLOR,LOOKUP,WIDGET,KW_SCROLL,QUERYCLEAR,VERIFY,PICTURE,KW_SCROLLBARS_V,DEFAULT,WORDWRAP,INVISIBLE,VALIDATE,DOWNSHIFT,KW_PIXELWIDTH,KW_STRETCH_Y,DYNAMIC,DISPLAY,KW_WANTNORETURNS,LOOKUP_FROM,KW_STYLE,OPTIONS,KW_ITEMS,KW_VALUEMAX,INCLUDE,NOUPDATE,COMMENTS,KW_PIXELHEIGHT,UPSHIFT,KW_VALUEUNCHECKED,-1};
 
const int token_group_66[]={NAMED,KW_IF,KW_LET,COMMA,KW_BEGIN,KW_CALL,KW_NEXTFIELD,KW_ABORT,COMMENTS,-1};
 
const int token_group_129[]={EQUAL,KWWHERE,LEFT,MAGENTA,RED,REVERSE,WHITE,UNDERLINE,CYAN,SEMICOLON,BOLD,NUMBER_VALUE,GREEN,COMMA,NORMAL,BLINK,BLACK,DIM,YELLOW,BLUE,-1};
 
const int token_group_55[]={NAMED,KW_TAB,KW_NL,PIPE,KW_NONSPACE,KW_WS,CHAR_VALUE,OPEN_SQUARE,CH,GRAPH_CH,-1};
 
const int token_group_90[]={REVERSE,CHAR_VALUE,-1};
 
const int token_group_15[]={NAMED,KW_END,KW_GROUP,OPEN_BRACKET,KW_TABLE,KW_GRID,KW_HBOX,KW_VBOX,KW_FOLDER,-1};
 
const int token_group_136[]={NAMED,NUMBER_VALUE,XVAL,CHAR_VALUE,-1};
 
const int token_group_40[]={NAMED,KW_END,ATTRIBUTES,COLON,ATSIGN,COMMA,DOT,-1};
 
const int token_group_135[]={KWAND,EQUAL,KWBETWEEN,SEMICOLON,KWNOTNULLCHK,KWNOT,LESSTHAN,KWOR,COMPARISON,COMMA,GREATERTHAN,KWIN,KWNULLCHK,LIKE,CLOSE_BRACKET,-1};
 
const int token_group_108[]={KW_TAB,PIPE,CLOSE_SQUARE,KW_WS,-1};
 
const int token_group_91[]={NAMED,KW_EXITNOW,-1};
 
const int token_group_109[]={EQUAL,OPEN_BRACKET,KWNOT,SEMICOLON,COMMA,TO,OPEN_SQUARE,-1};
 
const int token_group_86[]={NAMED,THROUGH,COMMA,DOT,FORMONLY,CLOSE_BRACKET,-1};
 
const int token_group_16[]={NAMED,OPEN_BRACKET,KW_PAGE,-1};
 
const int token_group_117[]={NAMED,KW_SCREEN,KW_COMPOSITES,KW_ON_BEGINNING,KW_END,KW_AFTER,KW_IF,SEMICOLON,KW_LET,KW_ON_ENDING,KW_BEGIN,KW_PANEL,KW_ELSE,KW_NEXTFIELD,KW_ABORT,KW_CALL,DELIMITERS,KW_BEFORE,COMMENTS,-1};
 
const int token_group_24[]={NAMED,KW_END,ATTRIBUTES,COMMA,-1};
 
const int token_group_116[]={NAMED,NUMBER_VALUE,XVAL,CHAR_VALUE,KW_NULL,-1};
 
const int token_group_76[]={KW_IF,KW_LET,KW_BEGIN,KW_CALL,KW_NEXTFIELD,KW_ABORT,COMMENTS,-1};
 
const int token_group_114[]={EQUAL,STAR,KWAND,NAMED,KW_SCREEN,KWBETWEEN,KW_COMPOSITES,KW_ON_BEGINNING,KW_END,KW_AFTER,KWNOTNULLCHK,KWNOT,LESSTHAN,KW_IF,SEMICOLON,COMPARISON,KWOR,KW_LET,KW_ON_ENDING,GREATERTHAN,KW_BEGIN,KW_PANEL,KWIN,DIVIDE,KW_ELSE,KWNULLCHK,PLUS,LIKE,MINUS,KW_NEXTFIELD,KW_ABORT,KW_CALL,DELIMITERS,KW_BEFORE,COMMENTS,-1};
 
const int token_group_77[]={NAMED,KW_SCREEN,KW_COMPOSITES,KW_ON_BEGINNING,KW_END,KW_AFTER,KW_IF,SEMICOLON,KW_LET,KW_ON_ENDING,KW_BEGIN,KW_PANEL,KW_CALL,KW_NEXTFIELD,KW_ABORT,DELIMITERS,COMMENTS,KW_BEFORE,-1};
 
const int token_group_39[]={DOT,-1};
 
const int token_group_18[]={ATTRIBUTES,-1};
 
const int token_group_70[]={EQUAL,SEMICOLON,COMMA,OPEN_SQUARE,-1};
 
const int token_group_0[]={DATABASE,-1};
 
const int token_group_52[]={NAMED,KW_SCREEN,KW_COMPOSITES,KW_ON_BEGINNING,KW_END,KW_AFTER,LESSTHAN,SEMICOLON,KW_ON_ENDING,KW_PANEL,DELIMITERS,KW_BEFORE,-1};
 
const int token_group_115[]={EQUAL,STAR,KWAND,KWBETWEEN,KWNOTNULLCHK,KWNOT,LESSTHAN,COMPARISON,KWOR,GREATERTHAN,KWIN,DIVIDE,KWNULLCHK,PLUS,LIKE,MINUS,-1};
 
const int token_group_72[]={CLOSE_BRACKET,-1};
 
const int token_group_46[]={KW_CALL,-1};
 
const int token_group_106[]={KWNOT,KW_BEFORE,EQUAL,KW_ON_ENDING,STAR,KW_ELSE,DELIMITERS,KW_THEN,DIVIDE,KW_BEGIN,MINUS,KWOR,SEMICOLON,COMPARISON,PLUS,CLOSE_BRACKET,KW_CALL,KWNULLCHK,KW_IF,KWAND,NAMED,COMMA,KWNOTNULLCHK,KW_ON_BEGINNING,KW_LET,KW_SCREEN,LESSTHAN,KW_AFTER,KW_END,KWBETWEEN,LIKE,KW_COMPOSITES,KW_PANEL,KW_NEXTFIELD,KW_ABORT,GREATERTHAN,COMMENTS,KWIN,-1};
 
const int token_group_103[]={STAR,NAMED,-1};
 
const int token_group_8[]={KW_NULL,-1};
 
const int token_group_111[]={EQUAL,KWNOT,SEMICOLON,COMMA,OPEN_SQUARE,DOT,-1};
 
const int token_group_53[]={KW_EDITADD,KW_EDITUPDATE,KW_REMOVE,KW_OF,-1};
 
const int token_group_71[]={NAMED,FORMONLY,-1};
 
const int token_group_47[]={KW_SCREEN,NAMED,KW_COMPOSITES,KW_ON_BEGINNING,KW_END,KW_AFTER,KW_ON_ENDING,KW_PANEL,DELIMITERS,KW_BEFORE,-1};
 
const int token_group_94[]={EQUAL,STAR,KWAND,KWBETWEEN,KWNOTNULLCHK,KWNOT,LESSTHAN,COMPARISON,KWOR,GREATERTHAN,KWIN,DIVIDE,KW_THEN,KWNULLCHK,PLUS,LIKE,MINUS,-1};
 
const int token_group_107[]={KWIN,LIKE,-1};
 
const int token_group_27[]={KW_USES_EXTENDED,OPEN_BRACE,BY,-1};
 
const int token_group_69[]={EQUAL,SEMICOLON,COMMA,OPEN_SQUARE,DOT,-1};
 
const int token_group_105[]={EQUAL,STAR,KWAND,KWBETWEEN,KWNOTNULLCHK,KWNOT,LESSTHAN,COMPARISON,KWOR,GREATERTHAN,KWIN,DIVIDE,KWNULLCHK,PLUS,LIKE,MINUS,CLOSE_BRACKET,-1};
 
const int token_group_134[]={KWAND,EQUAL,SEMICOLON,KWOR,COMMA,-1};
 
const int token_group_13[]={INPUT,-1};
 
const int token_group_137[]={KWAND,-1};
 
const int token_group_9[]={NAMED,-1};
 
const int token_group_100[]={DAY,EQUAL,MONTH,HOUR,KWNOT,SEMICOLON,SECOND,YEAR,COMMA,FRACTION,MINUTE,OPEN_SQUARE,-1};
 
const int token_group_95[]={KW_END,KW_IF,KW_LET,KW_BEGIN,KW_CALL,KW_NEXTFIELD,KW_ABORT,COMMENTS,-1};
 
const int token_group_60[]={COMMA,-1};
 
const int token_group_119[]={EQUAL,SEMICOLON,COMMA,KW_SIZE,-1};
 
const int token_group_28[]={KW_USES_EXTENDED,OPEN_BRACE,-1};
 
const int token_group_110[]={OPEN_BRACKET,TO,-1};
 
const int token_group_11[]={ATTRIBUTES,TABLES,-1};
 
const int token_group_84[]={EQUAL,SEMICOLON,KWNOT,COMMA,OPEN_SQUARE,-1};
 
const int token_group_67[]={NAMED,KW_TAB,KW_WS,-1};
 
const int token_group_17[]={KW_END,ATTRIBUTES,TABLES,-1};
 
const int token_group_81[]={KW_SCREEN,KW_END,ATTRIBUTES,TABLES,KW_SCREEN_TITLE,-1};
 
const int token_group_49[]={KW_MASTER_OF,-1};
 
const int token_group_32[]={NAMED,CHAR_VALUE,-1};
 
const int token_group_78[]={NAMED,OPEN_BRACKET,NUMBER_VALUE,KWNOT,XVAL,CHAR_VALUE,KW_TOTAL,PLUS,KW_NULL,MINUS,CLOSE_BRACKET,-1};
 
const int token_group_122[]={JOINING,COMMA,-1};
 
const int token_group_73[]={REVERSE,KW_BELL,CHAR_VALUE,-1};
 
const int token_group_44[]={KW_EDITADD,KW_EDITUPDATE,KW_REMOVE,-1};
 
const int token_group_30[]={OPEN_BRACKET,OPEN_BRACE,-1};
 
const int token_group_104[]={NAMED,KW_SCREEN,KW_COMPOSITES,KW_ON_BEGINNING,KW_END,KW_AFTER,SEMICOLON,AS,KW_ON_ENDING,KW_PANEL,DELIMITERS,KW_BEFORE,-1};
 
const int token_group_83[]={KW_BYTE,VARCHAR,KW_DATE,KW_CHAR,SMALLINT,MONEY,KW_FLOAT,KW_TEXT,SMALLFLOAT,KW_DECIMAL,BUTTON,DATETIME,INTERVAL,LIKE,SERIAL,KW_INT,-1};
 
const int token_group_41[]={LESSTHAN,-1};
 
const int token_group_5[]={KW_SCREEN,ATSIGN,CHARACTER_ENCODING,KW_SCREEN_TITLE,WITHOUT,KW_LAYOUT,-1};
 
const int token_group_92[]={KW_OF,-1};
 
const int token_group_124[]={LEFT,MAGENTA,RED,REVERSE,WHITE,UNDERLINE,CYAN,BOLD,NUMBER_VALUE,GREEN,NORMAL,BLINK,BLACK,DIM,YELLOW,BLUE,-1};
 
const int token_group_51[]={KW_ACTION,KW_HIDDEN,COMMA,KW_TEXT,KW_STYLE,KW_BORDER,KW_AUTOSIZE,CLOSE_BRACKET,-1};
 
const int token_group_80[]={NAMED,KW_TAB,PIPE,CLOSE_SQUARE,KW_WS,-1};
 
const int token_group_61[]={NAMED,KW_TAB,KW_NL,PIPE,KW_NONSPACE,KW_WS,CHAR_VALUE,OPEN_SQUARE,CH,CLOSE_BRACE,GRAPH_CH,-1};
 
const int token_group_29[]={KW_END,KW_GROUP,KW_TABLE,KW_GRID,KW_HBOX,KW_VBOX,KW_FOLDER,-1};
 
const int token_group_48[]={NAMED,KW_SCREEN,KW_COMPOSITES,KW_ON_BEGINNING,KW_END,KW_AFTER,SEMICOLON,KW_ON_ENDING,KW_PANEL,DELIMITERS,KW_BEFORE,-1};
 
const int token_group_37[]={KW_END,-1};
 
const int token_group_10[]={KW_GROUP,KW_TABLE,KW_GRID,KW_HBOX,KW_VBOX,KW_FOLDER,-1};
 
const int token_group_123[]={EQUAL,SEMICOLON,COMMA,DOT,-1};
 
const int token_group_65[]={OPEN_BRACKET,OPEN_SQUARE,-1};
 
const int token_group_82[]={NAMED,KW_END,-1};
 
const int token_group_127[]={NUMBER_VALUE,CHAR_VALUE,-1};
 
const int token_group_118[]={DAY,MONTH,HOUR,SECOND,YEAR,FRACTION,MINUTE,-1};
 
const int token_group_7[]={KW_SCREEN,KW_SCREEN_TITLE,KW_LAYOUT,-1};
 
const int token_group_57[]={EQUAL,SEMICOLON,-1};
 
const int token_group_42[]={RECORD,-1};
 
const int token_group_14[]={KW_USES_EXTENDED,OPEN_BRACE,KW_SIZE,-1};
 
const int token_group_120[]={LIKE,-1};
 
const int token_group_74[]={EQUAL,NAMED,KW_EXITNOW,-1};
 
const int token_group_64[]={STAR,LESSTHAN,-1};
 
const int token_group_88[]={NAMED,THROUGH,COMMA,FORMONLY,CLOSE_BRACKET,-1};
 
const int token_group_6[]={CHAR_VALUE,-1};
 
const int token_group_45[]={KW_EDITADD,KW_EDITUPDATE,DISPLAY,KW_REMOVE,KW_UPDATE,KW_QUERY,KW_ADD,-1};
 
const int token_group_12[]={KW_SCREEN,ATTRIBUTES,TABLES,KW_SCREEN_TITLE,-1};
 
const int token_group_128[]={NAMED,JOINING,-1};
 
const int token_group_26[]={INSTRUCTIONS,-1};
 
const int token_group_25[]={KW_EDIT,NAMED,KW_IMAGE,KW_DATEEDIT,KW_BROWSER,KW_CHECKBOX,KW_COMBOBOX,KW_TEXTEDIT,KW_BUTTONEDIT,KW_LABEL,KW_PROGRESSBAR,-1};
 
const int token_group_63[]={EQUAL,KW_EDIT,NAMED,KW_IMAGE,KW_DATEEDIT,KW_CHECKBOX,KW_BROWSER,KW_COMBOBOX,KW_END,INSTRUCTIONS,KW_TEXTEDIT,KW_LABEL,KW_BUTTONEDIT,KW_PROGRESSBAR,-1};
 
const int token_group_93[]={KWNOT,OPEN_BRACKET,KW_BEFORE,EQUAL,KW_ON_ENDING,STAR,KW_ELSE,DELIMITERS,KW_THEN,DIVIDE,KW_BEGIN,MINUS,KWOR,SEMICOLON,COMPARISON,PLUS,CLOSE_BRACKET,KW_CALL,KWNULLCHK,KW_IF,NAMED,KWAND,COMMA,KWNOTNULLCHK,KW_ON_BEGINNING,KW_LET,KW_SCREEN,LESSTHAN,KW_AFTER,KW_END,KWBETWEEN,LIKE,KW_COMPOSITES,KW_PANEL,KW_NEXTFIELD,KW_ABORT,GREATERTHAN,COMMENTS,KWIN,-1};
 
const int token_group_36[]={KW_ACTION,KW_HIDDEN,KW_TEXT,KW_STYLE,KW_BORDER,KW_AUTOSIZE,-1};
 
const int token_group_132[]={NAMED,OPEN_BRACKET,NUMBER_VALUE,KWNOT,XVAL,CHAR_VALUE,-1};
 
const int token_group_101[]={CLOSE_SQUARE,COMMA,-1};
 
const int token_group_20[]={KW_END,OPEN_BRACKET,KW_GROUP,KW_TABLE,KW_GRID,KW_HBOX,KW_VBOX,KW_FOLDER,-1};
 
const int token_group_130[]={NAMED,NUMBER_VALUE,CHAR_VALUE,CH,PLUS,KW_NULL,MINUS,-1};
 
const int token_group_89[]={TO,-1};
 
const int token_group_62[]={STAR,NAMED,DISPLAYONLY,FORMONLY,-1};
 
const int token_group_99[]={EQUAL,OPEN_BRACKET,KWNOT,SEMICOLON,COMMA,OPEN_SQUARE,-1};
 
const int token_group_38[]={KW_END,KW_PAGE,-1};
 
const int token_group_1[]={NAMED,SPECIAL_DBNAME,FORMONLY,-1};
 
const int token_group_31[]={KW_PAGE,-1};
 
const int token_group_96[]={COMMA,CLOSE_BRACKET,-1};
 
const int token_group_54[]={KW_EDITADD,KW_EDITUPDATE,DISPLAY,KW_REMOVE,KW_UPDATE,KW_OF,KW_QUERY,KW_ADD,-1};
 
const int token_group_34[]={KW_SCREEN,NAMED,KW_COMPOSITES,KW_ON_BEGINNING,KW_AFTER,KW_ON_ENDING,KW_PANEL,DELIMITERS,KW_BEFORE,-1};
 
const int token_group_4[]={KW_SCREEN,CHARACTER_ENCODING,KW_SCREEN_TITLE,WITHOUT,KW_LAYOUT,-1};
 
const int token_group_79[]={PIPE,CLOSE_SQUARE,-1};
 
const int token_group_75[]={NAMED,OPEN_BRACKET,NUMBER_VALUE,KWNOT,XVAL,CHAR_VALUE,KW_TOTAL,PLUS,KW_NULL,MINUS,-1};
 
#include "mk_fstates_1.h"
/* andrej moved here from top: */
static int FORMPARSE_allow_token_state(int yystate,int yytoken) {
int a;
int c;
const int *token_group;
  if (yytoken<0) return 1;
  token_group=token_groups[yystate];
  a=0;
  c=token_group[a];
  while (c>=0) {
    if (c==yytoken) return 1;
    c=token_group[++a];
  }
  return 0;
}
