
DATABASE test1

MAIN
	WHENEVER ERROR CONTINUE
	DROP TABLE xpto
	WHENEVER ERROR STOP
	CREATE TABLE xpto (
	  firstColumn SMALLINT,
		secondColumn CHAR(10)
	)

  GRANT ALL ON xpto TO PUBLIC WITH GRANT OPTION
  GRANT ALL ON xpto TO informix WITH GRANT OPTION
  GRANT ALL PRIVILEGES ON xpto TO informix, root WITH GRANT OPTION
	DROP TABLE xpto
END MAIN
