
r1.4ae: r1.4gl
	$(FGLC) r1.4gl -o r1.4ae

compile: r1.4ae
	
run: r1.4ae
	sh ./run_r1

ansi_sql_compat:
	@echo "1"


sql_features_used:		; @echo "DATABASE_USED DEFINE_CHAR DEFINE_INTEGER CREATE_TEMP_TABLE ANSI_INSERT CURSOR_SELECT FOREACH UI_DISPLAY_LINE_MODE DISPLAY "

