

m1.4ae: m1.4gl
	$(FGLC) m1.4gl -o m1.4ae

compile: m1.4ae
	
run: m1.4ae
	sh ./run_m1

ansi_sql_compat:
	@echo "1"


sql_features_used:		; @echo "DATABASE_USED CREATE_TEMP_TABLE CURSOR_SELECT FOREACH UI_DISPLAY_LINE_MODE DISPLAY EXIT_PROGRAM_EXPR CLOSE_CURSOR DROP_TABLE "

