
rep.4ae: rep.4gl
	$(FGLC) rep.4gl -o rep.4ae

compile: rep.4ae
	
run: rep.4ae
	sh ./run_rep
db_test:
	@echo "1"

ansi_sql_compat:
	@echo "1"

desc:
	@echo "Simple foreach handling"
	
sql_features_used:
	@echo "CURSOR_SELECT IFX_SYSTABLES   DEFINE_CHAR DEFINE_INTEGER USE_REPORT FOREACH UI_DISPLAY_LINE_MODE DISPLAY IF EXIT_PROGRAM_EXPR REPORT_ORDER_BY REPORT_FIRST_PAGE_HEADER ON_EVERY_ROW"
	
