.-1000
 (ER_HASHCHK)
 hashchk
.-1001
 (ER_NISAMCHK)
 isamchk
.-1002
 (ER_NO)
 NO
.-1003
 (ER_YES)
 YES
.-1004
 (ER_CANT_CREATE_FILE)
 Can't create file '%s' (errno: #)
.-1005
 (ER_CANT_CREATE_TABLE)
 Can't create table '%s' (errno: #)
.-1006
 (ER_CANT_CREATE_DB)
 Can't create database '%s' (errno: #)
.-1007
 (ER_DB_CREATE_EXISTS)
 Can't create database '%s'; database exists
.-1008
 (ER_DB_DROP_EXISTS)
 Can't drop database '%s'; database doesn't exist
.-1009
 (ER_DB_DROP_DELETE)
 Error dropping database (can't delete '%s', errno: #)
.-1010
 (ER_DB_DROP_RMDIR)
 Error dropping database (can't rmdir '%s', errno: #)
.-1011
 (ER_CANT_DELETE_FILE)
 Error on delete of '%s' (errno: #)
.-1012
 (ER_CANT_FIND_SYSTEM_REC)
 Can't read record in system table
.-1013
 (ER_CANT_GET_STAT)
 Can't get status of '%s' (errno: #)
.-1014
 (ER_CANT_GET_WD)
 Can't get working directory (errno: #)
.-1015
 (ER_CANT_LOCK)
 Can't lock file (errno: #)
.-1016
 (ER_CANT_OPEN_FILE)
 Can't open file: '%s' (errno: #)
.-1017
 (ER_FILE_NOT_FOUND)
 Can't find file: '%s' (errno: #)
.-1018
 (ER_CANT_READ_DIR)
 Can't read dir of '%s' (errno: #)
.-1019
 (ER_CANT_SET_WD)
 Can't change dir to '%s' (errno: #)
.-1020
 (ER_CHECKREAD)
 Record has changed since last read in table '%s'
.-1021
 (ER_DISK_FULL)
 Disk full (%s); waiting for someone to free some space...
.-1022
 (ER_DUP_KEY)
 Can't write; duplicate key in table '%s'
.-1023
 (ER_ERROR_ON_CLOSE)
 Error on close of '%s' (errno: #)
.-1024
 (ER_ERROR_ON_READ)
 Error reading file '%s' (errno: #)
.-1025
 (ER_ERROR_ON_RENAME)
 Error on rename of '%s' to '%s' (errno: #)
.-1026
 (ER_ERROR_ON_WRITE)
 Error writing file '%s' (errno: #)
.-1027
 (ER_FILE_USED)
 '%s' is locked against change
.-1028
 (ER_FILSORT_ABORT)
 Sort aborted
.-1029
 (ER_FORM_NOT_FOUND)
 View '%s' doesn't exist for '%s'
.-1030
 (ER_GET_ERRNO)
 Got error # from storage engine
.-1031
 (ER_ILLEGAL_HA)
 Table storage engine for '%s' doesn't have this option
.-1032
 (ER_KEY_NOT_FOUND)
 Can't find record in '%s'
.-1033
 (ER_NOT_FORM_FILE)
 Incorrect information in file: '%s'
.-1034
 (ER_NOT_KEYFILE)
 Incorrect key file for table '%s'; try to repair it
.-1035
 (ER_OLD_KEYFILE)
 Old key file for table '%s'; repair it!
.-1036
 (ER_OPEN_AS_READONLY)
 Table '%s' is read only
.-1037
 (ER_OUTOFMEMORY)
 Out of memory; restart server and try again (needed # bytes)
.-1038
 (ER_OUT_OF_SORTMEMORY)
 Out of sort memory; increase server sort buffer size
.-1039
 (ER_UNEXPECTED_EOF)
 Unexpected EOF found when reading file '%s' (errno: #)
.-1040
 (ER_CON_COUNT_ERROR)
 Too many connections
.-1041
 (ER_OUT_OF_RESOURCES)
 Out of memory; check if mysqld or some other process uses all available memory; if not, you may have to use 'ulimit' to allow mysqld to use more memory or you can add more swap space
.-1042
 (ER_BAD_HOST_ERROR)
 Can't get hostname for your address
.-1043
 (ER_HANDSHAKE_ERROR)
 Bad handshake
.-1044
 (ER_DBACCESS_DENIED_ERROR)
 Access denied for user '%s'@'%s' to database '%s'
.-1045
 (ER_ACCESS_DENIED_ERROR)
 Access denied for user '%s'@'%s' (using password: %s)
.-1046
 (ER_NO_DB_ERROR)
 No database selected
.-1047
 (ER_UNKNOWN_COM_ERROR)
 Unknown command
.-1048
 (ER_BAD_NULL_ERROR)
 Column '%s' cannot be null
.-1049
 (ER_BAD_DB_ERROR)
 Unknown database '%s'
.-1050
 (ER_TABLE_EXISTS_ERROR)
 Table '%s' already exists
.-1051
 (ER_BAD_TABLE_ERROR)
 Unknown table '%s'
.-1052
 (ER_NON_UNIQ_ERROR)
 Column '%s' in %s is ambiguous
.-1053
 (ER_SERVER_SHUTDOWN)
 Server shutdown in progress
.-1054
 (ER_BAD_FIELD_ERROR)
 Unknown column '%s' in '%s'
.-1055
 (ER_WRONG_FIELD_WITH_GROUP)
 '%s' isn't in GROUP BY
.-1056
 (ER_WRONG_GROUP_FIELD)
 Can't group on '%s'
.-1057
 (ER_WRONG_SUM_SELECT)
 Statement has sum functions and columns in same statement
.-1058
 (ER_WRONG_VALUE_COUNT)
 Column count doesn't match value count
.-1059
 (ER_TOO_LONG_IDENT)
 Identifier name '%s' is too long
.-1060
 (ER_DUP_FIELDNAME)
 Duplicate column name '%s'
.-1061
 (ER_DUP_KEYNAME)
 Duplicate key name '%s'
.-1062
 (ER_DUP_ENTRY)
 Duplicate entry '%s' for key #
.-1063
 (ER_WRONG_FIELD_SPEC)
 Incorrect column specifier for column '%s'
.-1064
 (ER_PARSE_ERROR)
 %s near '%s' at line #
.-1065
 (ER_EMPTY_QUERY)
 Query was empty
.-1066
 (ER_NONUNIQ_TABLE)
 Not unique table/alias: '%s'
.-1067
 (ER_INVALID_DEFAULT)
 Invalid default value for '%s'
.-1068
 (ER_MULTIPLE_PRI_KEY)
 Multiple primary key defined
.-1069
 (ER_TOO_MANY_KEYS)
 Too many keys specified; max # keys allowed
.-1070
 (ER_TOO_MANY_KEY_PARTS)
 Too many key parts specified; max # parts allowed
.-1071
 (ER_TOO_LONG_KEY)
 Specified key was too long; max key length is # bytes
.-1072
 (ER_KEY_COLUMN_DOES_NOT_EXITS)
 Key column '%s' doesn't exist in table
.-1073
 (ER_BLOB_USED_AS_KEY)
 BLOB column '%s' can't be used in key specification with the used table type
.-1074
 (ER_TOO_BIG_FIELDLENGTH)
 Column length too big for column '%s' (max = %lu); use BLOB or TEXT instead
.-1075
 (ER_WRONG_AUTO_KEY)
 Incorrect table definition; there can be only one auto column and it must be defined as a key
.-1076
 (ER_READY)
 %s: ready for connections. Version: '%s' socket: '%s' port: #
.-1077
 (ER_NORMAL_SHUTDOWN)
 %s: Normal shutdown
.-1078
 (ER_GOT_SIGNAL)
 %s: Got signal #. Aborting!
.-1079
 (ER_SHUTDOWN_COMPLETE)
 %s: Shutdown complete
.-1080
 (ER_FORCING_CLOSE)
 %s: Forcing close of thread %ld user: '%s'
.-1081
 (ER_IPSOCK_ERROR)
 Can't create IP socket
.-1082
 (ER_NO_SUCH_INDEX)
 Table '%s' has no index like the one used in CREATE INDEX; recreate the table
.-1083
 (ER_WRONG_FIELD_TERMINATORS)
 Field separator argument is not what is expected; check the manual
.-1084
 (ER_BLOBS_AND_NO_TERMINATED)
 You can't use fixed rowlength with BLOBs; please use 'fields terminated by'
.-1085
 (ER_TEXTFILE_NOT_READABLE)
 The file '%s' must be in the database directory or be readable by all
.-1086
 (ER_FILE_EXISTS_ERROR)
 File '%s' already exists
.-1087
 (ER_LOAD_INFO)
 Records: %ld Deleted: %ld Skipped: %ld Warnings: %ld
.-1088
 (ER_ALTER_INFO)
 Records: %ld Duplicates: %ld
.-1089
 (ER_WRONG_SUB_KEY)
 Incorrect sub part key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique sub keys
.-1090
 (ER_CANT_REMOVE_ALL_FIELDS)
 You can't delete all columns with ALTER TABLE; use DROP TABLE instead
.-1091
 (ER_CANT_DROP_FIELD_OR_KEY)
 Can't DROP '%s'; check that column/key exists
.-1092
 (ER_INSERT_INFO)
 Records: %ld Duplicates: %ld Warnings: %ld
.-1093
 (ER_UPDATE_TABLE_USED)
 You can't specify target table '%s' for update in FROM clause
.-1094
 (ER_NO_SUCH_THREAD)
 Unknown thread id: %lu
.-1095
 (ER_KILL_DENIED_ERROR)
 You are not owner of thread %lu
.-1096
 (ER_NO_TABLES_USED)
 No tables used
.-1097
 (ER_TOO_BIG_SET)
 Too many strings for column %s and SET
.-1098
 (ER_NO_UNIQUE_LOGFILE)
 Can't generate a unique log-filename %s.(1-999)
.-1099
 (ER_TABLE_NOT_LOCKED_FOR_WRITE)
 Table '%s' was locked with a READ lock and can't be updated
.-1100
 (ER_TABLE_NOT_LOCKED)
 Table '%s' was not locked with LOCK TABLES
.-1101
 (ER_BLOB_CANT_HAVE_DEFAULT)
 BLOB/TEXT column '%s' can't have a default value
.-1102
 (ER_WRONG_DB_NAME)
 Incorrect database name '%s'
.-1103
 (ER_WRONG_TABLE_NAME)
 Incorrect table name '%s'
.-1104
 (ER_TOO_BIG_SELECT)
 The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET SQL_MAX_JOIN_SIZE=# if the SELECT is okay
.-1105
 (ER_UNKNOWN_ERROR)
 Unknown error
.-1106
 (ER_UNKNOWN_PROCEDURE)
 Unknown procedure '%s'
.-1107
 (ER_WRONG_PARAMCOUNT_TO_PROCEDURE)
 Incorrect parameter count to procedure '%s'
.-1108
 (ER_WRONG_PARAMETERS_TO_PROCEDURE)
 Incorrect parameters to procedure '%s'
.-1109
 (ER_UNKNOWN_TABLE)
 Unknown table '%s' in %s
.-1110
 (ER_FIELD_SPECIFIED_TWICE)
 Column '%s' specified twice
.-1111
 (ER_INVALID_GROUP_FUNC_USE)
 Invalid use of group function
.-1112
 (ER_UNSUPPORTED_EXTENSION)
 Table '%s' uses an extension that doesn't exist in this MySQL version
.-1113
 (ER_TABLE_MUST_HAVE_COLUMNS)
 A table must have at least 1 column
.-1114
 (ER_RECORD_FILE_FULL)
 The table '%s' is full
.-1115
 (ER_UNKNOWN_CHARACTER_SET)
 Unknown character set: '%s'
.-1116
 (ER_TOO_MANY_TABLES)
 Too many tables; MySQL can only use # tables in a join
.-1117
 (ER_TOO_MANY_FIELDS)
 Too many columns
.-1118
 (ER_TOO_BIG_ROWSIZE)
 Row size too large. The maximum row size for the used table type, not counting BLOBs, is %ld. You have to change some columns to TEXT or BLOBs
.-1119
 (ER_STACK_OVERRUN)
 Thread stack overrun: Used: %ld of a %ld stack. Use 'mysqld -O thread_stack=#' to specify a bigger stack if needed
.-1120
 (ER_WRONG_OUTER_JOIN)
 Cross dependency found in OUTER JOIN; examine your ON conditions
.-1121
 (ER_NULL_COLUMN_IN_INDEX)
 Column '%s' is used with UNIQUE or INDEX but is not defined as NOT NULL
.-1122
 (ER_CANT_FIND_UDF)
 Can't load function '%s'
.-1123
 (ER_CANT_INITIALIZE_UDF)
 Can't initialize function '%s'; %s
.-1124
 (ER_UDF_NO_PATHS)
 No paths allowed for shared library
.-1125
 (ER_UDF_EXISTS)
 Function '%s' already exists
.-1126
 (ER_CANT_OPEN_LIBRARY)
 Can't open shared library '%s' (errno: # %s)
.-1127
 (ER_CANT_FIND_DL_ENTRY)
 Can't find function '%s' in library
.-1128
 (ER_FUNCTION_NOT_DEFINED)
 Function '%s' is not defined
.-1129
 (ER_HOST_IS_BLOCKED)
 Host '%s' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'
.-1130
 (ER_HOST_NOT_PRIVILEGED)
 Host '%s' is not allowed to connect to this MySQL server
.-1131
 (ER_PASSWORD_ANONYMOUS_USER)
 You are using MySQL as an anonymous user and anonymous users are not allowed to change passwords
.-1132
 (ER_PASSWORD_NOT_ALLOWED)
 You must have privileges to update tables in the mysql database to be able to change passwords for others
.-1133
 (ER_PASSWORD_NO_MATCH)
 Can't find any matching row in the user table
.-1134
 (ER_UPDATE_INFO)
 Rows matched: %ld Changed: %ld Warnings: %ld
.-1135
 (ER_CANT_CREATE_THREAD)
 Can't create a new thread (errno #); if you are not out of available memory, you can consult the manual for a possible OS-dependent bug
.-1136
 (ER_WRONG_VALUE_COUNT_ON_ROW)
 Column count doesn't match value count at row %ld
.-1137
 (ER_CANT_REOPEN_TABLE)
 Can't reopen table: '%s'
.-1138
 (ER_INVALID_USE_OF_NULL)
 Invalid use of NULL value
.-1139
 (ER_REGEXP_ERROR)
 Got error '%s' from regexp
.-1140
 (ER_MIX_OF_GROUP_FUNC_AND_FIELDS)
 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause
.-1141
 (ER_NONEXISTING_GRANT)
 There is no such grant defined for user '%s' on host '%s'
.-1142
 (ER_TABLEACCESS_DENIED_ERROR)
 %s command denied to user '%s'@'%s' for table '%s'
.-1143
 (ER_COLUMNACCESS_DENIED_ERROR)
 %s command denied to user '%s'@'%s' for column '%s' in table '%s'
.-1144
 (ER_ILLEGAL_GRANT_FOR_TABLE)
 Illegal GRANT/REVOKE command; please consult the manual to see which privileges can be used
.-1145
 (ER_GRANT_WRONG_HOST_OR_USER)
 The host or user argument to GRANT is too long
.-1146
 (ER_NO_SUCH_TABLE)
 Table '%s.%s' doesn't exist
.-1147
 (ER_NONEXISTING_TABLE_GRANT)
 There is no such grant defined for user '%s' on host '%s' on table '%s'
.-1148
 (ER_NOT_ALLOWED_COMMAND)
 The used command is not allowed with this MySQL version
.-1149
 (ER_SYNTAX_ERROR)
 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use
.-1150
 (ER_DELAYED_CANT_CHANGE_LOCK)
 Delayed insert thread couldn't get requested lock for table %s
.-1151
 (ER_TOO_MANY_DELAYED_THREADS)
 Too many delayed threads in use
.-1152
 (ER_ABORTING_CONNECTION)
 Aborted connection %ld to db: '%s' user: '%s' (%s)
.-1153
 (ER_NET_PACKET_TOO_LARGE)
 Got a packet bigger than 'max_allowed_packet' bytes
.-1154
 (ER_NET_READ_ERROR_FROM_PIPE)
 Got a read error from the connection pipe
.-1155
 (ER_NET_FCNTL_ERROR)
 Got an error from fcntl()
.-1156
 (ER_NET_PACKETS_OUT_OF_ORDER)
 Got packets out of order
.-1157
 (ER_NET_UNCOMPRESS_ERROR)
 Couldn't uncompress communication packet
.-1158
 (ER_NET_READ_ERROR)
 Got an error reading communication packets
.-1159
 (ER_NET_READ_INTERRUPTED)
 Got timeout reading communication packets
.-1160
 (ER_NET_ERROR_ON_WRITE)
 Got an error writing communication packets
.-1161
 (ER_NET_WRITE_INTERRUPTED)
 Got timeout writing communication packets
.-1162
 (ER_TOO_LONG_STRING)
 Result string is longer than 'max_allowed_packet' bytes
.-1163
 (ER_TABLE_CANT_HANDLE_BLOB)
 The used table type doesn't support BLOB/TEXT columns
.-1164
 (ER_TABLE_CANT_HANDLE_AUTO_INCREMENT)
 The used table type doesn't support AUTO_INCREMENT columns
.-1165
 (ER_DELAYED_INSERT_TABLE_LOCKED)
 INSERT DELAYED can't be used with table '%s' because it is locked with LOCK TABLES
.-1166
 (ER_WRONG_COLUMN_NAME)
 Incorrect column name '%s'
.-1167
 (ER_WRONG_KEY_COLUMN)
 The used storage engine can't index column '%s'
.-1168
 (ER_WRONG_MRG_TABLE)
 Unable to open underlying table which is differently defined or of non-MyISAM type or doesn't exist
.-1169
 (ER_DUP_UNIQUE)
 Can't write, because of unique constraint, to table '%s'
.-1170
 (ER_BLOB_KEY_WITHOUT_LENGTH)
 BLOB/TEXT column '%s' used in key specification without a key length
.-1171
 (ER_PRIMARY_CANT_HAVE_NULL)
 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
.-1172
 (ER_TOO_MANY_ROWS)
 Result consisted of more than one row
.-1173
 (ER_REQUIRES_PRIMARY_KEY)
 This table type requires a primary key
.-1174
 (ER_NO_RAID_COMPILED)
 This version of MySQL is not compiled with RAID support
.-1175
 (ER_UPDATE_WITHOUT_KEY_IN_SAFE_MODE)
 You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column
.-1176
 (ER_KEY_DOES_NOT_EXITS)
 Key '%s' doesn't exist in table '%s'
.-1177
 (ER_CHECK_NO_SUCH_TABLE)
 Can't open table
.-1178
 (ER_CHECK_NOT_IMPLEMENTED)
 The storage engine for the table doesn't support %s
.-1179
 (ER_CANT_DO_THIS_DURING_AN_TRANSACTION)
 You are not allowed to execute this command in a transaction
.-1180
 (ER_ERROR_DURING_COMMIT)
 Got error # during COMMIT
.-1181
 (ER_ERROR_DURING_ROLLBACK)
 Got error # during ROLLBACK
.-1182
 (ER_ERROR_DURING_FLUSH_LOGS)
 Got error # during FLUSH_LOGS
.-1183
 (ER_ERROR_DURING_CHECKPOINT)
 Got error # during CHECKPOINT
.-1184
 (ER_NEW_ABORTING_CONNECTION)
 Aborted connection %ld to db: '%s' user: '%s' host: '%s' (%s)
.-1185
 (ER_DUMP_NOT_IMPLEMENTED)
 The storage engine for the table does not support binary table dump
.-1186
 (ER_FLUSH_MASTER_BINLOG_CLOSED)
 Binlog closed, cannot RESET MASTER
.-1187
 (ER_INDEX_REBUILD)
 Failed rebuilding the index of dumped table '%s'
.-1188
 (ER_MASTER)
 Error from master: '%s'
.-1189
 (ER_MASTER_NET_READ)
 Net error reading from master
.-1190
 (ER_MASTER_NET_WRITE)
 Net error writing to master
.-1191
 (ER_FT_MATCHING_KEY_NOT_FOUND)
 Can't find FULLTEXT index matching the column list
.-1192
 (ER_LOCK_OR_ACTIVE_TRANSACTION)
 Can't execute the given command because you have active locked tables or an active transaction
.-1193
 (ER_UNKNOWN_SYSTEM_VARIABLE)
 Unknown system variable '%s'
.-1194
 (ER_CRASHED_ON_USAGE)
 Table '%s' is marked as crashed and should be repaired
.-1195
 (ER_CRASHED_ON_REPAIR)
 Table '%s' is marked as crashed and last (automatic?) repair failed
.-1196
 (ER_WARNING_NOT_COMPLETE_ROLLBACK)
 Some non-transactional changed tables couldn't be rolled back
.-1197
 (ER_TRANS_CACHE_FULL)
 Multi-statement transaction required more than 'max_binlog_cache_size' bytes of storage; increase this mysqld variable and try again
.-1198
 (ER_SLAVE_MUST_STOP)
 This operation cannot be performed with a running slave; run STOP SLAVE first
.-1199
 (ER_SLAVE_NOT_RUNNING)
 This operation requires a running slave; configure slave and do START SLAVE
.-1200
 (ER_BAD_SLAVE)
 The server is not configured as slave; fix in config file or with CHANGE MASTER TO
.-1201
 (ER_MASTER_INFO)
 Could not initialize master info structure; more error messages can be found in the MySQL error log
.-1202
 (ER_SLAVE_THREAD)
 Could not create slave thread; check system resources
.-1203
 (ER_TOO_MANY_USER_CONNECTIONS)
 User %s already has more than 'max_user_connections' active connections
.-1204
 (ER_SET_CONSTANTS_ONLY)
 You may only use constant expressions with SET
.-1205
 (ER_LOCK_WAIT_TIMEOUT)
 Lock wait timeout exceeded; try restarting transaction
.-1206
 (ER_LOCK_TABLE_FULL)
 The total number of locks exceeds the lock table size
.-1207
 (ER_READ_ONLY_TRANSACTION)
 Update locks cannot be acquired during a READ UNCOMMITTED transaction
.-1208
 (ER_DROP_DB_WITH_READ_LOCK)
 DROP DATABASE not allowed while thread is holding global read lock
.-1209
 (ER_CREATE_DB_WITH_READ_LOCK)
 CREATE DATABASE not allowed while thread is holding global read lock
.-1210
 (ER_WRONG_ARGUMENTS)
 Incorrect arguments to %s
.-1211
 (ER_NO_PERMISSION_TO_CREATE_USER)
 '%s'@'%s' is not allowed to create new users
.-1212
 (ER_UNION_TABLES_IN_DIFFERENT_DIR)
 Incorrect table definition; all MERGE tables must be in the same database
.-1213
 (ER_LOCK_DEADLOCK)
 Deadlock found when trying to get lock; try restarting transaction
.-1214
 (ER_TABLE_CANT_HANDLE_FT)
 The used table type doesn't support FULLTEXT indexes
.-1215
 (ER_CANNOT_ADD_FOREIGN)
 Cannot add foreign key constraint
.-1216
 (ER_NO_REFERENCED_ROW)
 Cannot add or update a child row: a foreign key constraint fails
.-1217
 (ER_ROW_IS_REFERENCED)
 Cannot delete or update a parent row: a foreign key constraint fails
.-1218
 (ER_CONNECT_TO_MASTER)
 Error connecting to master: %s
.-1219
 (ER_QUERY_ON_MASTER)
 Error running query on master: %s
.-1220
 (ER_ERROR_WHEN_EXECUTING_COMMAND)
 Error when executing command %s: %s
.-1221
 (ER_WRONG_USAGE)
 Incorrect usage of %s and %s
.-1222
 (ER_WRONG_NUMBER_OF_COLUMNS_IN_SELECT)
 The used SELECT statements have a different number of columns
.-1223
 (ER_CANT_UPDATE_WITH_READLOCK)
 Can't execute the query because you have a conflicting read lock
.-1224
 (ER_MIXING_NOT_ALLOWED)
 Mixing of transactional and non-transactional tables is disabled
.-1225
 (ER_DUP_ARGUMENT)
 Option '%s' used twice in statement
.-1226
 (ER_USER_LIMIT_REACHED)
 User '%s' has exceeded the '%s' resource (current value: %ld)
.-1227
 (ER_SPECIFIC_ACCESS_DENIED_ERROR)
 Access denied; you need the %s privilege for this operation
.-1228
 (ER_LOCAL_VARIABLE)
 Variable '%s' is a SESSION variable and can't be used with SET GLOBAL
.-1229
 (ER_GLOBAL_VARIABLE)
 Variable '%s' is a GLOBAL variable and should be set with SET GLOBAL
.-1230
 (ER_NO_DEFAULT)
 Variable '%s' doesn't have a default value
.-1231
 (ER_WRONG_VALUE_FOR_VAR)
 Variable '%s' can't be set to the value of '%s'
.-1232
 (ER_WRONG_TYPE_FOR_VAR)
 Incorrect argument type to variable '%s'
.-1233
 (ER_VAR_CANT_BE_READ)
 Variable '%s' can only be set, not read
.-1234
 (ER_CANT_USE_OPTION_HERE)
 Incorrect usage/placement of '%s'
.-1235
 (ER_NOT_SUPPORTED_YET)
 This version of MySQL doesn't yet support '%s'
.-1236
 (ER_MASTER_FATAL_ERROR_READING_BINLOG)
 Got fatal error #: '%s' from master when reading data from binary log
.-1237
 (ER_SLAVE_IGNORED_TABLE)
 Slave SQL thread ignored the query because of replicate-*-table rules
.-1238
 (ER_INCORRECT_GLOBAL_LOCAL_VAR)
 Variable '%s' is a %s variable
.-1239
 (ER_WRONG_FK_DEF)
 Incorrect foreign key definition for '%s': %s
.-1240
 (ER_KEY_REF_DO_NOT_MATCH_TABLE_REF)
 Key reference and table reference don't match
.-1241
 (ER_OPERAND_COLUMNS)
 Operand should contain # column(s)
.-1242
 (ER_SUBQUERY_NO_1_ROW)
 Subquery returns more than 1 row
.-1243
 (ER_UNKNOWN_STMT_HANDLER)
 Unknown prepared statement handler (%.*s) given to %s
.-1244
 (ER_CORRUPT_HELP_DB)
 Help database is corrupt or does not exist
.-1245
 (ER_CYCLIC_REFERENCE)
 Cyclic reference on subqueries
.-1246
 (ER_AUTO_CONVERT)
 Converting column '%s' from %s to %s
.-1247
 (ER_ILLEGAL_REFERENCE)
 Reference '%s' not supported (%s)
.-1248
 (ER_DERIVED_MUST_HAVE_ALIAS)
 Every derived table must have its own alias
.-1249
 (ER_SELECT_REDUCED)
 Select %u was reduced during optimization
.-1250
 (ER_TABLENAME_NOT_ALLOWED_HERE)
 Table '%s' from one of the SELECTs cannot be used in %s
.-1251
 (ER_NOT_SUPPORTED_AUTH_MODE)
 Client does not support authentication protocol requested by server; consider upgrading MySQL client
.-1252
 (ER_SPATIAL_CANT_HAVE_NULL)
 All parts of a SPATIAL index must be NOT NULL
.-1253
 (ER_COLLATION_CHARSET_MISMATCH)
 COLLATION '%s' is not valid for CHARACTER SET '%s'
.-1254
 (ER_SLAVE_WAS_RUNNING)
 Slave is already running
.-1255
 (ER_SLAVE_WAS_NOT_RUNNING)
 Slave already has been stopped
.-1256
 (ER_TOO_BIG_FOR_UNCOMPRESS)
 Uncompressed data size too large; the maximum size is # (probably, length of uncompressed data was corrupted)
.-1257
 (ER_ZLIB_Z_MEM_ERROR)
 ZLIB: Not enough memory
.-1258
 (ER_ZLIB_Z_BUF_ERROR)
 ZLIB: Not enough room in the output buffer (probably, length of uncompressed data was corrupted)
.-1259
 (ER_ZLIB_Z_DATA_ERROR)
 ZLIB: Input data corrupted
.-1260
 (ER_CUT_VALUE_GROUP_CONCAT)
 # line(s) were cut by GROUP_CONCAT()
.-1261
 (ER_WARN_TOO_FEW_RECORDS)
 Row %ld doesn't contain data for all columns
.-1262
 (ER_WARN_TOO_MANY_RECORDS)
 Row %ld was truncated; it contained more data than there were input columns
.-1263
 (ER_WARN_NULL_TO_NOTNULL)
 Column was set to data type implicit default; NULL supplied for NOT NULL column '%s' at row %ld
.-1264
 (ER_WARN_DATA_OUT_OF_RANGE)
 Out of range value adjusted for column '%s' at row %ld
.-1265
 (WARN_DATA_TRUNCATED)
 Data truncated for column '%s' at row %ld
.-1266
 (ER_WARN_USING_OTHER_HANDLER)
 Using storage engine %s for table '%s'
.-1267
 (ER_CANT_AGGREGATE_2COLLATIONS)
 Illegal mix of collations (%s,%s) and (%s,%s) for operation '%s'
.-1268
 (ER_DROP_USER)
 Cannot drop one or more of the requested users
.-1269
 (ER_REVOKE_GRANTS)
 Can't revoke all privileges for one or more of the requested users
.-1270
 (ER_CANT_AGGREGATE_3COLLATIONS)
 Illegal mix of collations (%s,%s), (%s,%s), (%s,%s) for operation '%s'
.-1271
 (ER_CANT_AGGREGATE_NCOLLATIONS)
 Illegal mix of collations for operation '%s'
.-1272
 (ER_VARIABLE_IS_NOT_STRUCT)
 Variable '%s' is not a variable component (can't be used as XXXX.variable_name)
.-1273
 (ER_UNKNOWN_COLLATION)
 Unknown collation: '%s'
.-1274
 (ER_SLAVE_IGNORED_SSL_PARAMS)
 SSL parameters in CHANGE MASTER are ignored because this MySQL slave was compiled without SSL support; they can be used later if MySQL slave with SSL is started
.-1275
 (ER_SERVER_IS_IN_SECURE_AUTH_MODE)
 Server is running in --secure-auth mode, but '%s'@'%s' has a password in the old format; please change the password to the new format
.-1276
 (ER_WARN_FIELD_RESOLVED)
 Field or reference '%s%s%s%s%s' of SELECT ## was resolved in SELECT ##
.-1277
 (ER_BAD_SLAVE_UNTIL_COND)
 Incorrect parameter or combination of parameters for START SLAVE UNTIL
.-1278
 (ER_MISSING_SKIP_SLAVE)
 It is recommended to use --skip-slave-start when doing step-by-step replication with START SLAVE UNTIL; otherwise, you will get problems if you get an unexpected slave's mysqld restart
.-1279
 (ER_UNTIL_COND_IGNORED)
 SQL thread is not to be started so UNTIL options are ignored
.-1280
 (ER_WRONG_NAME_FOR_INDEX)
 Incorrect index name '%s'
.-1281
 (ER_WRONG_NAME_FOR_CATALOG)
 Incorrect catalog name '%s'
.-1282
 (ER_WARN_QC_RESIZE)
 Query cache failed to set size %lu; new query cache size is %lu
.-1283
 (ER_BAD_FT_COLUMN)
 Column '%s' cannot be part of FULLTEXT index
.-1284
 (ER_UNKNOWN_KEY_CACHE)
 Unknown key cache '%s'
.-1285
 (ER_WARN_HOSTNAME_WONT_WORK)
 MySQL is started in --skip-name-resolve mode; you must restart it without this switch for this grant to work
.-1286
 (ER_UNKNOWN_STORAGE_ENGINE)
 Unknown table engine '%s'
.-1287
 (ER_WARN_DEPRECATED_SYNTAX)
 '%s' is deprecated; use '%s' instead
.-1288
 (ER_NON_UPDATABLE_TABLE)
 The target table %s of the %s is not updatable
.-1289
 (ER_FEATURE_DISABLED)
 The '%s' feature is disabled; you need MySQL built with '%s' to have it working
.-1290
 (ER_OPTION_PREVENTS_STATEMENT)
 The MySQL server is running with the %s option so it cannot execute this statement
.-1291
 (ER_DUPLICATED_VALUE_IN_TYPE)
 Column '%s' has duplicated value '%s' in %s
.-1292
 (ER_TRUNCATED_WRONG_VALUE)
 Truncated incorrect %s value: '%s'
.-1293
 (ER_TOO_MUCH_AUTO_TIMESTAMP_COLS)
 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
.-1294
 (ER_INVALID_ON_UPDATE)
 Invalid ON UPDATE clause for '%s' column
.-1295
 (ER_UNSUPPORTED_PS)
 This command is not supported in the prepared statement protocol yet
.-1296
 (ER_GET_ERRMSG)
 Got error # '%s' from %s
.-1297
 (ER_GET_TEMPORARY_ERRMSG)
 Got temporary error # '%s' from %s
.-1298
 (ER_UNKNOWN_TIME_ZONE)
 Unknown or incorrect time zone: '%s'
.-1299
 (ER_WARN_INVALID_TIMESTAMP)
 Invalid TIMESTAMP value in column '%s' at row %ld
.-1300
 (ER_INVALID_CHARACTER_STRING)
 Invalid %s character string: '%s'
.-1301
 (ER_WARN_ALLOWED_PACKET_OVERFLOWED)
 Result of %s() was larger than max_allowed_packet (%ld) - truncated
.-1302
 (ER_CONFLICTING_DECLARATIONS)
 Conflicting declarations: '%s%s' and '%s%s'
.-1303
 (ER_SP_NO_RECURSIVE_CREATE)
 Can't create a %s from within another stored routine
.-1304
 (ER_SP_ALREADY_EXISTS)
 %s %s already exists
.-1305
 (ER_SP_DOES_NOT_EXIST)
 %s %s does not exist
.-1306
 (ER_SP_DROP_FAILED)
 Failed to DROP %s %s
.-1307
 (ER_SP_STORE_FAILED)
 Failed to CREATE %s %s
.-1308
 (ER_SP_LILABEL_MISMATCH)
 %s with no matching label: %s
.-1309
 (ER_SP_LABEL_REDEFINE)
 Redefining label %s
.-1310
 (ER_SP_LABEL_MISMATCH)
 End-label %s without match
.-1311
 (ER_SP_UNINIT_VAR)
 Referring to uninitialized variable %s
.-1312
 (ER_SP_BADSELECT)
 PROCEDURE %s can't return a result set in the given context
.-1313
 (ER_SP_BADRETURN)
 RETURN is only allowed in a FUNCTION
.-1314
 (ER_SP_BADSTATEMENT)
 %s is not allowed in stored procedures
.-1315
 (ER_UPDATE_LOG_DEPRECATED_IGNORED)
 The update log is deprecated and replaced by the binary log; SET SQL_LOG_UPDATE has been ignored
.-1316
 (ER_UPDATE_LOG_DEPRECATED_TRANSLATED)
 The update log is deprecated and replaced by the binary log; SET SQL_LOG_UPDATE has been translated to SET SQL_LOG_BIN
.-1317
 (ER_QUERY_INTERRUPTED)
 Query execution was interrupted
.-1318
 (ER_SP_WRONG_NO_OF_ARGS)
 Incorrect number of arguments for %s %s; expected %u, got %u
.-1319
 (ER_SP_COND_MISMATCH)
 Undefined CONDITION: %s
.-1320
 (ER_SP_NORETURN)
 No RETURN found in FUNCTION %s
.-1321
 (ER_SP_NORETURNEND)
 FUNCTION %s ended without RETURN
.-1322
 (ER_SP_BAD_CURSOR_QUERY)
 Cursor statement must be a SELECT
.-1323
 (ER_SP_BAD_CURSOR_SELECT)
 Cursor SELECT must not have INTO
.-1324
 (ER_SP_CURSOR_MISMATCH)
 Undefined CURSOR: %s
.-1325
 (ER_SP_CURSOR_ALREADY_OPEN)
 Cursor is already open
.-1326
 (ER_SP_CURSOR_NOT_OPEN)
 Cursor is not open
.-1327
 (ER_SP_UNDECLARED_VAR)
 Undeclared variable: %s
.-1328
 (ER_SP_WRONG_NO_OF_FETCH_ARGS)
 Incorrect number of FETCH variables
.-1329
 (ER_SP_FETCH_NO_DATA)
 No data - zero rows fetched, selected, or processed
.-1330
 (ER_SP_DUP_PARAM)
 Duplicate parameter: %s
.-1331
 (ER_SP_DUP_VAR)
 Duplicate variable: %s
.-1332
 (ER_SP_DUP_COND)
 Duplicate condition: %s
.-1333
 (ER_SP_DUP_CURS)
 Duplicate cursor: %s
.-1334
 (ER_SP_CANT_ALTER)
 Failed to ALTER %s %s
.-1335
 (ER_SP_SUBSELECT_NYI)
 Subselect value not supported
.-1336
 (ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG)
 %s is not allowed in stored function or trigger
.-1337
 (ER_SP_VARCOND_AFTER_CURSHNDLR)
 Variable or condition declaration after cursor or handler declaration
.-1338
 (ER_SP_CURSOR_AFTER_HANDLER)
 Cursor declaration after handler declaration
.-1339
 (ER_SP_CASE_NOT_FOUND)
 Case not found for CASE statement
.-1340
 (ER_FPARSER_TOO_BIG_FILE)
 Configuration file '%s' is too big
.-1341
 (ER_FPARSER_BAD_HEADER)
 Malformed file type header in file '%s'
.-1342
 (ER_FPARSER_EOF_IN_COMMENT)
 Unexpected end of file while parsing comment '%s'
.-1343
 (ER_FPARSER_ERROR_IN_PARAMETER)
 Error while parsing parameter '%s' (line: '%s')
.-1344
 (ER_FPARSER_EOF_IN_UNKNOWN_PARAMETER)
 Unexpected end of file while skipping unknown parameter '%s'
.-1345
 (ER_VIEW_NO_EXPLAIN)
 EXPLAIN/SHOW can not be issued; lacking privileges for underlying table
.-1346
 (ER_FRM_UNKNOWN_TYPE)
 File '%s' has unknown type '%s' in its header
.-1347
 (ER_WRONG_OBJECT)
 '%s.%s' is not %s
.-1348
 (ER_NONUPDATEABLE_COLUMN)
 Column '%s' is not updatable
.-1349
 (ER_VIEW_SELECT_DERIVED)
 View's SELECT contains a subquery in the FROM clause
.-1350
 (ER_VIEW_SELECT_CLAUSE)
 View's SELECT contains a '%s' clause
.-1351
 (ER_VIEW_SELECT_VARIABLE)
 View's SELECT contains a variable or parameter
.-1352
 (ER_VIEW_SELECT_TMPTABLE)
 View's SELECT refers to a temporary table '%s'
.-1353
 (ER_VIEW_WRONG_LIST)
 View's SELECT and view's field list have different column counts
.-1354
 (ER_WARN_VIEW_MERGE)
 View merge algorithm can't be used here for now (assumed undefined algorithm)
.-1355
 (ER_WARN_VIEW_WITHOUT_KEY)
 View being updated does not have complete key of underlying table in it
.-1356
 (ER_VIEW_INVALID)
 View '%s.%s' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
.-1357
 (ER_SP_NO_DROP_SP)
 Can't drop or alter a %s from within another stored routine
.-1358
 (ER_SP_GOTO_IN_HNDLR)
 GOTO is not allowed in a stored procedure handler
.-1359
 (ER_TRG_ALREADY_EXISTS)
 Trigger already exists
.-1360
 (ER_TRG_DOES_NOT_EXIST)
 Trigger does not exist
.-1361
 (ER_TRG_ON_VIEW_OR_TEMP_TABLE)
 Trigger's '%s' is view or temporary table
.-1362
 (ER_TRG_CANT_CHANGE_ROW)
 Updating of %s row is not allowed in %strigger
.-1363
 (ER_TRG_NO_SUCH_ROW_IN_TRG)
 There is no %s row in %s trigger
.-1364
 (ER_NO_DEFAULT_FOR_FIELD)
 Field '%s' doesn't have a default value
.-1365
 (ER_DIVISION_BY_ZERO)
 Division by 0
.-1366
 (ER_TRUNCATED_WRONG_VALUE_FOR_FIELD)
 Incorrect %s value: '%s' for column '%s' at row %ld
.-1367
 (ER_ILLEGAL_VALUE_FOR_TYPE)
 Illegal %s '%s' value found during parsing
.-1368
 (ER_VIEW_NONUPD_CHECK)
 CHECK OPTION on non-updatable view '%s.%s'
.-1369
 (ER_VIEW_CHECK_FAILED)
 CHECK OPTION failed '%s.%s'
.-1370
 (ER_PROCACCESS_DENIED_ERROR)
 %s command denied to user '%s'@'%s' for routine '%s'
.-1371
 (ER_RELAY_LOG_FAIL)
 Failed purging old relay logs: %s
.-1372
 (ER_PASSWD_LENGTH)
 Password hash should be a #-digit hexadecimal number
.-1373
 (ER_UNKNOWN_TARGET_BINLOG)
 Target log not found in binlog index
.-1374
 (ER_IO_ERR_LOG_INDEX_READ)
 I/O error reading log index file
.-1375
 (ER_BINLOG_PURGE_PROHIBITED)
 Server configuration does not permit binlog purge
.-1376
 (ER_FSEEK_FAIL)
 Failed on fseek()
.-1377
 (ER_BINLOG_PURGE_FATAL_ERR)
 Fatal error during log purge
.-1378
 (ER_LOG_IN_USE)
 A purgeable log is in use, will not purge
.-1379
 (ER_LOG_PURGE_UNKNOWN_ERR)
 Unknown error during log purge
.-1380
 (ER_RELAY_LOG_INIT)
 Failed initializing relay log position: %s
.-1381
 (ER_NO_BINARY_LOGGING)
 You are not using binary logging
.-1382
 (ER_RESERVED_SYNTAX)
 The '%s' syntax is reserved for purposes internal to the MySQL server
.-1383
 (ER_WSAS_FAILED)
 WSAStartup Failed
.-1384
 (ER_DIFF_GROUPS_PROC)
 Can't handle procedures with different groups yet
.-1385
 (ER_NO_GROUP_FOR_PROC)
 Select must have a group with this procedure
.-1386
 (ER_ORDER_WITH_PROC)
 Can't use ORDER clause with this procedure
.-1387
 (ER_LOGGING_PROHIBIT_CHANGING_OF)
 Binary logging and replication forbid changing the global server %s
.-1388
 (ER_NO_FILE_MAPPING)
 Can't map file: %s, errno: #
.-1389
 (ER_WRONG_MAGIC)
 Wrong magic in %s
.-1390
 (ER_PS_MANY_PARAM)
 Prepared statement contains too many placeholders
.-1391
 (ER_KEY_PART_0)
 Key part '%s' length cannot be 0
.-1392
 (ER_VIEW_CHECKSUM)
 View text checksum failed
.-1393
 (ER_VIEW_MULTIUPDATE)
 Can not modify more than one base table through a join view '%s.%s'
.-1394
 (ER_VIEW_NO_INSERT_FIELD_LIST)
 Can not insert into join view '%s.%s' without fields list
.-1395
 (ER_VIEW_DELETE_MERGE_VIEW)
 Can not delete from join view '%s.%s'
.-1396
 (ER_CANNOT_USER)
 Operation %s failed for %s
.-1397
 (ER_XAER_NOTA)
 XAER_NOTA: Unknown XID
.-1398
 (ER_XAER_INVAL)
 XAER_INVAL: Invalid arguments (or unsupported command)
.-1399
 (ER_XAER_RMFAIL)
 XAER_RMFAIL: The command cannot be executed when global transaction is in the %s state
.-1400
 (ER_XAER_OUTSIDE)
 XAER_OUTSIDE: Some work is done outside global transaction
.-1401
 (ER_XAER_RMERR)
 XAER_RMERR: Fatal error occurred in the transaction branch - check your data for consistency
.-1402
 (ER_XA_RBROLLBACK)
 XA_RBROLLBACK: Transaction branch was rolled back
.-1403
 (ER_NONEXISTING_PROC_GRANT)
 There is no such grant defined for user '%s' on host '%s' on routine '%s'
.-1404
 (ER_PROC_AUTO_GRANT_FAIL)
 Failed to grant EXECUTE and ALTER ROUTINE privileges
.-1405
 (ER_PROC_AUTO_REVOKE_FAIL)
 Failed to revoke all privileges to dropped routine
.-1406
 (ER_DATA_TOO_LONG)
 Data too long for column '%s' at row %ld
.-1407
 (ER_SP_BAD_SQLSTATE)
 Bad SQLSTATE: '%s'
.-1408
 (ER_STARTUP)
 %s: ready for connections. Version: '%s' socket: '%s' port: # %s
.-1409
 (ER_LOAD_FROM_FIXED_SIZE_ROWS_TO_VAR)
 Can't load value from file with fixed size rows to variable
.-1410
 (ER_CANT_CREATE_USER_WITH_GRANT)
 You are not allowed to create a user with GRANT
.-1411
 (ER_WRONG_VALUE_FOR_TYPE)
 Incorrect %s value: '%s' for function %s
.-1412
 (ER_TABLE_DEF_CHANGED)
 Table definition has changed, please retry transaction
.-1413
 (ER_SP_DUP_HANDLER)
 Duplicate handler declared in the same block
.-1414
 (ER_SP_NOT_VAR_ARG)
 OUT or INOUT argument # for routine %s is not a variable or NEW pseudo-variable in BEFORE trigger
.-1415
 (ER_SP_NO_RETSET)
 Not allowed to return a result set from a %s
.-1416
 (ER_CANT_CREATE_GEOMETRY_OBJECT)
 Cannot get geometry object from data you send to the GEOMETRY field
.-1417
 (ER_FAILED_ROUTINE_BREAK_BINLOG)
 A routine failed and has neither NO SQL nor READS SQL DATA in its declaration and binary logging is enabled; if non-transactional tables were updated, the binary log will miss their changes
.-1418
 (ER_BINLOG_UNSAFE_ROUTINE)
 This function has none of DETERMINISTIC, NO SQL, or READS SQL DATA in its declaration and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)
.-1419
 (ER_BINLOG_CREATE_ROUTINE_NEED_SUPER)
 You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)
.-1420
 (ER_EXEC_STMT_WITH_OPEN_CURSOR)
 You can't execute a prepared statement which has an open cursor associated with it. Reset the statement to re-execute it.
.-1421
 (ER_STMT_HAS_NO_OPEN_CURSOR)
 The statement (%lu) has no open cursor.
.-1422
 (ER_COMMIT_NOT_ALLOWED_IN_SF_OR_TRG)
 Explicit or implicit commit is not allowed in stored function or trigger.
.-1423
 (ER_NO_DEFAULT_FOR_VIEW_FIELD)
 Field of view '%s.%s' underlying table doesn't have a default value
.-1424
 (ER_SP_NO_RECURSION)
 Recursive stored functions and triggers are not allowed.
.-1425
 (ER_TOO_BIG_SCALE)
 Too big scale %lu specified for column '%s'. Maximum is #.
.-1426
 (ER_TOO_BIG_PRECISION)
 Too big precision %lu specified for column '%s'. Maximum is %lu.
.-1427
 (ER_M_BIGGER_THAN_D)
 For float(M,D), double(M,D) or decimal(M,D), M must be >= D (column '%s').
.-1428
 (ER_WRONG_LOCK_OF_SYSTEM_TABLE)
 You can't combine write-locking of system '%s.%s' table with other tables
.-1429
 (ER_CONNECT_TO_FOREIGN_DATA_SOURCE)
 Unable to connect to foreign data source: %s
.-1430
 (ER_QUERY_ON_FOREIGN_DATA_SOURCE)
 There was a problem processing the query on the foreign data source. Data source error: %s
.-1431
 (ER_FOREIGN_DATA_SOURCE_DOESNT_EXIST)
 The foreign data source you are trying to reference does not exist. Data source error: %s
.-1432
 (ER_FOREIGN_DATA_STRING_INVALID_CANT_CREATE)
 Can't create federated table. The data source connection string '%s' is not in the correct format
.-1433
 (ER_FOREIGN_DATA_STRING_INVALID)
 The data source connection string '%s' is not in the correct format
.-1434
 (ER_CANT_CREATE_FEDERATED_TABLE)
 Can't create federated table. Foreign data src error: %s
.-1435
 (ER_TRG_IN_WRONG_SCHEMA)
 Trigger in wrong schema
.-1436
 (ER_STACK_OVERRUN_NEED_MORE)
 Thread stack overrun: %ld bytes used of a %ld byte stack, and %ld bytes needed. Use 'mysqld -O thread_stack=#' to specify a bigger stack.
.-1437
 (ER_TOO_LONG_BODY)
 Routine body for '%s' is too long
.-1438
 (ER_WARN_CANT_DROP_DEFAULT_KEYCACHE)
 Cannot drop default keycache
.-1439
 (ER_TOO_BIG_DISPLAYWIDTH)
 Display width out of range for column '%s' (max = %lu)
.-1440
 (ER_XAER_DUPID)
 XAER_DUPID: The XID already exists
.-1441
 (ER_DATETIME_FUNCTION_OVERFLOW)
 Datetime function: %s field overflow
.-1442
 (ER_CANT_UPDATE_USED_TABLE_IN_SF_OR_TRG)
 Can't update table '%s' in stored function/trigger because it is already used by statement which invoked this stored function/trigger.
.-1443
 (ER_VIEW_PREVENT_UPDATE)
 The definition of table '%s' prevents operation %s on table '%s'.
.-1444
 (ER_PS_NO_RECURSION)
 The prepared statement contains a stored routine call that refers to that same statement. It's not allowed to execute a prepared statement in such a recursive manner
.-1445
 (ER_SP_CANT_SET_AUTOCOMMIT)
 Not allowed to set autocommit from a stored function or trigger
.-1446
 (ER_MALFORMED_DEFINER)
 Definer is not fully qualified
.-1447
 (ER_VIEW_FRM_NO_USER)
 View '%s'.'%s' has no definer information (old table format). Current user is used as definer. Please recreate the view!
.-1448
 (ER_VIEW_OTHER_USER)
 You need the SUPER privilege for creation view with '%s'@'%s' definer
.-1449
 (ER_NO_SUCH_USER)
 There is no '%s'@'%s' registered
.-1450
 (ER_FORBID_SCHEMA_CHANGE)
 Changing schema from '%s' to '%s' is not allowed.
.-1451
 (ER_ROW_IS_REFERENCED_2)
 Cannot delete or update a parent row: a foreign key constraint fails (%s)
.-1452
 (ER_NO_REFERENCED_ROW_2)
 Cannot add or update a child row: a foreign key constraint fails (%s)
.-1453
 (ER_SP_BAD_VAR_SHADOW)
 Variable '%s' must be quoted with `...`, or renamed
.-1454
 (ER_TRG_NO_DEFINER)
 No definer attribute for trigger '%s'.'%s'. The trigger will be activated under the authorization of the invoker, which may have insufficient privileges. Please recreate the trigger.
.-1455
 (ER_OLD_FILE_FORMAT)
 '%s' has an old format, you should re-create the '%s' object(s)
.-1456
 (ER_SP_RECURSION_LIMIT)
 Recursive limit # (as set by the max_sp_recursion_depth variable) was exceeded for routine %s
.-1457
 (ER_SP_PROC_TABLE_CORRUPT)
 Failed to load routine %s. The table mysql.proc is missing, corrupt, or contains bad data (internal code #)
.-1458
 (ER_SP_WRONG_NAME)
 Incorrect routine name '%s'
.-1459
 (ER_TABLE_NEEDS_UPGRADE)
 Table upgrade required. Please do "REPAIR TABLE `%s`" to fix it!
.-1460
 (ER_SP_NO_AGGREGATE)
 AGGREGATE is not supported for stored functions
.-1461
 (ER_MAX_PREPARED_STMT_COUNT_REACHED)
 Can't create more than max_prepared_stmt_count statements (current value: %lu)
.-1462
 (ER_VIEW_RECURSIVE)
 `%s`.`%s` contains view recursion
.-1463
 (ER_NON_GROUPING_FIELD_USED)
 non-grouping field '%s' is used in %s clause
.-1464
 (ER_TABLE_CANT_HANDLE_SPKEYS)
 The used table type doesn't support SPATIAL indexes
.-1465
 (ER_NO_TRIGGERS_ON_SYSTEM_SCHEMA)
 Triggers can not be created on system tables
.-1466
 (ER_REMOVED_SPACES)
 Leading spaces are removed from name '%s'
.-1467
 (ER_AUTOINC_READ_FAILED)
 Failed to read auto-increment value from storage engine
.-1468
 (ER_USERNAME)
 user name
.-1469
 (ER_HOSTNAME)
 host name
.-1470
 (ER_WRONG_STRING_LENGTH)
 String '%s' is too long for %s (should be no longer than #)
.-1471
 (ER_NON_INSERTABLE_TABLE)
 The target table %s of the %s is not insertable-into
.-1472
 (ER_ADMIN_WRONG_MRG_TABLE)
 Table '%s' is differently defined or of non-MyISAM type or doesn't exist
.-1473
 (ER_TOO_HIGH_LEVEL_OF_NESTING_FOR_SELECT)
 Too high level of nesting for select
.-1474
 (ER_NAME_BECOMES_EMPTY)
 Name '%s' has become ''
.-1475
 (ER_AMBIGUOUS_FIELD_TERM)
 First character of the FIELDS TERMINATED string is ambiguous; please use non-optional and non-empty FIELDS ENCLOSED BY
.-1476
 (ER_LOAD_DATA_INVALID_COLUMN)
 Invalid column reference (%s) in LOAD DATA
.-1477
 (ER_LOG_PURGE_NO_FILE)
 Being purged log %s was not found
