
simple_null.4ae: simple_null.4gl
	$(FGLC) simple_null.4gl -o simple_null.4ae

compile: simple_null.4ae
	
run: simple_null.4ae
	sh ./run_simple_null



ansi_sql_compat:
	@echo "0"

desc
	@echo "Setting some basic types to null"
