
DATABASE test1

MAIN
	WHENEVER ERROR CONTINUE
	DROP TABLE xpto
	WHENEVER ERROR STOP
  CREATE TABLE xpto (
	  aColumn CHAR(5) PRIMARY KEY CONSTRAINT pkXpto,
		secondColumn INTEGER
	)
	ALTER TABLE xpto MODIFY (
    secondColumn INTEGER DEFAULT 1 NOT NULL
      UNIQUE CONSTRAINT unXpto
  )
	ALTER TABLE xpto MODIFY (
    secondColumn INTEGER DEFAULT 1 NOT NULL
      UNIQUE CONSTRAINT uniqueXpto
  )
	DROP TABLE xpto
END MAIN



