# -- Makefile for program tomake
# -- Generated by: TOMAKE Version 1.02 (1998-08-04)

.SUFFIXES: .4gl .42e .42o .per .42f .42m .42r .o .4gi .4go .o .4ge .frm

42R = tomake.42r
42E = tomake.42e
4GE = tomake.4ge
4GI = tomake.4gi

# --- Add the names of the form files for this program
FORMS_42F = 

FORMS_FRM = 

# --- List of other sources
OTHERSRCS = 

# --- D4GL C-code Object files
OBJECTS_42O = getopt.42o \
              instring.42o \
              tomake.42o

# --- D4GL P-code Module files
OBJECTS_42M = getopt.42m \
              instring.42m \
              tomake.42m

# --- I4GL object files
OBJECTS_O = getopt.o \
            instring.o \
            tomake.o

# --- I4GL-RDS object files
OBJECTS_4GO = getopt.4go \
              instring.4go \
              tomake.4go


# Program-specific compilation rules
all: 42r
	@echo "Use: '${MAKE} 42e' to create D4GL c-code executable"
	@echo "Use: '${MAKE} 4gi' to create I4GL p-code executable"
	@echo "Use: '${MAKE} 4ge' to create I4GL c-code executable"
all: 42r

42e: $(42E) $(FORMS_42F)

$(42E):  $(OBJECTS_42O) $(OTHERSRCS)
	fgl2c -o $(42E) $(OBJECTS_42O)

42r: $(42R) $(FORMS_42F)

$(42R):  $(OBJECTS_42M) $(OTHERSRCS)
	fgl2p -o $(42R) $(OBJECTS_42M)

4ge: $(4GE) $(FORMS_FRM)

$(4GE):  $(OBJECTS_O) $(OTHERSRCS)
	c4gl -o $(4GE) $(OBJECTS_O)

4gi: $(4GI) $(FORMS_FRM)

$(4GI):  $(OBJECTS_4GO) $(OTHERSRCS)
	cat $(OBJECTS_4GO) > $(4GI)

# --- Generic suffix rules for compiling D4GL
.per.42f:
	fglform $*.per

.4gl.42o:
	fgl2c -c $*.4gl

.4gl.42m:
	fgl2p -c $*.4gl


# --- Generic suffix rules for compiling I4GL
.per.frm:
	form4gl $*.per

.4gl.o:
	c4gl -c $*.4gl

.4gl.4go:
	fglpc -c $*.4gl

