test_oo:  fglobject.4gl obj2.4gl test_obj.4gl
	4glpc -Wall -g fglobject.4gl obj2.4gl test_obj.4gl -o test_oo

clean:
	rm fglobject.ao fglobject.c obj2.ao obj2.c test_obj.ao test_obj.c test_oo *.err || true
