

MAIN
  OPEN WINDOW w_a AT 2,3 WITH 6 ROWS, 50 COLUMNS ATTRIBUTE(BORDER)
  OPEN WINDOW w_b AT 3,4 WITH 6 ROWS, 50 COLUMNS ATTRIBUTE(BORDER)
	CURRENT WINDOW IS w_a
	CLOSE WINDOW w_a
	CLOSE WINDOW w_b
END MAIN
