
dt.4ae: dt.4gl
	${FGLC} dt.4gl -o dt.4ae

compile: dt.4ae
	
run: dt.4ae
	sh ./run_dt

ansi_sql_compat:
	@echo "1"

desc:
	@echo "Very basic datetime arithmetic"

sql_features_used:		; @echo "DATABASE_USED DEFINE_CHAR DEFINE_INTEGER IFX_SYSTABLES CURSOR_SELECT USE_REPORT FOREACH UI_DISPLAY_LINE_MODE DISPLAY IF EXIT_PROGRAM_EXPR REPORT_ORDER_BY REPORT_FIRST_PAGE_HEADER ON_EVERY_ROW "

