globals "sokoban.4gl"
function set_level()
  define lv_this_level integer
  let lv_this_level=get_level()
   if lv_this_level=1 then
        call display_copywrite("Author: David W. Skinner <sasquatch@bentonrea.com>","Copyright: (C) 2000","Name: Microban")
   end if
   case lv_this_level
      when 1
      let mv_level[1]="####"
      let mv_level[2]="# .#"
      let mv_level[3]="#  ###"
      let mv_level[4]="#*@  #"
      let mv_level[5]="#  $ #"
      let mv_level[6]="#  ###"
      let mv_level[7]="####"
    when 2
      let mv_level[1]="######"
      let mv_level[2]="#    #"
      let mv_level[3]="# #@ #"
      let mv_level[4]="# $* #"
      let mv_level[5]="# .* #"
      let mv_level[6]="#    #"
      let mv_level[7]="######"
    when 3
      let mv_level[1]="  ####"
      let mv_level[2]="###  ####"
      let mv_level[3]="#     $ #"
      let mv_level[4]="# #  #$ #"
      let mv_level[5]="# . .#@ #"
      let mv_level[6]="#########"
    when 4
      let mv_level[1]="########"
      let mv_level[2]="#      #"
      let mv_level[3]="# .**$@#"
      let mv_level[4]="#      #"
      let mv_level[5]="#####  #"
      let mv_level[6]="    ####"
    when 5
      let mv_level[1]=" #######"
      let mv_level[2]=" #     #"
      let mv_level[3]=" # .$. #"
      let mv_level[4]="## $@$ #"
      let mv_level[5]="#  .$. #"
      let mv_level[6]="#      #"
      let mv_level[7]="########"
    when 6
      let mv_level[1]="###### #####"
      let mv_level[2]="#    ###   #"
      let mv_level[3]="# $$     #@#"
      let mv_level[4]="# $ #...   #"
      let mv_level[5]="#   ########"
      let mv_level[6]="#####"
    when 7
      let mv_level[1]="#######"
      let mv_level[2]="#     #"
      let mv_level[3]="# .$. #"
      let mv_level[4]="# $.$ #"
      let mv_level[5]="# .$. #"
      let mv_level[6]="# $.$ #"
      let mv_level[7]="#  @  #"
      let mv_level[8]="#######"
    when 8
      let mv_level[1]="  ######"
      let mv_level[2]="  # ..@#"
      let mv_level[3]="  # $$ #"
      let mv_level[4]="  ## ###"
      let mv_level[5]="   # #"
      let mv_level[6]="   # #"
      let mv_level[7]="#### #"
      let mv_level[8]="#    ##"
      let mv_level[9]="# #   #"
      let mv_level[10]="#   # #"
      let mv_level[11]="###   #"
      let mv_level[12]="  #####"
    when 9
      let mv_level[1]="#####"
      let mv_level[2]="#.  ##"
      let mv_level[3]="#@$$ #"
      let mv_level[4]="##   #"
      let mv_level[5]=" ##  #"
      let mv_level[6]="  ##.#"
      let mv_level[7]="   ###"
    when 10
      let mv_level[1]="      #####"
      let mv_level[2]="      #.  #"
      let mv_level[3]="      #.# #"
      let mv_level[4]="#######.# #"
      let mv_level[5]="# @ $ $ $ #"
      let mv_level[6]="# # # # ###"
      let mv_level[7]="#       #"
      let mv_level[8]="#########"
    when 11
      let mv_level[1]="  ######"
      let mv_level[2]="  #    #"
      let mv_level[3]="  # ##@##"
      let mv_level[4]="### # $ #"
      let mv_level[5]="# ..# $ #"
      let mv_level[6]="#       #"
      let mv_level[7]="#  ######"
      let mv_level[8]="####"
    when 12
      let mv_level[1]="#####"
      let mv_level[2]="#   ##"
      let mv_level[3]="# $  #"
      let mv_level[4]="## $ ####"
      let mv_level[5]=" ###@.  #"
      let mv_level[6]="  #  .# #"
      let mv_level[7]="  #     #"
      let mv_level[8]="  #######"
    when 13
      let mv_level[1]="####"
      let mv_level[2]="#. ##"
      let mv_level[3]="#.@ #"
      let mv_level[4]="#. $#"
      let mv_level[5]="##$ ###"
      let mv_level[6]=" # $  #"
      let mv_level[7]=" #    #"
      let mv_level[8]=" #  ###"
      let mv_level[9]=" ####"
    when 14
      let mv_level[1]="#######"
      let mv_level[2]="#     #"
      let mv_level[3]="# # # #"
      let mv_level[4]="#. $*@#"
      let mv_level[5]="#   ###"
      let mv_level[6]="#####"
    when 15
      let mv_level[1]="     ###"
      let mv_level[2]="######@##"
      let mv_level[3]="#    .* #"
      let mv_level[4]="#   #   #"
      let mv_level[5]="#####$# #"
      let mv_level[6]="    #   #"
      let mv_level[7]="    #####"
    when 16
      let mv_level[1]=" ####"
      let mv_level[2]=" #  ####"
      let mv_level[3]=" #     ##"
      let mv_level[4]="## ##   #"
      let mv_level[5]="#. .# @$##"
      let mv_level[6]="#   # $$ #"
      let mv_level[7]="#  .#    #"
      let mv_level[8]="##########"
    when 17
      let mv_level[1]="#####"
      let mv_level[2]="# @ #"
      let mv_level[3]="#...#"
      let mv_level[4]="#$$$##"
      let mv_level[5]="#    #"
      let mv_level[6]="#    #"
      let mv_level[7]="######"
    when 18
      let mv_level[1]="#######"
      let mv_level[2]="#     #"
      let mv_level[3]="#. .  #"
      let mv_level[4]="# ## ##"
      let mv_level[5]="#  $ #"
      let mv_level[6]="###$ #"
      let mv_level[7]="  #@ #"
      let mv_level[8]="  #  #"
      let mv_level[9]="  ####"
    when 19
      let mv_level[1]="########"
      let mv_level[2]="#   .. #"
      let mv_level[3]="#  @$$ #"
      let mv_level[4]="##### ##"
      let mv_level[5]="   #  #"
      let mv_level[6]="   #  #"
      let mv_level[7]="   #  #"
      let mv_level[8]="   ####"
    when 20
      let mv_level[1]="#######"
      let mv_level[2]="#     ###"
      let mv_level[3]="#  @$$..#"
      let mv_level[4]="#### ## #"
      let mv_level[5]="  #     #"
      let mv_level[6]="  #  ####"
      let mv_level[7]="  #  #"
      let mv_level[8]="  ####"
    when 21
      let mv_level[1]="####"
      let mv_level[2]="#  ####"
      let mv_level[3]="# . . #"
      let mv_level[4]="# $$#@#"
      let mv_level[5]="##    #"
      let mv_level[6]=" ######"
    when 22
      let mv_level[1]="#####"
      let mv_level[2]="#   ###"
      let mv_level[3]="#. .  #"
      let mv_level[4]="#   # #"
      let mv_level[5]="## #  #"
      let mv_level[6]=" #@$$ #"
      let mv_level[7]=" #    #"
      let mv_level[8]=" #  ###"
      let mv_level[9]=" ####"
    when 23
      let mv_level[1]="#######"
      let mv_level[2]="#  *  #"
      let mv_level[3]="#     #"
      let mv_level[4]="## # ##"
      let mv_level[5]=" #$@.#"
      let mv_level[6]=" #   #"
      let mv_level[7]=" #####"
    when 24
      let mv_level[1]="# #####"
      let mv_level[2]="  #   #"
      let mv_level[3]="###$$@#"
      let mv_level[4]="#   ###"
      let mv_level[5]="#     #"
      let mv_level[6]="# . . #"
      let mv_level[7]="#######"
    when 25
      let mv_level[1]=" ####"
      let mv_level[2]=" #  ###"
      let mv_level[3]=" # $$ #"
      let mv_level[4]="##... #"
      let mv_level[5]="#  @$ #"
      let mv_level[6]="#   ###"
      let mv_level[7]="#####"
    when 26
      let mv_level[1]=" #####"
      let mv_level[2]=" # @ #"
      let mv_level[3]=" #   #"
      let mv_level[4]="###$ #"
      let mv_level[5]="# ...#"
      let mv_level[6]="# $$ #"
      let mv_level[7]="###  #"
      let mv_level[8]="  ####"
    when 27
      let mv_level[1]="######"
      let mv_level[2]="#   .#"
      let mv_level[3]="# ## ##"
      let mv_level[4]="#  $$@#"
      let mv_level[5]="# #   #"
      let mv_level[6]="#.  ###"
      let mv_level[7]="#####"
    when 28
      let mv_level[1]="#####"
      let mv_level[2]="#   #"
      let mv_level[3]="# @ #"
      let mv_level[4]="# $$###"
      let mv_level[5]="##. . #"
      let mv_level[6]=" #    #"
      let mv_level[7]=" ######"
    when 29
      let mv_level[1]="     #####"
      let mv_level[2]="     #   ##"
      let mv_level[3]="     #    #"
      let mv_level[4]=" ######   #"
      let mv_level[5]="##     #. #"
      let mv_level[6]="# $ $ @  ##"
      let mv_level[7]="# ######.#"
      let mv_level[8]="#        #"
      let mv_level[9]="##########"
    when 30
      let mv_level[1]="####"
      let mv_level[2]="#  ###"
      let mv_level[3]="# $$ #"
      let mv_level[4]="#... #"
      let mv_level[5]="# @$ #"
      let mv_level[6]="#   ##"
      let mv_level[7]="#####"
    when 31
      let mv_level[1]="  ####"
      let mv_level[2]=" ##  #"
      let mv_level[3]="##@$.##"
      let mv_level[4]="# $$  #"
      let mv_level[5]="# . . #"
      let mv_level[6]="###   #"
      let mv_level[7]="  #####"
    when 32
      let mv_level[1]=" ####"
      let mv_level[2]="##  ###"
      let mv_level[3]="#     #"
      let mv_level[4]="#.**$@#"
      let mv_level[5]="#   ###"
      let mv_level[6]="##  #"
      let mv_level[7]=" ####"
    when 33
      let mv_level[1]="#######"
      let mv_level[2]="#. #  #"
      let mv_level[3]="#  $  #"
      let mv_level[4]="#. $#@#"
      let mv_level[5]="#  $  #"
      let mv_level[6]="#. #  #"
      let mv_level[7]="#######"
    when 34
      let mv_level[1]="  ####"
      let mv_level[2]="###  ####"
      let mv_level[3]="#       #"
      let mv_level[4]="#@$***. #"
      let mv_level[5]="#       #"
      let mv_level[6]="#########"
    when 35
      let mv_level[1]="  ####"
      let mv_level[2]=" ##  #"
      let mv_level[3]=" #. $#"
      let mv_level[4]=" #.$ #"
      let mv_level[5]=" #.$ #"
      let mv_level[6]=" #.$ #"
      let mv_level[7]=" #. $##"
      let mv_level[8]=" #   @#"
      let mv_level[9]=" ##   #"
      let mv_level[10]="  #####"
    when 36
      let mv_level[1]="####"
      let mv_level[2]="#  ############"
      let mv_level[3]="# $ $ $ $ $ @ #"
      let mv_level[4]="# .....       #"
      let mv_level[5]="###############"
    when 37
      let mv_level[1]="      ###"
      let mv_level[2]="##### #.#"
      let mv_level[3]="#   ###.#"
      let mv_level[4]="#   $ #.#"
      let mv_level[5]="# $  $  #"
      let mv_level[6]="#####@# #"
      let mv_level[7]="    #   #"
      let mv_level[8]="    #####"
    when 38
      let mv_level[1]="##########"
      let mv_level[2]="#        #"
      let mv_level[3]="# ##.### #"
      let mv_level[4]="# # $$ . #"
      let mv_level[5]="# . @$## #"
      let mv_level[6]="#####    #"
      let mv_level[7]="    ######"
    when 39
      let mv_level[1]="#####"
      let mv_level[2]="#   ####"
      let mv_level[3]="# # # .#"
      let mv_level[4]="#    $ ###"
      let mv_level[5]="### #$.  #"
      let mv_level[6]="#   #@   #"
      let mv_level[7]="# # ######"
      let mv_level[8]="#   #"
      let mv_level[9]="#####"
    when 40
      let mv_level[1]=" #####"
      let mv_level[2]=" #   #"
      let mv_level[3]="##   ##"
      let mv_level[4]="# $$$ #"
      let mv_level[5]="# .+. #"
      let mv_level[6]="#######"
    when 41
      let mv_level[1]="#######"
      let mv_level[2]="#     #"
      let mv_level[3]="#@$$$ ##"
      let mv_level[4]="#  #...#"
      let mv_level[5]="##    ##"
      let mv_level[6]=" ######"
    when 42
      let mv_level[1]="   ####"
      let mv_level[2]="   #  #"
      let mv_level[3]="   #@ #"
      let mv_level[4]="####$.#"
      let mv_level[5]="#   $.#"
      let mv_level[6]="# # $.#"
      let mv_level[7]="#    ##"
      let mv_level[8]="######"
    when 43
      let mv_level[1]="     ####"
      let mv_level[2]="     # @#"
      let mv_level[3]="     #  #"
      let mv_level[4]="###### .#"
      let mv_level[5]="#   $  .#"
      let mv_level[6]="#  $$# .#"
      let mv_level[7]="#    ####"
      let mv_level[8]="###  #"
      let mv_level[9]="  ####"
    when 44
      let mv_level[1]="#####"
      let mv_level[2]="#@$.#"
      let mv_level[3]="#####"
    when 45
      let mv_level[1]="######"
      let mv_level[2]="#... #"
      let mv_level[3]="#  $ #"
      let mv_level[4]="# #$##"
      let mv_level[5]="#  $ #"
      let mv_level[6]="#  @ #"
      let mv_level[7]="######"
    when 46
      let mv_level[1]=" ######"
      let mv_level[2]="##    #"
      let mv_level[3]="#  ## #"
      let mv_level[4]="# # $ #"
      let mv_level[5]="#  * .#"
      let mv_level[6]="## #@##"
      let mv_level[7]=" #   #"
      let mv_level[8]=" #####"
    when 47
      let mv_level[1]="  #######"
      let mv_level[2]="###     #"
      let mv_level[3]="# $ $   #"
      let mv_level[4]="# ### #####"
      let mv_level[5]="# @ . .   #"
      let mv_level[6]="#   ###   #"
      let mv_level[7]="##### #####"
    when 48
      let mv_level[1]="######"
      let mv_level[2]="#  @ #"
      let mv_level[3]="#  # ##"
      let mv_level[4]="# .#  ##"
      let mv_level[5]="# .$$$ #"
      let mv_level[6]="# .#   #"
      let mv_level[7]="####   #"
      let mv_level[8]="   #####"
    when 49
      let mv_level[1]="######"
      let mv_level[2]="# @  #"
      let mv_level[3]="# $# #"
      let mv_level[4]="# $  #"
      let mv_level[5]="# $ ##"
      let mv_level[6]="### ####"
      let mv_level[7]=" #  #  #"
      let mv_level[8]=" #...  #"
      let mv_level[9]=" #     #"
      let mv_level[10]=" #######"
    when 50
      let mv_level[1]="  ####"
      let mv_level[2]="###  #####"
      let mv_level[3]="#  $  @..#"
      let mv_level[4]="# $    # #"
      let mv_level[5]="### #### #"
      let mv_level[6]="  #      #"
      let mv_level[7]="  ########"
    when 51
      let mv_level[1]="####"
      let mv_level[2]="#  ###"
      let mv_level[3]="#    ###"
      let mv_level[4]="#  $*@ #"
      let mv_level[5]="### .# #"
      let mv_level[6]="  #    #"
      let mv_level[7]="  ######"
    when 52
      let mv_level[1]="  ####"
      let mv_level[2]="### @#"
      let mv_level[3]="#  $ #"
      let mv_level[4]="#  *.#"
      let mv_level[5]="#  *.#"
      let mv_level[6]="#  $ #"
      let mv_level[7]="###  #"
      let mv_level[8]="  ####"
    when 53
      let mv_level[1]=" #####"
      let mv_level[2]="##. .##"
      let mv_level[3]="# * * #"
      let mv_level[4]="#  #  #"
      let mv_level[5]="# $ $ #"
      let mv_level[6]="## @ ##"
      let mv_level[7]=" #####"
    when 54
      let mv_level[1]="      ######"
      let mv_level[2]="      #    #"
      let mv_level[3]="  ##### .  #"
      let mv_level[4]="###  ###.  #"
      let mv_level[5]="# $  $  . ##"
      let mv_level[6]="# @$$ # . #"
      let mv_level[7]="##    #####"
      let mv_level[8]=" ######"
    when 55
      let mv_level[1]="########"
      let mv_level[2]="# @ #  #"
      let mv_level[3]="#      #"
      let mv_level[4]="#####$ #"
      let mv_level[5]="    #  ###"
      let mv_level[6]=" ## #$ ..#"
      let mv_level[7]=" ## #  ###"
      let mv_level[8]="    ####"
    when 56
      let mv_level[1]="#####"
      let mv_level[2]="#   ###"
      let mv_level[3]="#  $  #"
      let mv_level[4]="##* . #"
      let mv_level[5]=" #   @#"
      let mv_level[6]=" ######"
    when 57
      let mv_level[1]="  ####"
      let mv_level[2]="  #  #"
      let mv_level[3]="  #@ #"
      let mv_level[4]="  #  #"
      let mv_level[5]="### ####"
      let mv_level[6]="#    * #"
      let mv_level[7]="#  $   #"
      let mv_level[8]="#####. #"
      let mv_level[9]="    ####"
    when 58
      let mv_level[1]="####"
      let mv_level[2]="#  ####"
      let mv_level[3]="#.*$  #"
      let mv_level[4]="# .$# #"
      let mv_level[5]="## @  #"
      let mv_level[6]=" #   ##"
      let mv_level[7]=" #####"
    when 59
      let mv_level[1]="############"
      let mv_level[2]="#          #"
      let mv_level[3]="# ####### @##"
      let mv_level[4]="# #         #"
      let mv_level[5]="# #  $   #  #"
      let mv_level[6]="# $$ #####  #"
      let mv_level[7]="###  # # ...#"
      let mv_level[8]="  #### #    #"
      let mv_level[9]="       ######"
    when 60
      let mv_level[1]=" #########"
      let mv_level[2]=" #       #"
      let mv_level[3]="##@##### #"
      let mv_level[4]="#  #   # #"
      let mv_level[5]="#  #   $.#"
      let mv_level[6]="#  ##$##.#"
      let mv_level[7]="##$##  #.#"
      let mv_level[8]="#   $  #.#"
      let mv_level[9]="#   #  ###"
      let mv_level[10]="########"
    when 61
      let mv_level[1]="########"
      let mv_level[2]="#      #"
      let mv_level[3]="# #### #"
      let mv_level[4]="# #...@#"
      let mv_level[5]="# ###$###"
      let mv_level[6]="# #     #"
      let mv_level[7]="#  $$ $ #"
      let mv_level[8]="####   ##"
      let mv_level[9]="   #.###"
      let mv_level[10]="   ###"
    when 62
      let mv_level[1]="   ##########"
      let mv_level[2]="####    ##  #"
      let mv_level[3]="#  $$$....$@#"
      let mv_level[4]="#      ###  #"
      let mv_level[5]="#   #### ####"
      let mv_level[6]="#####"
    when 63
      let mv_level[1]="#####   ####"
      let mv_level[2]="#   ##### .#"
      let mv_level[3]="#       $  ########"
      let mv_level[4]="###  #### .$    @ #"
      let mv_level[5]="  #  #  #  ####   #"
      let mv_level[6]="  ####  ####  #####"
    when 64
      let mv_level[1]=" ######"
      let mv_level[2]="##    #"
      let mv_level[3]="#   $ #"
      let mv_level[4]="#  $$ #"
      let mv_level[5]="### .#####"
      let mv_level[6]="  ##.# @ #"
      let mv_level[7]="   #.  $ #"
      let mv_level[8]="   #. ####"
      let mv_level[9]="   ####"
    when 65
      let mv_level[1]="  ######"
      let mv_level[2]="  #    #"
      let mv_level[3]="  #  $ #"
      let mv_level[4]=" ####$ #"
      let mv_level[5]="## $ $ #"
      let mv_level[6]="#....# ##"
      let mv_level[7]="#     @ #"
      let mv_level[8]="##  #   #"
      let mv_level[9]=" ########"
    when 66
      let mv_level[1]="   ###"
      let mv_level[2]="   #@#"
      let mv_level[3]=" ###$###"
      let mv_level[4]="##  .  ##"
      let mv_level[5]="#  # #  #"
      let mv_level[6]="# #   # #"
      let mv_level[7]="# #   # #"
      let mv_level[8]="# #   # #"
      let mv_level[9]="#  # #  #"
      let mv_level[10]="## $ $ ##"
      let mv_level[11]=" ##. .##"
      let mv_level[12]="  #   #"
      let mv_level[13]="  #   #"
      let mv_level[14]="  #####"
    when 67
      let mv_level[1]="#####"
      let mv_level[2]="#   ##"
      let mv_level[3]="# #  #"
      let mv_level[4]="#@$*.##"
      let mv_level[5]="##  . #"
      let mv_level[6]=" # $# #"
      let mv_level[7]=" ##   #"
      let mv_level[8]="  #####"
    when 68
      let mv_level[1]=" ####"
      let mv_level[2]=" #  ######"
      let mv_level[3]="##    $  #"
      let mv_level[4]="# .# $   #"
      let mv_level[5]="# .#$#####"
      let mv_level[6]="# .@ #"
      let mv_level[7]="######"
    when 69
      let mv_level[1]="####  ####"
      let mv_level[2]="#  ####  #"
      let mv_level[3]="#  #  #  #"
      let mv_level[4]="#  #    $##"
      let mv_level[5]="#  . .#$  #"
      let mv_level[6]="#@ ## # $ #"
      let mv_level[7]="#   . #   #"
      let mv_level[8]="###########"
    when 70
      let mv_level[1]="#####"
      let mv_level[2]="# @ ####"
      let mv_level[3]="#      #"
      let mv_level[4]="# $ $$ #"
      let mv_level[5]="##$##  #"
      let mv_level[6]="#   ####"
      let mv_level[7]="# ..  #"
      let mv_level[8]="##..  #"
      let mv_level[9]=" ###  #"
      let mv_level[10]="   ####"
    when 71
      let mv_level[1]="###########"
      let mv_level[2]="#     #   ###"
      let mv_level[3]="# $@$ # .  .#"
      let mv_level[4]="# ## ### ## #"
      let mv_level[5]="# #       # #"
      let mv_level[6]="# #   #   # #"
      let mv_level[7]="# ######### #"
      let mv_level[8]="#           #"
      let mv_level[9]="#############"
    when 72
      let mv_level[1]="  ####"
      let mv_level[2]=" ##  #####"
      let mv_level[3]=" #  $  @ #"
      let mv_level[4]=" #  $#   #"
      let mv_level[5]="#### #####"
      let mv_level[6]="#  #   #"
      let mv_level[7]="#    $ #"
      let mv_level[8]="# ..#  #"
      let mv_level[9]="#  .####"
      let mv_level[10]="#  ##"
      let mv_level[11]="####"
    when 73
      let mv_level[1]="####"
      let mv_level[2]="#  #####"
      let mv_level[3]="# $$ $ #"
      let mv_level[4]="#      #"
      let mv_level[5]="## ## ##"
      let mv_level[6]="#...#@#"
      let mv_level[7]="# ### ##"
      let mv_level[8]="#      #"
      let mv_level[9]="#  #   #"
      let mv_level[10]="########"
    when 74
      let mv_level[1]=" ####"
      let mv_level[2]=" #  #######"
      let mv_level[3]=" #$ @#   .#"
      let mv_level[4]="## #$$   .#"
      let mv_level[5]="#  $  ##..#"
      let mv_level[6]="#   # #####"
      let mv_level[7]="###   #"
      let mv_level[8]="  #####"
    when 75
      let mv_level[1]=" #######"
      let mv_level[2]="## ....##"
      let mv_level[3]="#   ######"
      let mv_level[4]="#   $ $ @#"
      let mv_level[5]="###  $ $ #"
      let mv_level[6]="  ###    #"
      let mv_level[7]="    ######"
    when 76
      let mv_level[1]=" #####"
      let mv_level[2]="##   #"
      let mv_level[3]="#    #####"
      let mv_level[4]="#  #.#   #"
      let mv_level[5]="#@ #.# $ #"
      let mv_level[6]="#  #.#  ##"
      let mv_level[7]="#    #  #"
      let mv_level[8]="##  ##$$#"
      let mv_level[9]=" ##     #"
      let mv_level[10]="  #  ####"
      let mv_level[11]="  ####"
    when 77
      let mv_level[1]="##########"
      let mv_level[2]="# @ .... #"
      let mv_level[3]="#   ####$##"
      let mv_level[4]="## #  $ $ #"
      let mv_level[5]=" # $      #"
      let mv_level[6]=" #   ######"
      let mv_level[7]=" #####"
    when 78
      let mv_level[1]=" #######"
      let mv_level[2]="##     ##"
      let mv_level[3]="#  $ $  #"
      let mv_level[4]="# $ $ $ #"
      let mv_level[5]="## ### ####"
      let mv_level[6]=" #@  .....#"
      let mv_level[7]=" ##     ###"
      let mv_level[8]="  #######"
    when 79
      let mv_level[1]=" #########"
      let mv_level[2]=" #    #  #"
      let mv_level[3]="## $#$#  #"
      let mv_level[4]="#  .$.@  #"
      let mv_level[5]="#  .#    #"
      let mv_level[6]="##########"
    when 80
      let mv_level[1]="####"
      let mv_level[2]="#  #######"
      let mv_level[3]="#  . ## .#"
      let mv_level[4]="# $#    .#"
      let mv_level[5]="## ## # .#"
      let mv_level[6]=" #    #  #"
      let mv_level[7]=" #### #  #"
      let mv_level[8]="  # @$ ###"
      let mv_level[9]="  # $$ #"
      let mv_level[10]="  #    #"
      let mv_level[11]="  ######"
    when 81
      let mv_level[1]=" #####"
      let mv_level[2]=" #   #"
      let mv_level[3]=" # . #"
      let mv_level[4]="## * #"
      let mv_level[5]="#  *##"
      let mv_level[6]="#  @##"
      let mv_level[7]="## $ #"
      let mv_level[8]=" #   #"
      let mv_level[9]=" #####"
    when 82
      let mv_level[1]="#####"
      let mv_level[2]="#   ###"
      let mv_level[3]="# .   ##"
      let mv_level[4]="##*#$  #"
      let mv_level[5]="# .# $ #"
      let mv_level[6]="# @## ##"
      let mv_level[7]="#     #"
      let mv_level[8]="#######"
    when 83
      let mv_level[1]="######"
      let mv_level[2]="#    ##"
      let mv_level[3]="# $ $ ##"
      let mv_level[4]="## $$  #"
      let mv_level[5]=" # #   #"
      let mv_level[6]=" # ## ##"
      let mv_level[7]=" #  . .#"
      let mv_level[8]=" # @. .#"
      let mv_level[9]=" #  ####"
      let mv_level[10]=" ####"
    when 84
      let mv_level[1]="########"
      let mv_level[2]="#  ... #"
      let mv_level[3]="#  ### ##"
      let mv_level[4]="#  # $  #"
      let mv_level[5]="## #@$  #"
      let mv_level[6]=" # # $  #"
      let mv_level[7]=" # ### #####"
      let mv_level[8]=" #         #"
      let mv_level[9]=" #   ###   #"
      let mv_level[10]=" ##### #####"
    when 85
      let mv_level[1]="       ####"
      let mv_level[2]=" #######  #"
      let mv_level[3]=" # $      #"
      let mv_level[4]=" #   $ $  #"
      let mv_level[5]=" # ########"
      let mv_level[6]="## # .  #"
      let mv_level[7]="#  # #  #"
      let mv_level[8]="#  @ . ##"
      let mv_level[9]="## # # #"
      let mv_level[10]=" #   . #"
      let mv_level[11]=" #######"
    when 86
      let mv_level[1]="    ####"
      let mv_level[2]="  ###  ##"
      let mv_level[3]=" ## $   #"
      let mv_level[4]="## $  # #"
      let mv_level[5]="# @#$$  #"
      let mv_level[6]="# ..  ###"
      let mv_level[7]="# ..###"
      let mv_level[8]="#####"
    when 87
      let mv_level[1]="     ####"
      let mv_level[2]="######  #"
      let mv_level[3]="#       #"
      let mv_level[4]="#  ... .#"
      let mv_level[5]="##$######"
      let mv_level[6]="# $  #"
      let mv_level[7]="#   $###"
      let mv_level[8]="##  $  #"
      let mv_level[9]=" ## @  #"
      let mv_level[10]="  ######"
    when 88
      let mv_level[1]="     ####"
      let mv_level[2]=" # ###  #"
      let mv_level[3]=" # #    #"
      let mv_level[4]=" # #  # #"
      let mv_level[5]=" # #$ #.#"
      let mv_level[6]=" # #  # # #"
      let mv_level[7]=" # #$ #.# #"
      let mv_level[8]="   #  # # #"
      let mv_level[9]="####$ #.# #"
      let mv_level[10]="# @     # #"
      let mv_level[11]="#   #  ## #"
      let mv_level[12]="########"
    when 89
      let mv_level[1]="##########"
      let mv_level[2]="#   ##   #"
      let mv_level[3]="# $  $@# #"
      let mv_level[4]="#### # $ #"
      let mv_level[5]="   #.#  ##"
      let mv_level[6]=" # #.# $#"
      let mv_level[7]=" # #.   #"
      let mv_level[8]=" # #.   #"
      let mv_level[9]="   ######"
    when 90
      let mv_level[1]=" ########"
      let mv_level[2]=" #  @   #"
      let mv_level[3]=" # $  $ #"
      let mv_level[4]="### ## ###"
      let mv_level[5]="#  $..$  #"
      let mv_level[6]="#   ..   #"
      let mv_level[7]="##########"
    when 91
      let mv_level[1]="###########"
      let mv_level[2]="#    .##  #"
      let mv_level[3]="# $$@..$$ #"
      let mv_level[4]="#   ##.   #"
      let mv_level[5]="###########"
    when 92
      let mv_level[1]="  ####"
      let mv_level[2]="  #  #    #####"
      let mv_level[3]="  #  #    #   #"
      let mv_level[4]="  #  ######.# #"
      let mv_level[5]="####  $    .  #"
      let mv_level[6]="#   $$# ###.# #"
      let mv_level[7]="#   #   # #   #"
      let mv_level[8]="######### #@ ##"
      let mv_level[9]="          #  #"
      let mv_level[10]="          ####"
    when 93
      let mv_level[1]=" #########"
      let mv_level[2]="##   #   ##"
      let mv_level[3]="#    #    #"
      let mv_level[4]="#  $ # $  #"
      let mv_level[5]="#   *.*   #"
      let mv_level[6]="####.@.####"
      let mv_level[7]="#   *.*   #"
      let mv_level[8]="#  $ # $  #"
      let mv_level[9]="#    #    #"
      let mv_level[10]="##   #   ##"
      let mv_level[11]=" #########"
    when 94
      let mv_level[1]="#########"
      let mv_level[2]="# @ #   #"
      let mv_level[3]="# $ $   #"
      let mv_level[4]="##$### ##"
      let mv_level[5]="#  ...  #"
      let mv_level[6]="#   #   #"
      let mv_level[7]="######  #"
      let mv_level[8]="     ####"
    when 95
      let mv_level[1]="########"
      let mv_level[2]="#@     #"
      let mv_level[3]="# .$$. #"
      let mv_level[4]="# $..$ #"
      let mv_level[5]="# $..$ #"
      let mv_level[6]="# .$$. #"
      let mv_level[7]="#      #"
      let mv_level[8]="########"
    when 96
      let mv_level[1]="  ######"
      let mv_level[2]="  #    #"
      let mv_level[3]="  #    #"
      let mv_level[4]="#####  #"
      let mv_level[5]="#   #.#####"
      let mv_level[6]="#   $@$   #"
      let mv_level[7]="#####.#   #"
      let mv_level[8]="   ## ## ##"
      let mv_level[9]="   #   $.#"
      let mv_level[10]="   #   ###"
      let mv_level[11]="   #####"
    when 97
      let mv_level[1]="   ####"
      let mv_level[2]="   #  ########"
      let mv_level[3]="#### $ $.....#"
      let mv_level[4]="#   $   ######"
      let mv_level[5]="#@### ###"
      let mv_level[6]="#  $  #"
      let mv_level[7]="# $ # #"
      let mv_level[8]="## #  #"
      let mv_level[9]=" #    #"
      let mv_level[10]=" ######"
    when 98
      let mv_level[1]="#####"
      let mv_level[2]="#   ## ####"
      let mv_level[3]="#  $ ### .#"
      let mv_level[4]="# $   $  .#"
      let mv_level[5]="## $#####.# ####"
      let mv_level[6]="# $  # # .###  #"
      let mv_level[7]="#    # # .#  @ #"
      let mv_level[8]="###  # #       #"
      let mv_level[9]="  #### ##     ##"
      let mv_level[10]="        #######"
    when 99
      let mv_level[1]="               #####"
      let mv_level[2]="               #   #"
      let mv_level[3]="#######  ####### # #"
      let mv_level[4]="#     #  #  #      #"
      let mv_level[5]="#  @  ####  #     ####"
      let mv_level[6]="#  #    ....## ####  #"
      let mv_level[7]="#    ##### ## $$ $ $ #"
      let mv_level[8]="######   #           #"
      let mv_level[9]="         #  ##########"
      let mv_level[10]="         ####"
    when 100
      let mv_level[1]="#######"
      let mv_level[2]="# @#  #"
      let mv_level[3]="#.$   #"
      let mv_level[4]="#. # $##"
      let mv_level[5]="#.$#   #"
      let mv_level[6]="#. # $ #"
      let mv_level[7]="#  #   #"
      let mv_level[8]="########"
    when 101
      let mv_level[1]="  #####"
      let mv_level[2]="  #   #"
      let mv_level[3]="  # # #######"
      let mv_level[4]="  #  *  #   #"
      let mv_level[5]="  ## ##   # #"
      let mv_level[6]="  #     #*  #"
      let mv_level[7]="### # # # ###"
      let mv_level[8]="#  *#$+   #"
      let mv_level[9]="# #   ## ##"
      let mv_level[10]="#   #  *  #"
      let mv_level[11]="####### # #"
      let mv_level[12]="      #   #"
      let mv_level[13]="      #####"
    when 102
      let mv_level[1]="###########"
      let mv_level[2]="#....#    #"
      let mv_level[3]="#  #   $$ #"
      let mv_level[4]="#  @  ##  #"
      let mv_level[5]="#     ##$ #"
      let mv_level[6]="######  $ #"
      let mv_level[7]="     #    #"
      let mv_level[8]="     ######"
    when 103
      let mv_level[1]="  #####"
      let mv_level[2]="  # . ##"
      let mv_level[3]="### $  #"
      let mv_level[4]="# . $#@#"
      let mv_level[5]="# #$ . #"
      let mv_level[6]="#  $ ###"
      let mv_level[7]="## . #"
      let mv_level[8]=" #####"
    when 104
      let mv_level[1]="    #####"
      let mv_level[2]="#####   #"
      let mv_level[3]="#    $  #"
      let mv_level[4]="#  $#$#@#"
      let mv_level[5]="### #   #"
      let mv_level[6]="  # ... #"
      let mv_level[7]="  ###  ##"
      let mv_level[8]="    #  #"
      let mv_level[9]="    ####"
    when 105
      let mv_level[1]=" #### ####"
      let mv_level[2]="##  ###  ##"
      let mv_level[3]="#   # #   #"
      let mv_level[4]="#  *. .*  #"
      let mv_level[5]="###$   $###"
      let mv_level[6]=" #   @   #"
      let mv_level[7]="###$   $###"
      let mv_level[8]="#  *. .*  #"
      let mv_level[9]="#   # #   #"
      let mv_level[10]="##  ###  ##"
      let mv_level[11]=" #### ####"
    when 106
      let mv_level[1]=" ########"
      let mv_level[2]=" #      #"
      let mv_level[3]=" #@   $ #"
      let mv_level[4]="## ###$ #"
      let mv_level[5]="# .....###"
      let mv_level[6]="# $ $ $  #"
      let mv_level[7]="###### # #"
      let mv_level[8]="     #   #"
      let mv_level[9]="     #####"
    when 107
      let mv_level[1]="########"
      let mv_level[2]="#      #"
      let mv_level[3]="# $*** #"
      let mv_level[4]="# *  * #"
      let mv_level[5]="# *  * #"
      let mv_level[6]="# ***. #"
      let mv_level[7]="#     @#"
      let mv_level[8]="########"
    when 108
      let mv_level[1]="####     #####"
      let mv_level[2]="#  ###   #   ##"
      let mv_level[3]="#    #   #$ $ #"
      let mv_level[4]="#..# ##### #  #"
      let mv_level[5]="#  @    # $ $ #"
      let mv_level[6]="#..#         ##"
      let mv_level[7]="##   #########"
      let mv_level[8]=" #####"
    when 109
      let mv_level[1]="  #######"
      let mv_level[2]="# #     #"
      let mv_level[3]="# # # # #"
      let mv_level[4]="  # @ $ #"
      let mv_level[5]="### ### #"
      let mv_level[6]="#   ### #"
      let mv_level[7]="# $  ##.#"
      let mv_level[8]="## $  #.#"
      let mv_level[9]=" ## $  .#"
      let mv_level[10]="# ## $#.#"
      let mv_level[11]="## ## #.#"
      let mv_level[12]="### #   #"
      let mv_level[13]="### #####"
    when 110
      let mv_level[1]="  ####"
      let mv_level[2]="  #  #"
      let mv_level[3]="  # $####"
      let mv_level[4]="###. .  #"
      let mv_level[5]="# $ # $ #"
      let mv_level[6]="#  . .###"
      let mv_level[7]="####$ #"
      let mv_level[8]="   # @#"
      let mv_level[9]="   ####"
    when 111
      let mv_level[1]="######"
      let mv_level[2]="#    ####"
      let mv_level[3]="#    ...#"
      let mv_level[4]="#    ...#"
      let mv_level[5]="######  #"
      let mv_level[6]="  #  #  #"
      let mv_level[7]="  # $$ ##"
      let mv_level[8]="  # @$  #"
      let mv_level[9]="  # $$  #"
      let mv_level[10]="  ## $# #"
      let mv_level[11]="   #    #"
      let mv_level[12]="   ######"
    when 112
      let mv_level[1]=" #####"
      let mv_level[2]="##   ####"
      let mv_level[3]="#  $$$  #"
      let mv_level[4]="# #   $ #"
      let mv_level[5]="#   $## ##"
      let mv_level[6]="###  #.  #"
      let mv_level[7]="  #  #   #"
      let mv_level[8]=" ##### ###"
      let mv_level[9]=" #   # ##"
      let mv_level[10]=" # @....#"
      let mv_level[11]=" #      #"
      let mv_level[12]=" #   #  #"
      let mv_level[13]=" ########"
    when 113
      let mv_level[1]="   #####"
      let mv_level[2]="  ##   #"
      let mv_level[3]="###  # #"
      let mv_level[4]="#    . #"
      let mv_level[5]="#  ## #####"
      let mv_level[6]="#  . . #  ##"
      let mv_level[7]="#  # @ $   ###"
      let mv_level[8]="#####. #  $  #"
      let mv_level[9]="    ####  $  #"
      let mv_level[10]="       ## $ ##"
      let mv_level[11]="        #  ##"
      let mv_level[12]="        #  #"
      let mv_level[13]="        ####"
    when 114
      let mv_level[1]="######"
      let mv_level[2]="#    ###"
      let mv_level[3]="#  # $ #"
      let mv_level[4]="#  $ @ #"
      let mv_level[5]="## ## #####"
      let mv_level[6]="#  #......#"
      let mv_level[7]="# $ $ $ $ #"
      let mv_level[8]="##   ######"
      let mv_level[9]=" #####"
    when 115
      let mv_level[1]="    #####"
      let mv_level[2]="#####   ####"
      let mv_level[3]="#     #    #"
      let mv_level[4]="#  #.....  #"
      let mv_level[5]="##  ## # ###"
      let mv_level[6]=" #$$@$$$ #"
      let mv_level[7]=" #     ###"
      let mv_level[8]=" #######"
    when 116
      let mv_level[1]="     #####"
      let mv_level[2]="   ###   #"
      let mv_level[3]="####.....#"
      let mv_level[4]="# @$$$$$ #"
      let mv_level[5]="#     # ##"
      let mv_level[6]="#####   #"
      let mv_level[7]="    #####"
    when 117
      let mv_level[1]=" #### ####"
      let mv_level[2]=" #  ###  ##"
      let mv_level[3]=" #      @ #"
      let mv_level[4]="##..###   #"
      let mv_level[5]="#      #  #"
      let mv_level[6]="#...#$  # #"
      let mv_level[7]="# ## $$ $ #"
      let mv_level[8]="#  $    ###"
      let mv_level[9]="####  ###"
      let mv_level[10]="   ####"
    when 118
      let mv_level[1]=" #####"
      let mv_level[2]="##   ##"
      let mv_level[3]="#  $  ##"
      let mv_level[4]="# $ $  ##"
      let mv_level[5]="###$# . ##"
      let mv_level[6]="  # # .  #"
      let mv_level[7]=" ## ##.  #"
      let mv_level[8]=" # @  . ##"
      let mv_level[9]=" #   #  #"
      let mv_level[10]=" ########"
    when 119
      let mv_level[1]="  ######"
      let mv_level[2]="  #    ##"
      let mv_level[3]=" ## ##  #"
      let mv_level[4]=" # $$ # #"
      let mv_level[5]=" # @$ # #"
      let mv_level[6]=" #    # #"
      let mv_level[7]="#### #  #"
      let mv_level[8]="#  ... ##"
      let mv_level[9]="#     ##"
      let mv_level[10]="#######"
    when 120
      let mv_level[1]="      ####"
      let mv_level[2]="#######  #"
      let mv_level[3]="# $      ##"
      let mv_level[4]="# $#####  #"
      let mv_level[5]="#  @#  #  #"
      let mv_level[6]="## ##..   #"
      let mv_level[7]="#  # ..####"
      let mv_level[8]="# $  ###"
      let mv_level[9]="# $###"
      let mv_level[10]="#  #"
      let mv_level[11]="####"
    when 121
      let mv_level[1]=" ######"
      let mv_level[2]=" # .  #"
      let mv_level[3]="##$.# #"
      let mv_level[4]="#  *  #"
      let mv_level[5]="# ..###"
      let mv_level[6]="##$ # #####"
      let mv_level[7]="## ## #   #"
      let mv_level[8]="#  #### # #"
      let mv_level[9]="#   @ $ $ #"
      let mv_level[10]="##  #     #"
      let mv_level[11]=" ##########"
    when 122
      let mv_level[1]="#####"
      let mv_level[2]="#   ###"
      let mv_level[3]="# #$  #"
      let mv_level[4]="# $   #"
      let mv_level[5]="# $ $ #"
      let mv_level[6]="# $#  #"
      let mv_level[7]="#  @###"
      let mv_level[8]="## ########"
      let mv_level[9]="#      ...#"
      let mv_level[10]="#         #"
      let mv_level[11]="########..#"
      let mv_level[12]="       ####"
    when 123
      let mv_level[1]="########"
      let mv_level[2]="#      #"
      let mv_level[3]="# $ $$ ########"
      let mv_level[4]="##### @##. .  #"
      let mv_level[5]="    #$  # .   #"
      let mv_level[6]="    #   #. . ##"
      let mv_level[7]="    #$# ## # #"
      let mv_level[8]="    #        #"
      let mv_level[9]="    #  ###  ##"
      let mv_level[10]="    #  # ####"
      let mv_level[11]="    ####"
    when 124
      let mv_level[1]="##############"
      let mv_level[2]="#      #     #"
      let mv_level[3]="# $@$$ # . ..#"
      let mv_level[4]="## ## ### ## #"
      let mv_level[5]=" # #       # #"
      let mv_level[6]=" # #   #   # #"
      let mv_level[7]=" # ######### #"
      let mv_level[8]=" #           #"
      let mv_level[9]=" #############"
    when 125
      let mv_level[1]="      #####"
      let mv_level[2]="      #   ##"
      let mv_level[3]="      # $  #"
      let mv_level[4]="######## #@##"
      let mv_level[5]="# .  # $ $  #"
      let mv_level[6]="#        $# #"
      let mv_level[7]="#...#####   #"
      let mv_level[8]="#####   #####"
    when 126
      let mv_level[1]=" ###########"
      let mv_level[2]="##.......  #"
      let mv_level[3]="# $$$$$$$@ #"
      let mv_level[4]="#   # # # ##"
      let mv_level[5]="# # #     #"
      let mv_level[6]="#   #######"
      let mv_level[7]="#####"
    when 127
      let mv_level[1]="## ####"
      let mv_level[2]="####  ####"
      let mv_level[3]=" # $ $.  #"
      let mv_level[4]="## #  .$ #"
      let mv_level[5]="#   ##.###"
      let mv_level[6]="#  $  . #"
      let mv_level[7]="# @ #   #"
      let mv_level[8]="#  ######"
      let mv_level[9]="####"
    when 128
      let mv_level[1]="  #########"
      let mv_level[2]="###   #   #"
      let mv_level[3]="# * $ . . #"
      let mv_level[4]="#   $ ## ##"
      let mv_level[5]="####*#   #"
      let mv_level[6]=" #  @  ###"
      let mv_level[7]=" #   ###"
      let mv_level[8]=" #####"
    when 129
      let mv_level[1]="  #########"
      let mv_level[2]="### @ #   #"
      let mv_level[3]="# * $ *.. #"
      let mv_level[4]="#   $ #   #"
      let mv_level[5]="####*#  ###"
      let mv_level[6]=" #     ##"
      let mv_level[7]=" #   ###"
      let mv_level[8]=" #####"
    when 130
      let mv_level[1]="#####  #####"
      let mv_level[2]="#   ####.. #"
      let mv_level[3]="# $$$      #"
      let mv_level[4]="#   $#  .. #"
      let mv_level[5]="### @#  ## #"
      let mv_level[6]="  #  ##    #"
      let mv_level[7]="  ##########"
    when 131
      let mv_level[1]="#####"
      let mv_level[2]="#   #"
      let mv_level[3]="# . #"
      let mv_level[4]="#.@.###"
      let mv_level[5]="##.#  #"
      let mv_level[6]="#  $  #"
      let mv_level[7]="# $   #"
      let mv_level[8]="##$$  #"
      let mv_level[9]=" #  ###"
      let mv_level[10]=" #  #"
      let mv_level[11]=" ####"
    when 132
      let mv_level[1]="####"
      let mv_level[2]="# @###"
      let mv_level[3]="#.*  #####"
      let mv_level[4]="#..#$$ $ #"
      let mv_level[5]="##       #"
      let mv_level[6]=" # # ##  #"
      let mv_level[7]=" #   #####"
      let mv_level[8]=" #####"
    when 133
      let mv_level[1]=" #######"
      let mv_level[2]=" #  . .###"
      let mv_level[3]=" # . . . #"
      let mv_level[4]="### #### #"
      let mv_level[5]="#  @$  $ #"
      let mv_level[6]="#  $$  $ #"
      let mv_level[7]="####   ###"
      let mv_level[8]="   #####"
    when 134
      let mv_level[1]="        ####"
      let mv_level[2]="#########  #"
      let mv_level[3]="#   ## $   #"
      let mv_level[4]="#  $   ##  #"
      let mv_level[5]="### #. .# ##"
      let mv_level[6]="  # #. .#$##"
      let mv_level[7]="  # #   #  #"
      let mv_level[8]="  # @ $    #"
      let mv_level[9]="  #  #######"
      let mv_level[10]="  ####"
    when 135
      let mv_level[1]="#######"
      let mv_level[2]="#     #####"
      let mv_level[3]="# $$#@##..#"
      let mv_level[4]="# #       #"
      let mv_level[5]="#  $ # #  #"
      let mv_level[6]="#### $  ..#"
      let mv_level[7]="   ########"
    when 136
      let mv_level[1]=" #######"
      let mv_level[2]=" #     #"
      let mv_level[3]="## ###$##"
      let mv_level[4]="#.$   @ #"
      let mv_level[5]="# .. #$ #"
      let mv_level[6]="#.##  $ #"
      let mv_level[7]="#    ####"
      let mv_level[8]="######"
    when 137
      let mv_level[1]="       ####"
      let mv_level[2]="      ##  ###"
      let mv_level[3]="####  #  $  #"
      let mv_level[4]="#  #### $ $ #"
      let mv_level[5]="#   ..# #$  #"
      let mv_level[6]="#  #   @  ###"
      let mv_level[7]="## #..# ###"
      let mv_level[8]=" # ## # #"
      let mv_level[9]=" #      #"
      let mv_level[10]=" ########"
    when 138
      let mv_level[1]="  ####"
      let mv_level[2]="###  #"
      let mv_level[3]="#    ###"
      let mv_level[4]="# # . .#"
      let mv_level[5]="# @ ...####"
      let mv_level[6]="# # # #   ##"
      let mv_level[7]="#   # $$   #"
      let mv_level[8]="#####  $ $ #"
      let mv_level[9]="    ##$ # ##"
      let mv_level[10]="     #    #"
      let mv_level[11]="     ######"
    when 139
      let mv_level[1]=" ####"
      let mv_level[2]="##  ####"
      let mv_level[3]="#   ...#"
      let mv_level[4]="#   ...#"
      let mv_level[5]="#   # ##"
      let mv_level[6]="#   #@ #### ####"
      let mv_level[7]="##### $   ###  #"
      let mv_level[8]="    #  ##$ $   #"
      let mv_level[9]="   ###     $$  #"
      let mv_level[10]="   # $  ##   ###"
      let mv_level[11]="   #    ######"
      let mv_level[12]="   ######"
    when 140
      let mv_level[1]="######## #####"
      let mv_level[2]="#  #   ###   #"
      let mv_level[3]="#      ## $  #"
      let mv_level[4]="#.# @ ## $  ##"
      let mv_level[5]="#.#   # $  ##"
      let mv_level[6]="#.#    $  ##"
      let mv_level[7]="#. ## #####"
      let mv_level[8]="##    #"
      let mv_level[9]=" ######"
    when 141
      let mv_level[1]="  ########"
      let mv_level[2]="  #  # . #"
      let mv_level[3]="  #   .*.#"
      let mv_level[4]="  #  # * #"
      let mv_level[5]="####$##.##"
      let mv_level[6]="#      $ #"
      let mv_level[7]="# $ ## $ #"
      let mv_level[8]="#   @#   #"
      let mv_level[9]="##########"
    when 142
      let mv_level[1]="  ####"
      let mv_level[2]="  #  #"
      let mv_level[3]="  #  ####"
      let mv_level[4]="###$.$  #"
      let mv_level[5]="#  .@.  #"
      let mv_level[6]="#  $.$###"
      let mv_level[7]="####  #"
      let mv_level[8]="   #  #"
      let mv_level[9]="   ####"
    when 143
      let mv_level[1]="####"
      let mv_level[2]="#  ####"
      let mv_level[3]="# $   #"
      let mv_level[4]="# .#  #"
      let mv_level[5]="# $# ##"
      let mv_level[6]="# .  #"
      let mv_level[7]="#### #"
      let mv_level[8]="   # #"
      let mv_level[9]=" ### ###"
      let mv_level[10]=" #  $  #"
      let mv_level[11]="## #$# ##"
      let mv_level[12]="# $ @ $ #"
      let mv_level[13]="# ..#.. #"
      let mv_level[14]="###   ###"
      let mv_level[15]="  #####"
    when 144
      let mv_level[1]="   ####"
      let mv_level[2]=" ###  #####"
      let mv_level[3]=" # $$ #   #"
      let mv_level[4]=" # $ . .$$##"
      let mv_level[5]=" # .. #. $ #"
      let mv_level[6]="### #** .  #"
      let mv_level[7]="#  . **# ###"
      let mv_level[8]="# $ .# .. #"
      let mv_level[9]="##$$.@. $ #"
      let mv_level[10]=" #   # $$ #"
      let mv_level[11]=" #####  ###"
      let mv_level[12]="     ####"
    when 145
      let mv_level[1]="   #####"
      let mv_level[2]="   # @ #"
      let mv_level[3]="  ##   ##"
      let mv_level[4]="###.$$$.###"
      let mv_level[5]="#  $...$  #"
      let mv_level[6]="#  $.#.$  #"
      let mv_level[7]="#  $...$  #"
      let mv_level[8]="###.$$$.###"
      let mv_level[9]="  ##   ##"
      let mv_level[10]="   #   #"
      let mv_level[11]="   #####"
    when 146
      let mv_level[1]=" #######"
      let mv_level[2]="##  .  ##"
      let mv_level[3]="# .$$$. #"
      let mv_level[4]="# $. .$ #"
      let mv_level[5]="#.$ @ $.#"
      let mv_level[6]="# $. .$ #"
      let mv_level[7]="# .$$$. #"
      let mv_level[8]="##  .  ##"
      let mv_level[9]=" #######"
    when 147
      let mv_level[1]="       #####"
      let mv_level[2]="########   #"
      let mv_level[3]="#.   .  @#.#"
      let mv_level[4]="#  ###     #"
      let mv_level[5]="## $  #    #"
      let mv_level[6]=" # $   #####"
      let mv_level[7]=" # $#  #"
      let mv_level[8]=" ## #  #"
      let mv_level[9]="  #   ##"
      let mv_level[10]="  #####"
    when 148
      let mv_level[1]="###########"
      let mv_level[2]="#  .  #   #"
      let mv_level[3]="# #.  @   #"
      let mv_level[4]="#  #..# #######"
      let mv_level[5]="##  ## $$ $ $ #"
      let mv_level[6]=" ##           #"
      let mv_level[7]="  #############"
    when 149
      let mv_level[1]=" ####"
      let mv_level[2]="##  ###"
      let mv_level[3]="#@$   #"
      let mv_level[4]="### $ #"
      let mv_level[5]=" #  ######"
      let mv_level[6]=" #  $....#"
      let mv_level[7]=" #  # ####"
      let mv_level[8]=" ## # #"
      let mv_level[9]=" # $# #"
      let mv_level[10]=" #    #"
      let mv_level[11]=" #  ###"
      let mv_level[12]=" ####"
    when 150
      let mv_level[1]="     ####"
      let mv_level[2]=" #####  #"
      let mv_level[3]=" #     $#######"
      let mv_level[4]="## ## ..#  ...#"
      let mv_level[5]="# $ $$#$  @   #"
      let mv_level[6]="#        ###  #"
      let mv_level[7]="#######  # ####"
      let mv_level[8]="      ####"
    when 151
      let mv_level[1]="   ####"
      let mv_level[2]="   #  #"
      let mv_level[3]=" ###  #"
      let mv_level[4]="##  $ #"
      let mv_level[5]="#   # #"
      let mv_level[6]="# #$$ ######"
      let mv_level[7]="# #   #   .#"
      let mv_level[8]="#  $  @   .#"
      let mv_level[9]="###  ####..#"
      let mv_level[10]="  ####  ####"
    when 152
      let mv_level[1]="###### ####"
      let mv_level[2]="#     #    #"
      let mv_level[3]="#.##  #$##  #"
      let mv_level[4]="#   #     #  #"
      let mv_level[5]="#$  # ###  #  #"
      let mv_level[6]="# #      #  # #"
      let mv_level[7]="# # ####  # # #"
      let mv_level[8]="#. @    $ * . #"
      let mv_level[9]="###############"
    when 153
      let mv_level[1]="#############"
      let mv_level[2]="#.# @#  #   #"
      let mv_level[3]="#.#$$   # $ #"
      let mv_level[4]="#.#  # $#   #"
      let mv_level[5]="#.# $#  # $##"
      let mv_level[6]="#.#  # $#  #"
      let mv_level[7]="#.# $#  # $#"
      let mv_level[8]="#..  # $   #"
      let mv_level[9]="#..  #  #  #"
      let mv_level[10]="############"
    when 154
      let mv_level[1]=" ############################"
      let mv_level[2]=" #                          #"
      let mv_level[3]=" # ######################## #"
      let mv_level[4]=" # #                      # #"
      let mv_level[5]=" # # #################### # #"
      let mv_level[6]=" # # #                  # # #"
      let mv_level[7]=" # # # ################ # # #"
      let mv_level[8]=" # # # #              # # # #"
      let mv_level[9]=" # # # # ############ # # # #"
      let mv_level[10]=" # # # # #            # # # #"
      let mv_level[11]=" # # # # # ############ # # #"
      let mv_level[12]=" # # # # #              # # #"
      let mv_level[13]=" # # # # ################ # #"
      let mv_level[14]=" # # # #                  # #"
      let mv_level[15]="##$# # #################### #"
      let mv_level[16]="#. @ #                      #"
      let mv_level[17]="#############################"
    when 155
      let mv_level[1]="    ######               ####"
      let mv_level[2]="#####*#  #################  ##"
      let mv_level[3]="#   ###                      #"
      let mv_level[4]="#        ########  ####  ##  #"
      let mv_level[5]="### ####     #  ####  ####  ##"
      let mv_level[6]="#*# # .# # # #     #     #   #"
      let mv_level[7]="#*# #  #     # ##  # ##  ##  #"
      let mv_level[8]="###    ### ###  # ##  # ##  ##"
      let mv_level[9]=" #   # #*#      #     # #    #"
      let mv_level[10]=" #   # ###  #####  #### #    #"
      let mv_level[11]=" #####   #####  ####### ######"
      let mv_level[12]=" #   # # #**#               #"
      let mv_level[13]="## # #   #**#  #######  ##  #"
      let mv_level[14]="#    #########  #    ##### ###"
      let mv_level[15]="# #             # $        #*#"
      let mv_level[16]="#   #########  ### @#####  #*#"
      let mv_level[17]="#####       #### ####   ######"
      call levels_finished() exit program 0
   end case
end function
