

datetime.4ae: datetime.4gl
	$(FGLC) datetime.4gl -o datetime.4ae

compile: datetime.4ae
	
run: datetime.4ae
	sh ./run_datetime

ansi_sql_compat:
	@echo "0"


desc:
	@echo "Basic DB exercising of Datetimes"
	
sql_features_used:
	@echo "CREATE_TEMP_TABLE DDL_DATETIME"
	
