.-30002
A report cannot accept data as it has not been started
.-30003
You cannot FINISH REPORT - because the report has not been started
.-30004
string is too long to convert to BOOLEAN
.-30005
string value cannot be converted to BOOLEAN
.-30006
Invalid data type\n
.-30007
Screen too wide - maximum 255 characters
.-30008
Couldnt create window
.-30009
No spare windows left...
.-30010
Window not found
.-30011
Window is too small to display this form (too high)
.-30012
Window is too small to display this form (too wide)
.-30013
Window is too small to display this form
.-30014
Unable to create form
.-30015
No current form
.-30016
The row or column number in DISPLAY AT exceeds the limits of your terminal
.-30017
Internal error - window on top =0
.-30018
NOCURSES Mode has been specified - operation not permitted
.-30019
Window already exists (%s)
.-30020
Error displaying form in window
.-30021
Form not open
.-30022
The form has not been opened
.-30023
Panel not found....
.-30024
Window to move was not found
.-30025
Couldnt move window
.-30026
Unable to create field
.-30027
Internal Error
.-30028
Failed to create the loaded the form
.-30029
Internal error - unable to change field width
.-30030
No form
.-30031
Construct needs fixing to handle 'byname on tab.*'
.-30032
Number of fields is not the same as the number of variables
.-30033
No form displayed
.-30034
Table/Screen record does not exist in form
.-30035
Dubious form\n
.-30036
Field subscript out of bounds
.-30037
Too few variables for the number of fields
.-30038
Field name not found
.-30039
after field : field number not found!
.-30040
Format is wider than the field
.-30041
Internal error - no field list
.-30042
Form driver complaint
.-30043
Not implemented for TUI mode
.-30044
Field is not currently being input
.-30045
field_touched called with no fields...
.-30046
Internal error - no change in state 
.-30047
Unhandled code...
.-30048
Field not found
.-30049
Input form is not the current form!
.-30050
Blob not located
.-30051
No prompt window created
.-30052
Prompt message is too long to fit in the window.
.-30053
Internal error - couldn't create error window
.-30054
Internal error - negative messageline
.-30055
Not available in TUI mode (show_menu)
.-30056
Not available in TUI mode (enable/disable)
.-30057
Cant open gui form in curses mode..
.-30058
The NEXT OPTION name is not in the menu
.-30059
Menu option not found
.-30060
No current option
.-30061
Screen record not found
.-30062
Too many or too few variables for fields
.-30063
MAXCOUNT out of range (<0 or > array record size)
.-30064
set_scrline requires 1 parameter
.-30065
set_arrline requires 1 parameter
.-30066
Picture applied to a non-char field not implemented yet..
.-30067
Internal error - no change in state
.-30068
Screen record does not exist
.-30069
set_scrline() may only be called when in a display/input array
.-30070
Internal error - expected a .* in screen record
.-30071
Unknown screen record
.-30072
Unable to determine date from format
.-30073
Field or field subscript was not found
.-30074
Unable to open glade file\n
.-30075
Unable to find form
.-30076
Form was not opened
.-30077
Invalid response - did the client die ?
.-30078
Not connected
.-30079
Socket write failed
.-30080

.-30081
no fields found to clear...
.-30082
Internal error - no change in state..
.-30083
Internal error - bad change in state 
.-30084
Internal error - no break\n
.-30085
Input form is not current
.-30086
Invalid window style type
.-30087
INTERNAL ERROR BAD FORM
.-30088
Unable to create new window
.-30089
Unable to open form
.-30090
serious bug in widget.c
.-30091
GTK ERROR (%s)
.-30092
That shouldn't be posted by now...
.-30093
Not in TUI mode
.-30094
Invalid Widget
.-30095
Error creating pixmap
.-30096
make_pixbuf not available with GTK1.2
.-30097
Unable to load blob file
.-30098
Unable to open temporay file
.-30099
No menu displayed
.-30100
Invalid menu ID
.-30101
The row or column number in DISPLAY AT exceeds the limits of your terminal 1
.-30102
The row or column number in DISPLAY AT exceeds the limits of your terminal 2
.-30103
Not available in console driver
.-30104
Unable to open sqexplain.out file
.-30105
Could not connect to database
.-30106
Could not connect to database 
.-30107
Not connected to database
.-30108
Unexpected postgres return code1\n
.-30109
Table not found\n
.-30110
Invalid datatype for Aubit4GL
.-30111
Unexpected postgres return code2\n
.-30112
Database not open
.-30113
Unable to open file for unload
.-30114
Unexpected postgres return code3\n
.-30115
Unable to open blobfile
.-30116
Can't open cursor that hasn't been defined
.-30117
Cursor not found
.-30118
Column out of range
.-30119
Could not find statement or cursor specified
.-30120
Statement could not be found
.-30121
Unexpected postgres return code\n
.-30122
Currently unable to unload a statement that uses variables
.-30123
Parameter is not applicable to option
.-30124
Option was not found
.-30125
Unable to open blob
.-30126
Number of host variables does not match the sql string
.-30127
Cursor (%s) not found
.-30128
Preparing statement failed: %s
.-30129
Closing cursor (%s) failed
.-30130
declare_cursor (%s): Statement could not be found (sid == 0)
.-30131
declare_cursor: Cannot set cursor name (%s)
.-30132
Statement (%s) could not be found
.-30133
Statement (%s) did not contain a hstmt
.-30134
Preparing cursor (%s) failed
.-30135
Too many or too few host variables for 
.-30136
Binding input failed; cursor (%s)
.-30137
Opening cursor (%s) failed
.-30138
Binding output failed; cursor (%s)
.-30139
Fetch attempted on unopened cursor (%s)
.-30140
Fetching cursor (%s) failed
.-30141
SQLite database file not found in DBPATH=%s
.-30142
Could not connect to database (%s)
.-30143
Can't free cursor (%s) that hasn't been defined
.-30144
Can't close cursor (%s) that hasn't been defined
.-30145
Not connected to database (%s)
.-30146
Allocating a statement failed
.-30147
Statement has not been prepared
.-30148
Internal Error (describecolumn)
.-30149
Unable to retrieve column info for table (%s)\n
.-30150
Session (%s) already opened
.-30151
Could not make session (%s) current as it does not exist
.-30152
Session Id (%s) does not exist
.-30153
Could not disconnect from the database
.-30154
Error opening file (%s) for unload
.-30155
Not implemented A4GLSQL_flush_cursor
.-30156
Sessions not implemented
.-30157
Could not start MySQL embedded server
.-30158
Started MySQL embedded server
.-30159
SQL Transaction Error
.-30160
No database connection
.-30161
No statement
.-30162
Too many or too few host variables
.-30163
Can't declare cursor for non-prepared statement
.-30164
Cursor not found (%s)
.-30165
Fetch Relative or Absolute on a non-scroll cursor
.-30166
Can't close cursor that hasn't been defined
.-30167
Can't open file for unload
.-30168
Invalid statement name or statement was not prepared. (%s)
.-30169
Couldn't open schema file
.-30170
Parse error in schema file - no ']'
.-30171
Not available in windows build
.-30172
Could not defer interrupt
.-30173
Could not attach SegFault Handler
.-30174
Unable to attach SIGCLD handler
.-30175
Unable to attach SIGPIPE handler
.-30176
Not an object of type (ui.combobox) or not initialized
.-30177
Unable to open SQL library...
.-30178
Unable to open help file
.-30179
Unable to open language file
.-30180
No language file
.-30181
message not found
.-30182
Could not read lang text
.-30183
Unable to open UI library...
.-30184
Invalid date
.-30185
Unable to open PACKER library...
.-30186
Form was not found
.-30187
Invalid Form info request
.-30188
Invalid Connection info request
.-30189
Invalid statement info request
.-30190
Window was not found
.-30191
Invalid Window info request
.-30192
Invalid type called in get_info
.-30193
Wrong number of arguments
.-30194
Cant do a load within a load...
.-30195
Could not open file for load
.-30196
Error in getting number of columns for load (does the table '%s' exist?)
.-30197
Internal Error : Error generating insert string for load
.-30198
Number of fields in load file does not equal the number of columns %s
.-30199
Error reading load file at line %s
.-30200
Error in getting number of columns for load
.-30201
trunc not implemented\n
.-30202
round not implemented\n
.-30203
exp not implemented\n
.-30204
logn not implemented\n
.-30205
log not implemented\n
.-30206
Internal Error : Couldnt process datatype %x\n
.-30207
Internal Error : Couldnt process datatype \n
.-30208
Unknown attribute
.-30209
Unable to open FORM library...
.-30210
Construct callback function returns a variable that is too long
.-30211
MAPM Error
.-30212
MAPM Warning
.-30213
Type cannot be converted to an object (%s)
.-30214
Error in conversion
.-30215
Stack overflow
.-30216
Too many bindings
.-30217
Could not find copyback variable as a COPYOF parameter
.-30218
A character variable has referenced subscripts that are out of range
.-30219
Unable to open Error Log file
.-30220
Error Log file is not open
.-30221
4Js DDE functions not implemented
.-30222
4Js winexecwait function not implemented
.-30223
4Js winexec function not implemented
.-30224
No DLL Loaded
.-30225
0: Non-existing function called in DLL\n
.-30226
Error: can't open DLL - STOP. See debug.out
.-30227
Could not open shared library
.-30228
Could not find function in shared library
.-30229
Could not open share library
.-30230
2: Non-existing function (%s) called in DLL
.-30231
Unable to load shared library file
.-30232
Unable to load function from shared libary
.-30233
dmy.c - Invalid DBDATE format: %s
.-30234
Unable to open EXDTYPE library.
.-30235
Unable to find function (%s)
.-30236
Invalid prepared statement
.-30237
Unable to remove original ACL file
.-30238
Dubious string size
.-30239
Unknown operation
.-30240
Unknown/non-handled special name in field colour where clause
.-30241
Unknown comparison %s
.-30242
Internal error - unhandled field comparison
.-30243
Internal error-unexpected keytype for A4GL_is_special_key
.-30244
Can't resize a non-allocated dynamic array
.-30245
Dynamic Array has not been allocated or has already been freed
.-30246
DLL functions not available yet for WIN32 platforms
.-30247
Error: Cannot determine AUBITDIR - STOP.
.-30248
Unable to open ESQL library...
.-30249
Incompatible storage size
.-30250
Recurrsive replacement?
.-30251
Invalid operation on a character string (1)
.-30252
Invalid operation on a character string (2)
.-30253
Can't use interval YEAR-MONTH and DAY-FRACTION together
.-30254
You can't multiply two intervals...
.-30255
You can't mod two intervals...
.-30256
You can't raise the power of intervals...
.-30257
Unread blob
.-30258
Out of heap
.-30259
Not an object of type base.channel - or not initialized
.-30260
expects 1 parameter
.-30261
Expects 2 parameters
.-30262
File is not open
.-30263
Expected 1 parameter
.-30264
Not an object of type ui.window - or not initialized
.-30265
expects 0 parameter
.-30266
Not an object of type ui.form - or not initialized
.-30267
Unable to open key file
.-30268
Ran out of keys
.-30269
Unknown Key
.-30270
A4GL_KEYLOG and A4GL_KEYFILE both point to the same file
.-30271
Unable to open key logging file
.-30272
Unable to open RPC library...
.-30273
Unable to open MENU library...
.-30274
Unable to open EXREPORT library...
.-30275
Could not open report output
.-30276
Cant print at this column with that right margin :-(
.-30277
Big Oops
.-30278
Internal error - unable to prepare statement
.-30279
Internal error - unable to declare statement
.-30280
Unable to open PRINT FILE file
.-30281
Unknown error
.-30282
Value exceeds limit of SMALLINT 
.-30283
conv.c - Invalid DBDATE format: %s
.-30284
Invalid conversion
.-30285
Unable to open HELP library...
.-30286
Unable to open SQLPARSE library...
.-30287
Unable to start TCP session
.-30288
Assertion failed %s
.-30289
Assertion failed
.-30290
Unable to determine current action...
.-30291
You have specified PRINTSCRKEY but not PRINTSCRFILE
.-30292
Cannot add a month/day and a non-month day interval
.-30293
Can't add an interval to a number
.-30294
Can't subtract numbers and interval
.-30295
Can't multiply two intervals
.-30296
Unable to open library
.-30297
Help message not found
.-30298
Could not read help message
.-30299
Invalid file (%s)
.-30300
Unable to open
.-30301
Unable to open form in memory
.-30302
Invalid barcode type
.-30303
Unable to generate QR code
.-30304
Invalid DBDATE format(1)
.-30305
Invalid DBDATE format(2)
.-30306
Invalid DBDATE format(3)
.-30307
XMLRPC Error
.-30308
Call failed
.-30309
Couldnt open form - does not appear to be a valid form file
.-30310
Couldnt open form
.-30311
Unable to read form
.-30312
This form has a version number that I can't handle
.-30313
Form compilation error
.-30314
Error opening output\n
.-30315
Unable to locate font
.-30316
Not implemented yet...\n
.-30317
Unable to open file %s %s
.-30318
Unable to open file.
.-30319
PDF Error
.-30320
Menu item does not exist
.-30321
Untransmittable data
.-30322
Can't Handle Base64 Data
.-30323
Can't Handle Complex Data
.-30324
Can't Handle Pointers
.-30325
Got a 0xDEAD
.-30326
UNKNOWN XML TYPE
.-30327
unable to free arguments
.-30328
cannot create udp service.
.-30329
unable to register (FGL_RPC, FGL_RPC_VER, udp).
.-30330
cannot create tcp service.
.-30331
unable to register (FGL_RPC, FGL_RPC_VER, tcp).
.-30332
Function Already registered
.-30333
Function not registered
.-30334
RPC server failed
.-30335
Unable to send asynchronous reply!
.-30336
Unprintable datatype
.-30337
serious bug in rpc_server.c
.-30338
Unable to connect to host
.-30339
RPC call failed
.-30340
Bad SQL: %s
.-30341
Unable to open PARSER library...
.-30342
Unable to open LEX library...
.-30343
You cannot FINISH REPORT - becasue the report has not been started
.-30344
Unexpected ingres return code (D)\n
.-30345
Unexpected ingres return code (O) \n
.-30346
Unexpected ingres return code (F2)\n
.-30347
get_Validation not implemented yet for Ingres
.-30348
Could not fill_array - Wrong mode asked!
.-30349
Could not fill_array - DATABASES service not implemented !
.-30350
Could not fill_array - TABLES service not implemented !
.-30351
Could not fill_array - Invalid service asked !
.-30352
Database name not set
.-30353
Session already opened
.-30354
Invalid bind\n
.-30355
Use of unlocated blob variable...
.-30356
Invalid cursor type
.-30357
Invalid fetch
.-30358
Error binding
.-30359
Invalid datatype
.-30360
Out of memory 1
.-30361
Out of memory2
.-30362
Invalid Datatype
.-30363
Internal error
.-30364
Database name not seted
.-30366
Datatype has not been loaded
.-30368
Invalid Form
.-30369
Unknown widget ID
.-30370
Unable to open LOGREP library...
.-30371
Unable to open LOGREPPROC library...
.-30372
Unable to open file
.-30374
Couldn't create window
.-30375
Couldn't move window
.-30376
Internal Error : Couldn't process datatype \n
.-30377
Couldn't open form - does not appear to be a valid form file
.-30378
Couldn't open form
.-30380
Function returned incorrect number of values
.-30382
No current table
.-30384
Not an object of type 'STRING' - or not initialized
.-30386
Invalid barcode
.-30387
Invalid character in barcode
.-30388
Invalid length of barcode
.-30390
GTK ERROR
.-30392
Not an object of type not initialized
.-30393
Not an object of the correct type or not initialized
.-30394
Not an object of the correct type, or not initialized
.-30396
Parameter is not a reference
.-30398
Unable to open SQLPARSECMD library...
