
/**
 * @file
 * This test suite was generated by genTestSuite.pl based on the 4gl files
 * that found in a directory
 */

#include <stdio.h>
#include "GenFglTest.h"

// @todo : Declare this in a .h
int parse_4gl(const char *fileName);

#define PARSE_OK 0

// Registers the fixture into the 'registry'
//CPPUNIT_TEST_SUITE_REGISTRATION( GenFglTest );


void 
GenFglTest::setUp()
{
}


void 
GenFglTest::tearDown()
{
}
  
void GenFglTest::fgl_with_errors_syntax_wrong_define()
{
  FglParse *fglParse = new FglParse("fgl/with_errors/syntax/wrong_define.4gl");
  CPPUNIT_ASSERT_EQUAL(
    PARSE_OK,fglParse->getParsingResult()
  );
	delete fglParse;
}
