

prompt_err.4ae: prompt_err.4gl
	${FGLC} prompt_err.4gl -o prompt_err.4ae

compile: prompt_err.4ae
	
run: prompt_err.4ae
	sh ./run_prompt_err

ansi_sql_compat:
	@echo "1"

desc:
	@echo "Simple PROMPT"
