
using.4ae: using.4gl
	$(FGLC) using.4gl -o using.4ae

compile: using.4ae
	
run: using.4ae
	sh ./run_using

ansi_sql_compat:
	@echo "1"


sql_features_used:		; @echo "DATABASE_USED CREATE_TEMP_TABLE CURSOR_SELECT FOREACH UI_DISPLAY_LINE_MODE DISPLAY EXIT_PROGRAM_EXPR CLOSE_CURSOR DROP_TABLE "

