

chartst.4ae: chartst.4gl
	$(FGLC) chartst.4gl -o chartst.4ae

compile: chartst.4ae
	
run: chartst.4ae
	sh ./run_chartst

ansi_sql_compat:
	@echo "1"


sql_features_used:		; @echo "DATABASE_USED DEFINE_DATETIME DDL_DATETIME CREATE_TEMP_TABLE UI_DISPLAY_LINE_MODE DISPLAY ANSI_INSERT INITIALIZE_NULL "

