.-30001
Unable to open EXREPORT library.
.-30002
Unable to open  library...
.-30003
Unable to open RPC library.
.-30004
Unable to open SQL library.
.-30005
Unable to open UI library.
.-30006
Unable to determine current action...
.-30007
Unable to open Error Log file
.-30008
Error Log file is not open
.-30009
acli_scroll not implemented
.-30010
4Js DDE functions not implemented
.-30011
4Js winmessage function not implemented
.-30012
4Js winexecwait function not implemented
.-30013
4Js winexec function not implemented
.-30014
trunc not implemented
.-30015
round not implemented
.-30016
exp not implemented
.-30017
logn not implemented
.-30018
log not implemented
.-30019
length not implemented
.-30020
Internal Error : Couldnt process datatype %x
.-30021
Internal Error : Couldnt process datatype 
.-30022
DLL functions not available yet for WIN32 platforms
.-30023
No DLL Loaded
.-30024
0: Non-existing function called in DLL
.-30025
Error: Cannot determine AUBITDIR - STOP.
.-30026

.-30027
Error: can't open DLL - STOP. See debug.out
.-30028
Could not open shared library
.-30029
Could not find function in shared library
.-30030
Could not open share library
.-30031
2: Non-existing function (%s) called in DLL
.-30032
Unable to load shared library file
.-30033
Unable to load function from shared libary
.-30034
does not fit
.-30035
conv.c - Invalid DBDATE format: %s
.-30036
Assertion failed %s
.-30037
Unable to open library
.-30038
Unable to open EXDTYPE library.
.-30039
Unable to find function
.-30040
Invalid date
.-30041
dmy.c - Invalid DBDATE format: %s
.-30042
Unknown error
.-30043
Unable to open help file
.-30044
Unable to open language file
.-30045
No language file
.-30046
message not found
.-30047
Could not read lang text
.-30048
Could not defer interrupt
.-30049
Could not attach SegFault Handler
.-30050
SA_NOCLDWAIT on Windows? FIXME!
.-30051
Unable to attach SIGCLD handler
.-30052
Unable to start TCP session
.-30053
Front end closed unexpectedly
.-30054
Connection Dropped
.-30055
Error Starting Winsock
.-30056
Form was not found
.-30057
Invalid Window info request
.-30058
Invalid statement info request
.-30059
Window was not found
.-30060
Invalid type called in get_info
.-30061
Wrong number of arguments
.-30062
Cannot add a month/day and a non-month day interval
.-30063
Can't add an interval to a number
.-30064
Can't subtract numbers and interval
.-30065
Can't multiply two intervals
.-30066
Could not open file for load
.-30067
Error in getting number of columns for load
.-30068
Internal Error : Error generating insert string for load
.-30069
Error reading load file at line %s
.-30070
Internal error in_dt_ops
.-30071
Unknown operation
.-30072
Can't use interval YEAR-MONTH and DAY-FRACTION together
.-30073
You can't multiply two intervals...
.-30074
You can't mod two intervals...
.-30075
You can't raise the A4GL_power of intervals...
.-30076
Unable to open key file
.-30077
Ran out of keys
.-30078
Unknown Key
.-30079
Could not open report output
.-30080
Internal error
.-30081
Big Opps
.-30082
Not implemented
.-30083
Error in conversion
.-30084
Stack overflow
.-30085
Could not initialize variable to null
.-30086
Too many bindings
.-30087
Dubious string size
.-30088
Not connected to database
.-30089
Cursor not found
.-30090
Can't execute unprepared statement
.-30091
Memory Allocation Error
.-30092
Can't declare cursor for non-prepared statement
.-30093
Cursor already open
.-30094
Too many or too few host variables
.-30095
Fetch attempted on unopened cursor
.-30096
Could not connect to database
.-30097
Can't free cursor thats not been defined
.-30098
Can't close cursor that hasn't been defined
.-30099
Statement has not been prepared
.-30100
Internal Error (describecolumn)
.-30101
Could not find statement or cursor specified
.-30102
Statement could not be found
.-30103
Error getting column info
.-30104
Session already opened
.-30105
%s is not a statement or cursor name
.-30106
Session Id (%s) does not exist
.-30107
Could not disconnect from database
.-30108
Error opening file for unload
.-30109
Parameter is not applicable to option
.-30110
Option was not found
.-30111
Blob not located
.-30112
Unable to open blob
.-30113
Database name not seted
.-30114
Invalid data type
.-30115
Invalid bind
.-30116
Invalid cursor type
.-30117
Invalid fetch
.-30118
Error binding
.-30119
Could not fill_array - Wrong mode asked!
.-30120
Could not fill_array - DATABASES service not implemented !
.-30121
Could not fill_array - TABLES service not implemented !
.-30122
Could not fill_array - Invalid service asked !
.-30123
Invalid datatype for Aubit4GL
.-30124
Couldnt open form - does not appear to be a valid form file
.-30125
Couldnt open form
.-30126
Unable to read form
.-30127
This form has a version number that I can't handle
.-30128
Not in GUI mode
.-30129
Error creating pixmap
.-30130
Input form is not the current form!
.-30131
Screen record not found
.-30132
Screen record does not exist
.-30133
set_scrline requires 1 parameter
.-30134
set_arrline requires 1 parameter
.-30135
set_scrline() may only be called when in a display/input array
.-30136
Unable to create new window
.-30137
Invalid window style type
.-30138
Window already exists (%s)
.-30139
Unable to open file.
.-30140
Bad form file format
.-30141
Form not open
.-30142
Window is not open
.-30143
Unable to open form
.-30144
form not there
.-30145
Must have gotten confused somewhere
.-30146
Dubious form
.-30147
Too few variables for the number of fields
.-30148
Field name not found
.-30149
Bad option - not in the menu
.-30150
Invalid Widget
.-30151
serious bug in widget.c
.-30152
Window not found
.-30153
Not available in TUI mode (show_menu)
.-30154
No menu displayed
.-30155
Invalid menu ID
.-30156
Help message not found
.-30157
Could not read help message
.-30158
Error opening output
.-30159
Unable to locate font
.-30160
Not implemented yet...
.-30161
Unable to open file %s %s
.-30162
Unable to open file.
.-30163
Unable to connect to host
.-30164
Untransmittable data
.-30165
Call failed
.-30166
Unprintable datatype
.-30167
serious bug in rpc_server.c
.-30168
Function not registered
.-30169
unable to free arguments
.-30170
cannot create udp service.
.-30171
unable to register (FGL_RPC, FGL_RPC_VER, udp).
.-30172
cannot create tcp service.
.-30173
unable to register (FGL_RPC, FGL_RPC_VER, tcp).
.-30174
Function Already registered
.-30175
RPC server failed
.-30176
Unable to send asynchronous reply!
.-30177
XMLRPC Error
.-30178
Can't Handle Base64 Data
.-30179
Can't Handle Complex Data
.-30180
Can't Handle Pointers
.-30181
Got a 0xDEAD
.-30182
UNKNOWN XML TYPE
.-30183
Internal error - couldn't create error window
.-30184
No current option
.-30185
Internal error - negative messageline
.-30186
Not available in TUI mode (enable/disable)
.-30187
Internal error - no change in state
.-30188
Field not found
.-30189
Input form is not current
.-30190
Internal error - no change in state..
.-30191
Unable to create field
.-30192
Internal Error
.-30193
Failed to create the loaded the form
.-30194
No form
.-30195
No active field
.-30196
Field subscript out of bounds
.-30197
after field : field number not found!
.-30198
before field : field number not found!
.-30199
Format is wider than the field
.-30200
No current form
.-30201
Field name not found on form
.-30202
Form driver complaint
.-30203
Not implemented for TUI mode
.-30204
No valid metric....
.-30205
Field is not currently being input
.-30206
field_touched called with no fields...
.-30207
Couldnt create window
.-30208
No spare windows left...
.-30209
Window is too small to display this form (too high)
.-30210
Window is too small to display this form (too wide)
.-30211
Window is too small to display this form
.-30212
Unable to create form
.-30213
NOCURSES Mode has been specified - operation not permitted
.-30214
Error displaying form in window
.-30215
The form has not been opened
.-30216
Panel not found....
.-30217
Window to move was not found
.-30218
Couldnt move window
