
/* RULE 1: keep this table in sorted order. A binary search is used.
 * RULE 2: the constants have been originally extracted from SCO
 * which seems to have a glut of constants. My advice if a certain
 * constant is not available on *your* platform: strike it out!
 * Let me know; I'll look it up in SCO and probably agree with you.
 *
 * In practice, please put a suitable #if ! defined(*yourplatform*)
 * around the dodgy constant as the first stage of it's retirement.
 * Discuss it with the interested group for confirmation and then
 * we'll shoot it down.
 */

    { "E2BIG",                  E2BIG },
    { "EACCES",                 EACCES },
    { "EADDRINUSE",             EADDRINUSE },
    { "EADDRNOTAVAIL",          EADDRNOTAVAIL },
    { "EAFNOSUPPORT",           EAFNOSUPPORT },
    { "EAGAIN",                 EAGAIN },
    { "EALREADY",               EALREADY },
    { "EBADF",                  EBADF },
    { "EBADMSG",                EBADMSG },
    { "EBUSY",                  EBUSY },
    { "ECHILD",                 ECHILD },
    { "ECONNABORTED",           ECONNABORTED },
    { "ECONNREFUSED",           ECONNREFUSED },
    { "ECONNRESET",             ECONNRESET },
    { "EDEADLK",                EDEADLK },
    { "EDESTADDRREQ",           EDESTADDRREQ },
    { "EDOM",                   EDOM },
    { "EDQUOT",                 EDQUOT },
    { "EEXIST",                 EEXIST },
    { "EFAULT",                 EFAULT },
    { "EFBIG",                  EFBIG },
    { "EHOSTDOWN",              EHOSTDOWN },
    { "EHOSTUNREACH",           EHOSTUNREACH },
    { "EIDRM",                  EIDRM },
    { "EILSEQ",                 EILSEQ },
    { "EINPROGRESS",            EINPROGRESS },
    { "EINTR",                  EINTR },
    { "EINVAL",                 EINVAL },
    { "EIO",                    EIO },
    { "EISCONN",                EISCONN },
    { "EISDIR",                 EISDIR },
    { "ELOOP",                  ELOOP },
    { "EMFILE",                 EMFILE },
    { "EMLINK",                 EMLINK },
    { "EMSGSIZE",               EMSGSIZE },
    { "ENAMETOOLONG",           ENAMETOOLONG },
    { "ENETDOWN",               ENETDOWN },
    { "ENETRESET",              ENETRESET },
    { "ENETUNREACH",            ENETUNREACH },
    { "ENFILE",                 ENFILE },
    { "ENOBUFS",                ENOBUFS },
    { "ENODATA",                ENODATA },
    { "ENODEV",                 ENODEV },
    { "ENOENT",                 ENOENT },
    { "ENOEXEC",                ENOEXEC },
    { "ENOLCK",                 ENOLCK },
    { "ENOMEM",                 ENOMEM },
    { "ENOMSG",                 ENOMSG },
    { "ENOPKG",                 ENOPKG },
    { "ENOPROTOOPT",            ENOPROTOOPT },
    { "ENOSPC",                 ENOSPC },
    { "ENOSR",                  ENOSR },
    { "ENOSTR",                 ENOSTR },
    { "ENOSYS",                 ENOSYS },
    { "ENOTBLK",                ENOTBLK },
    { "ENOTCONN",               ENOTCONN },
    { "ENOTDIR",                ENOTDIR },
    { "ENOTEMPTY",              ENOTEMPTY },
    { "ENOTSOCK",               ENOTSOCK },
    { "ENOTTY",                 ENOTTY },
    { "ENXIO",                  ENXIO },
    { "EOPNOTSUPP",             EOPNOTSUPP },
    { "EPERM",                  EPERM },
    { "EPFNOSUPPORT",           EPFNOSUPPORT },
    { "EPIPE",                  EPIPE },
    { "EPROTO",                 EPROTO },
    { "EPROTONOSUPPORT",        EPROTONOSUPPORT },
    { "EPROTOTYPE",             EPROTOTYPE },
    { "ERANGE",                 ERANGE },
    { "EREMOTE",                EREMOTE },
    { "EROFS",                  EROFS },
    { "ESHUTDOWN",              ESHUTDOWN },
    { "ESOCKTNOSUPPORT",        ESOCKTNOSUPPORT },
    { "ESPIPE",                 ESPIPE },
    { "ESRCH",                  ESRCH },
    { "ESTALE",                 ESTALE },
    { "ETIME",                  ETIME },
    { "ETIMEDOUT",              ETIMEDOUT },
    { "ETOOMANYREFS",           ETOOMANYREFS },
    { "ETXTBSY",                ETXTBSY },
    { "EWOULDBLOCK",            EWOULDBLOCK },
    { "EXDEV",                  EXDEV },

