
/**
 * @file
 * Generate the fgldoc in static html for this module.
 * This action is also made by the manager (fgldoc Perl script)
 * but implies the existance of information in the repository.
 *
 * Invoked with --document p4gl switch
 *
 * Note - incomplete - use "fgldoc --action=export2Html"
 *
 */

#include <stdio.h>
#include <ctype.h>
#include <unistd.h>
#include <varargs.h>
#include "p4gl_symtab.h"

FILE *o;

/* Preparação para multi-idioma */
char *methodSummary = "Sumário dos métodos";
char *methodDetail  = "Detalhe dos métodos";

/** 
 *  Open the file where the information should be writed.
 */
static void openModuleDocFile(void)
{
	char *baseModName = (char *)fileWithoutExtension(P4glCb.module);
  P4glCb.docFileName = (char *)malloc(
	  strlen(P4glCb.docFileDir)+2+strlen(baseModName)+5
  );
	strcpy(P4glCb.docFileName,P4glCb.docFileDir);
	strcat(P4glCb.docFileName,"/");
	strcat(P4glCb.docFileName,baseModName);
	strcat(P4glCb.docFileName,".html");
	P4glCb.docFilePtr = fopen(P4glCb.docFileName,"w");
  o = P4glCb.docFilePtr;
}


/**
 * Writes the trailer documentation for the module.
 */
static void writeModuleDocTrailer(void)
{
}

/**
 * Closes the file
 */
static void closeModuleDocFile(void)
{
  fclose(o);
}

/**
 * Print the header of the html.
 */
static void printHeader(void)
{
  fprintf(o,"<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.0 Frameset//EN''");
	fprintf(o,"http://www.w3.org/tr/rec-html40/frameset.dtd'>\n");

  fprintf(o,"<HTML>\n");
  fprintf(o,"<HEAD>\n");

	/* TODO - ??? Data de geração devia ser automática */
  fprintf(o,"<!-- Generated by javadoc on ");
	fprintf(o,"Sun Mar 04 20:35:32 GMT 2001 -->\n");
  fprintf(o,"<TITLE>\n");

	/* TODO - ??? Devia ser multiidioma */
  fprintf(o,": Module  %s\n");
  fprintf(o,"</TITLE>\n");
  fprintf(o,"<LINK REL ='stylesheet' TYPE='text/css' ");

	/* TODO - Tem, de se resolver o href pelo nome do package */
	fprintf(o,"HREF='../../../stylesheet.css' TITLE='Style'>\n");
  fprintf(o,"</HEAD>\n");
  fprintf(o,"<BODY BGCOLOR='white'>\n");
}

/**
 * Prints the navigation bar with menu for the diferent actions.
 */
static void printHeaderNavbar(void)
{
  fprintf(o,"<!-- ========== START OF NAVBAR ========== -->\n");
  fprintf(o,"<A NAME='navbar_top'><!-- --></A>\n");
  fprintf(o,"<TABLE BORDER='0' WIDTH='100%' ");
	fprintf(o,"CELLPADDING='1' CELLSPACING='0'>\n");
  fprintf(o,"<TR>\n");
  fprintf(o,"<TD COLSPAN=2 BGCOLOR='#EEEEFF' CLASS='NavBarCell1'>\n");
  fprintf(o,"<A NAME='navbar_top_firstrow'><!-- --></A>\n");

  fprintf(o,"<TABLE BORDER='0' CELLPADDING='0' CELLSPACING='3'>\n");
  fprintf(o,"<TR ALIGN='center' VALIGN='top'>\n");
  fprintf(o,"<TD BGCOLOR='#EEEEFF' CLASS='NavBarCell1'>    ");
	fprintf(o,"<A HREF='../../../overview-summary.html'>");
	fprintf(o,"<FONT CLASS='NavBarFont1'><B>Overview</B></FONT></A>");
	fprintf(o,"&nbsp;</TD>\n");
  fprintf(o,"<TD BGCOLOR='#EEEEFF' CLASS='NavBarCell1'>    ");
	fprintf(o,"<A HREF='package-summary.html'><FONT CLASS='NavBarFont1'>");
	fprintf(o,"<B>Package</B></FONT></A>&nbsp;</TD>\n");
  fprintf(o,"<TD BGCOLOR='#FFFFFF' CLASS='NavBarCell1Rev'> &nbsp;");
  fprintf(o,"<FONT CLASS='NavBarFont1Rev'><B>Class</B></FONT>&nbsp;</TD>\n");
  fprintf(o,"<TD BGCOLOR='#EEEEFF' CLASS='NavBarCell1'>    ");
	fprintf(o,"<A HREF='package-tree.html'><FONT CLASS='NavBarFont1'>");
	fprintf(o,"<B>Tree</B></FONT></A>&nbsp;</TD>\n");
  fprintf(o,"<TD BGCOLOR='#EEEEFF' CLASS='NavBarCell1'>    ");
	fprintf(o,"<A HREF='../../../deprecated-list.html'>");
	fprintf(o,"<FONT CLASS='NavBarFont1'><B>Deprecated</B></FONT>");
	fprintf(o,"</A>&nbsp;</TD>\n");
  fprintf(o,"<TD BGCOLOR='#EEEEFF' CLASS='NavBarCell1'>    ");
	fprintf(o,"<A HREF='../../../index-all.html'>");
	fprintf(o,"<FONT CLASS='NavBarFont1'><B>Index</B></FONT></A>&nbsp;</TD>\n");
  fprintf(o,"<TD BGCOLOR='#EEEEFF' CLASS='NavBarCell1'>    ");
	fprintf(o,"<A HREF='../../../help-doc.html'>");
	fprintf(o,"<FONT CLASS='NavBarFont1'><B>Help</B></FONT></A>&nbsp;</TD>\n");
  fprintf(o,"</TR>\n");
  fprintf(o,"</TABLE>\n");
  fprintf(o,"</TD>\n");
  fprintf(o,"<TD ALIGN='right' VALIGN='top' ROWSPAN=3><EM>\n");
  fprintf(o,"</EM>\n");
  fprintf(o,"</TD>\n");
  fprintf(o,"</TR>\n");

  fprintf(o,"<TR>\n");
  fprintf(o,"<TD BGCOLOR='white' CLASS='NavBarCell2'><FONT SIZE='-2'>\n");
  fprintf(o,"&nbsp;PREV CLASS&nbsp;\n");
  fprintf(o,"&nbsp;NEXT CLASS</FONT></TD>\n");
  fprintf(o,"<TD BGCOLOR='white' CLASS='NavBarCell2'><FONT SIZE='-2'>\n");
  fprintf(o,"<A HREF='../../../index.html' TARGET='_top'><B>FRAMES</B>");
	fprintf(o,"</A>  &nbsp;\n");
  fprintf(o,"&nbsp;<A HREF='Exp.html' TARGET='_top'><B>NO FRAMES</B>");
	fprintf(o,"</A></FONT></TD>\n");
  fprintf(o,"</TR>\n");
  fprintf(o,"<TR>\n");
  fprintf(o,"<TD VALIGN='top' CLASS='NavBarCell3'><FONT SIZE='-2'>\n");
  fprintf(o,"SUMMARY: &nbsp;INNER&nbsp;|&nbsp;FIELD&nbsp;|&nbsp;");
	fprintf(o,"<A HREF='#constructor_summary'>CONSTR</A>&nbsp;|&nbsp;");
	fprintf(o,"<A HREF='#method_summary'>METHOD</A></FONT></TD>\n");
  fprintf(o,"<TD VALIGN='top' CLASS='NavBarCell3'><FONT SIZE='-2'>\n");
  fprintf(o,"DETAIL: &nbsp;FIELD&nbsp;|&nbsp;");
	fprintf(o,"<A HREF='#constructor_detail'>CONSTR</A>&nbsp;|&nbsp;");
	fprintf(o,"<A HREF='#method_detail'>METHOD</A></FONT></TD>\n");
  fprintf(o,"</TR>\n");
  fprintf(o,"</TABLE>\n");
  fprintf(o,"<!-- =========== END OF NAVBAR =========== -->\n");
}

/**
 * Prints the header of module documentation.
 */
static void printHeaderModuleData(void)
{
  fprintf(o,"<!-- ======== START OF CLASS DATA ======== -->");
  fprintf(o,"<H2>Module  %s</H2>\n",P4glCb.module);
  fprintf(o,"<HR>\n");

  fprintf(o,"<P>\n");
  fprintf(o,"Experiência de javadoc\n");
   fprintf(o,"<BR> A classe exp serve para ver o que isto gera com o objectivo\n");
   fprintf(o,"de fazer a mesma coisa para o fgldoc\n");
  fprintf(o,"<P>\n");
  fprintf(o,"<HR>\n");

  fprintf(o,"<P>\n");
}

/**
 * Print the modular variable summary
 */
static void printFieldSummary(void)
{
  /* TODO - Variáveis do módulo */
  fprintf(o,"<!-- =========== FIELD SUMMARY =========== -->\n");
}

/**
 * Prints the function summary table
 */
static void printMethodSummaryHeader(void)
{
  fprintf(o,"&nbsp;\n");
  fprintf(o,"<!-- ========== METHOD SUMMARY =========== -->\n");

  fprintf(o,"<A NAME='method_summary'><!-- --></A>\n");
  fprintf(o,"<TABLE BORDER='1' CELLPADDING='3' CELLSPACING='0' ");
	fprintf(o,"WIDTH='100%'>\n");
  fprintf(o,"<TR BGCOLOR='#CCCCFF' CLASS='TableHeadingColor'>\n");
  fprintf(o,"<TD COLSPAN=2><FONT SIZE='+2'>\n");
  fprintf(o,"<B>%s</B></FONT></TD>\n",methodSummary);
  fprintf(o,"</TR>\n");


}

/**
 * Prints the function summary description
 *
 * @param idxFunction The function index
 */
static void printMethodSummaryBody(int idxFunction)
{
  char *functionName;
	char *comments;

  functionName = FUNCAO(idxFunction).name;
	comments     = FUNCAO(idxFunction).parsedDoc->buffer;

  fprintf(o,"<TR BGCOLOR='white' CLASS='TableRowColor'>\n");
  fprintf(o,"<TD ALIGN='right' VALIGN='top' WIDTH='1%'>");
	fprintf(o,"<FONT SIZE='-1'>\n");
  fprintf(o,"<CODE>&nbsp;</CODE></FONT></TD>\n");
  fprintf(o,"<TD><CODE><B>");

	/* TODO - Resolver a referência */
	fprintf(o,"<A HREF='#%s()'>%s()</A></B>",functionName,functionName);

	/* TODO - Parametros do método */
	fprintf(o,"</CODE>\n");

  fprintf(o,"<BR>\n");
  fprintf(o,"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
	fprintf(o,"%s</TD>\n",comments);
  fprintf(o,"</TR>\n");
}

printMethodSummaryTrailer()
{
  fprintf(o,"</TABLE>\n");
}

/**
 * Write the summary with the links to the detail information.
 */
static void printMethodsSummary(void)
{
  register int i;

  printMethodSummaryHeader();
	/* TODO - Tem de saber quantos métodos existem */
  for ( i = 0 ; i < P4glCb.idx_funcoes ; i++ )
    printMethodSummaryBody(i);
  printMethodSummaryTrailer();
}

/* TODO - Obter javadoc para variáveis */
printFieldDetail()
{
  fprintf(o,"<!-- ============ FIELD DETAIL =========== -->\n");
}

/**
 * Escreve a documentação de uma método
 */
static void printMethodsDetail(void)
{
  register int i;

  printMethodDetailHeader();
	/* TODO - Tem de saber quantos métodos existem */

  for ( i = 0 ; i < P4glCb.idx_funcoes ; i++ )
    printMethodDetailBody(i);
  printMethodDetailTrailer();
}


printMethodDetailHeader()
{
  fprintf(o,"<!-- ============ METHOD DETAIL ========== -->\n");

  fprintf(o,"<A NAME='method_detail'><!-- --></A>\n");
  fprintf(o,"<TABLE BORDER='1' CELLPADDING='3' CELLSPACING='0' WIDTH='100%'>\n");
  fprintf(o,"<TR BGCOLOR='#CCCCFF' CLASS='TableHeadingColor'>\n");
  fprintf(o,"<TD COLSPAN=1><FONT SIZE='+2'>\n");
  fprintf(o,"<B>%s</B></FONT></TD>\n",methodDetail);
  fprintf(o,"</TR>\n");
  fprintf(o,"</TABLE>\n");
}


/**
 * Preenche os dados relativos ao detalhe de cada método 
 * @param idxFunction Indice da função na tabela de simbolos
 */
printMethodDetailBody(int idxFunction)
{
  char *functionName;
	char *comments;

  functionName = FUNCAO(idxFunction).name;
	comments     = FUNCAO(idxFunction).parsedDoc->buffer;

  fprintf(o,"<A NAME='%s()'><!-- --></A><H3>\n",functionName);
  fprintf(o,"%s</H3>\n",functionName);

	/* TODO - Parametros */
  /*fprintf(o,"<PRE><B>%s</B>()</PRE>\n",functionName); */

  fprintf(o,"<DL>\n"); 
  fprintf(o,"<DD>%s</DD>\n",comments); 
  /* fprintf(o,"<DD>%s<DD><DL>\n",comments); */

	/* TODO - Parametros */
	/*
  fprintf(o,"<DT><B>Parameters:</B><DD>");
	fprintf(o,"<CODE>x</CODE> - Coordenada Z");
	fprintf(o,"<DD><CODE>y</CODE> - Nome da coordenada Y");
	fprintf(o,"<DT><B>Returns:</B><DD>Nada</DL>\n");
  fprintf(o,"</DD>\n");
	*/
  fprintf(o,"</DL>\n"); 

}

printMethodDetailTrailer()
{
  fprintf(o,"<!-- ========= END OF CLASS DATA ========= -->\n");
  fprintf(o,"<HR>\n");
}

/**
 * Este método ainda pode ser partido aos bocados
 */
printDocTrailer()
{
  fprintf(o,"<!-- ========== START OF NAVBAR ========== -->\n");
  fprintf(o,"<A NAME='navbar_bottom'><!-- --></A>\n");
  fprintf(o,"<TABLE BORDER='0' WIDTH='100%%' CELLPADDING='1' CELLSPACING='0'>\n");
  fprintf(o,"<TR>\n");
  fprintf(o,"<TD COLSPAN=2 BGCOLOR='#EEEEFF' CLASS='NavBarCell1'>\n");
  fprintf(o,"<A NAME='navbar_bottom_firstrow'><!-- --></A>\n");
  fprintf(o,"<TABLE BORDER='0' CELLPADDING='0' CELLSPACING='3'>\n");
  fprintf(o,"<TR ALIGN='center' VALIGN='top'>\n");
  fprintf(o,"<TD BGCOLOR='#EEEEFF' CLASS='NavBarCell1'>    ");
	fprintf(o,"<A HREF='../../../overview-summary.html'>");
	fprintf(o,"<FONT CLASS='NavBarFont1'><B>Overview</B></FONT></A>&nbsp;</TD>\n");
  fprintf(o,"<TD BGCOLOR='#EEEEFF' CLASS='NavBarCell1'>    ");
	fprintf(o,"<A HREF='package-summary.html'><FONT CLASS='NavBarFont1'>");
	fprintf(o,"<B>Package</B></FONT></A>&nbsp;</TD>\n");
  fprintf(o,"<TD BGCOLOR='#FFFFFF' CLASS='NavBarCell1Rev'> &nbsp;");
	fprintf(o,"<FONT CLASS='NavBarFont1Rev'><B>Class</B></FONT>&nbsp;</TD>\n");
  fprintf(o,"<TD BGCOLOR='#EEEEFF' CLASS='NavBarCell1'>    <A HREF='package-tree.html'><FONT CLASS='NavBarFont1'><B>Tree</B></FONT></A>&nbsp;</TD>\n");
  fprintf(o,"<TD BGCOLOR='#EEEEFF' CLASS='NavBarCell1'>    ");
	fprintf(o,"<A HREF='../../../deprecated-list.html'><FONT CLASS='NavBarFont1'><B>Deprecated</B></FONT></A>&nbsp;</TD>\n");
  fprintf(o,"<TD BGCOLOR='#EEEEFF' CLASS='NavBarCell1'>    ");
	fprintf(o,"<A HREF='../../../index-all.html'>");
	fprintf(o,"<FONT CLASS='NavBarFont1'><B>Index</B></FONT></A>&nbsp;</TD>\n");
  fprintf(o,"<TD BGCOLOR='#EEEEFF' CLASS='NavBarCell1'>    ");
	fprintf(o,"<A HREF='../../../help-doc.html'>");
	fprintf(o,"<FONT CLASS='NavBarFont1'><B>Help</B></FONT></A>&nbsp;</TD>\n");
  fprintf(o,"</TR>\n");
  fprintf(o,"</TABLE>\n");
  fprintf(o,"</TD>\n");
  fprintf(o,"<TD ALIGN='right' VALIGN='top' ROWSPAN=3><EM>\n");
  fprintf(o,"</EM>\n");
  fprintf(o,"</TD>\n");
  fprintf(o,"</TR>\n");

  fprintf(o,"<TR>\n");
  fprintf(o,"<TD BGCOLOR='white' CLASS='NavBarCell2'><FONT SIZE='-2'>\n");
  fprintf(o,"&nbsp;PREV CLASS&nbsp;\n");
  fprintf(o,"&nbsp;NEXT CLASS</FONT></TD>\n");
  fprintf(o,"<TD BGCOLOR='white' CLASS='NavBarCell2'><FONT SIZE='-2'>\n");
  fprintf(o,"<A HREF='../../../index.html' TARGET='_top'>");
	fprintf(o,"<B>FRAMES</B></A>  &nbsp;\n");
  fprintf(o,"&nbsp;<A HREF='Exp.html' TARGET='_top'>");
	fprintf(o,"<B>NO FRAMES</B></A></FONT></TD>\n");
  fprintf(o,"</TR>\n");
  fprintf(o,"<TR>\n");
  fprintf(o,"<TD VALIGN='top' CLASS='NavBarCell3'><FONT SIZE='-2'>\n");
  fprintf(o,"SUMMARY: &nbsp;INNER&nbsp;|&nbsp;FIELD&nbsp;|&nbsp;");
	fprintf(o,"<A HREF='#constructor_summary'>CONSTR</A>&nbsp;|&nbsp;");
	fprintf(o,"<A HREF='#method_summary'>METHOD</A></FONT></TD>\n");
  fprintf(o,"<TD VALIGN='top' CLASS='NavBarCell3'><FONT SIZE='-2'>\n");
  fprintf(o,"DETAIL: &nbsp;FIELD&nbsp;|&nbsp;");
	fprintf(o,"<A HREF='#constructor_detail'>CONSTR</A>&nbsp;|&nbsp;");
	fprintf(o,"<A HREF='#method_detail'>METHOD</A></FONT></TD>\n");
  fprintf(o,"</TR>\n");
  fprintf(o,"</TABLE>\n");
  fprintf(o,"<!-- =========== END OF NAVBAR =========== -->\n");

  fprintf(o,"<HR>\n");

  fprintf(o,"</BODY>\n");
  fprintf(o,"</HTML>\n");
}

/**
 * Gera um ficheiro que contem a lista de metodos descoberto pelo p4gl
 * TODO - Nome de jeito para a lista de métodos
 */
genMethodList()
{
  FILE *mo;
	char *functionName;
	char *comments;
	register int i;

	mo = fopen("/tmp/method.list","w");
	if ( mo == (FILE *)0 )
	  printf("Impossivel abrir ficheiro %s\n","/tmp/method.list");
  for ( i = 0 ; i < P4glCb.idx_funcoes ; i++ )
  {
    functionName = FUNCAO(i).name;
	  comments     = FUNCAO(i).parsedDoc->buffer;
		fprintf(mo,"%s\n",functionName);
  }
  fclose(mo);
}

/**
 * Writes de documentation html header.
 */
static void printDocHeader(void)
{
  printHeader();
  fprintf(o,"<HR>\n");
  printHeaderNavbar();
	printHeaderModuleData();
}


/**
 * Generate the html web page corresponding to the fgldoc of current module.
 */
void genFglDoc(void)
{
  openModuleDocFile();
	printDocHeader();
	printFieldSummary();
	printMethodsSummary();
	printMethodsDetail();
	printFieldDetail();
	printDocTrailer();
  closeModuleDocFile();

	genMethodList();
}

