

fgldrawbox.4ae: fgldrawbox.4gl
	${FGLC} fgldrawbox.4gl -o fgldrawbox.4ae

compile: fgldrawbox.4ae
	
run: fgldrawbox.4ae
	sh ./run_fgldrawbox



ansi_sql_compat:
	@echo "1"

desc:
	@echo "testing fgl_drawbox"

sql_features_used:		; @echo "DATABASE_USED DEFINE_LIKE DDL_DECIMAL DDL_DATE DDL_MONEY DDL_DATETIME CREATE_TEMP_TABLE ANSI_INSERT ANSI_DELETE DROP_TABLE DEFINE_CHAR DEFINE_SMALLINT DEFINE_INTEGER DEFINE_FLOAT DEFINE_DECIMAL DEFINE_DATE DEFINE_MONEY DEFINE_DATETIME STATUS IF UI_DISPLAY_LINE_MODE DISPLAY "

