.100
 NOT_FOUND          100
.-239
duplicate key violates unique constraint
.-349
Not connected to a database
.-284
Subquery has returned not exactly one row
.-255
Not in a transaction
.-201
Syntax error
.-206
Table is not in the database
.-310
Table already exists
.301
 PGTYPES_NUM_OVERFLOW            301
.302
 PGTYPES_NUM_BAD_NUMERIC         302
.303
 PGTYPES_NUM_DIVIDE_ZERO         303
.310
 PGTYPES_DATE_BAD_DATE           310
.311
 PGTYPES_DATE_ERR_EARGS          311
.312
 PGTYPES_DATE_ERR_ENOSHORTDATE   312
.313
 PGTYPES_DATE_ERR_ENOTDMY        313
.314
 PGTYPES_DATE_BAD_DAY            314
.315
 PGTYPES_DATE_BAD_MONTH          315
.320
 PGTYPES_TS_BAD_TIMESTAMP        320
.321
 PGTYPES_TS_ERR_EINFTIME         321
.330
 PGTYPES_INTVL_BAD_INTERVAL      330
