DATABASE test1

MAIN
	WHENEVER ERROR CONTINUE
	DROP TABLE a_table
	WHENEVER ERROR STOP
  CREATE TABLE a_table (
	  a_column INTEGER NOT NULL UNIQUE,
	  another_col INTEGER NOT NULL DISTINCT
	)
	DROP TABLE a_table
END MAIN
