/* soapStub.h
   Generated by gSOAP 2.8.1 from outfile.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"http://futureware.biz/mantisconnect"
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (12)
/* xsd:boolean */
enum xsd__boolean {xsd__boolean__false_ = 0, xsd__boolean__true_ = 1};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (8)
/* Base64 schema type: */
struct xsd__base64Binary
{
	unsigned char *__ptr;
	int __size;
	char *id;	/* optional element of type xsd:string */
	char *type;	/* optional element of type xsd:string */
	char *options;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__ObjectRef
#define SOAP_TYPE_ns1__ObjectRef (15)
/* ns1:ObjectRef */
struct ns1__ObjectRef
{
	char *id;	/* optional element of type xsd:integer */
	char *name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__AccountData
#define SOAP_TYPE_ns1__AccountData (16)
/* ns1:AccountData */
struct ns1__AccountData
{
	char *id;	/* optional element of type xsd:integer */
	char *name;	/* optional element of type xsd:string */
	char *real_USCOREname;	/* optional element of type xsd:string */
	char *email;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__AttachmentData
#define SOAP_TYPE_ns1__AttachmentData (17)
/* ns1:AttachmentData */
struct ns1__AttachmentData
{
	char *id;	/* optional element of type xsd:integer */
	char *filename;	/* optional element of type xsd:string */
	char *size;	/* optional element of type xsd:integer */
	char *content_USCOREtype;	/* optional element of type xsd:string */
	time_t *date_USCOREsubmitted;	/* optional element of type xsd:dateTime */
	char *download_USCOREurl;	/* optional element of type xsd:anyURI */
};
#endif

#ifndef SOAP_TYPE_ns1__ProjectAttachmentData
#define SOAP_TYPE_ns1__ProjectAttachmentData (20)
/* ns1:ProjectAttachmentData */
struct ns1__ProjectAttachmentData
{
	char *id;	/* optional element of type xsd:integer */
	char *filename;	/* optional element of type xsd:string */
	char *title;	/* optional element of type xsd:string */
	char *description;	/* optional element of type xsd:string */
	char *size;	/* optional element of type xsd:integer */
	char *content_USCOREtype;	/* optional element of type xsd:string */
	time_t *date_USCOREsubmitted;	/* optional element of type xsd:dateTime */
	char *download_USCOREurl;	/* optional element of type xsd:anyURI */
};
#endif

#ifndef SOAP_TYPE_ns1__RelationshipData
#define SOAP_TYPE_ns1__RelationshipData (21)
/* ns1:RelationshipData */
struct ns1__RelationshipData
{
	char *id;	/* optional element of type xsd:integer */
	struct ns1__ObjectRef *type;	/* optional element of type ns1:ObjectRef */
	char *target_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__IssueNoteData
#define SOAP_TYPE_ns1__IssueNoteData (23)
/* ns1:IssueNoteData */
struct ns1__IssueNoteData
{
	char *id;	/* optional element of type xsd:integer */
	struct ns1__AccountData *reporter;	/* optional element of type ns1:AccountData */
	char *text;	/* optional element of type xsd:string */
	struct ns1__ObjectRef *view_USCOREstate;	/* optional element of type ns1:ObjectRef */
	time_t *date_USCOREsubmitted;	/* optional element of type xsd:dateTime */
	time_t *last_USCOREmodified;	/* optional element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE_ns1__IssueData
#define SOAP_TYPE_ns1__IssueData (25)
/* ns1:IssueData */
struct ns1__IssueData
{
	char *id;	/* optional element of type xsd:integer */
	struct ns1__ObjectRef *view_USCOREstate;	/* optional element of type ns1:ObjectRef */
	time_t *last_USCOREupdated;	/* optional element of type xsd:dateTime */
	struct ns1__ObjectRef *project;	/* optional element of type ns1:ObjectRef */
	char *category;	/* optional element of type xsd:string */
	struct ns1__ObjectRef *priority;	/* optional element of type ns1:ObjectRef */
	struct ns1__ObjectRef *severity;	/* optional element of type ns1:ObjectRef */
	struct ns1__ObjectRef *status;	/* optional element of type ns1:ObjectRef */
	struct ns1__AccountData *reporter;	/* optional element of type ns1:AccountData */
	char *summary;	/* optional element of type xsd:string */
	char *version;	/* optional element of type xsd:string */
	char *build;	/* optional element of type xsd:string */
	char *platform;	/* optional element of type xsd:string */
	char *os;	/* optional element of type xsd:string */
	char *os_USCOREbuild;	/* optional element of type xsd:string */
	struct ns1__ObjectRef *reproducibility;	/* optional element of type ns1:ObjectRef */
	time_t *date_USCOREsubmitted;	/* optional element of type xsd:dateTime */
	char *sponsorship_USCOREtotal;	/* optional element of type xsd:integer */
	struct ns1__AccountData *handler;	/* optional element of type ns1:AccountData */
	struct ns1__ObjectRef *projection;	/* optional element of type ns1:ObjectRef */
	struct ns1__ObjectRef *eta;	/* optional element of type ns1:ObjectRef */
	struct ns1__ObjectRef *resolution;	/* optional element of type ns1:ObjectRef */
	char *fixed_USCOREin_USCOREversion;	/* optional element of type xsd:string */
	char *description;	/* optional element of type xsd:string */
	char *steps_USCOREto_USCOREreproduce;	/* optional element of type xsd:string */
	char *additional_USCOREinformation;	/* optional element of type xsd:string */
	struct AttachmentDataArray *attachments;	/* optional element of type ArrayOfAttachmentData */
	struct RelationshipDataArray *relationships;	/* optional element of type ArrayOfRelationshipData */
	struct IssueNoteDataArray *notes;	/* optional element of type ArrayOfIssueNoteData */
	struct CustomFieldValueForIssueDataArray *custom_USCOREfields;	/* optional element of type ArrayOfCustomFieldValueForIssueData */
};
#endif

#ifndef SOAP_TYPE_ns1__IssueHeaderData
#define SOAP_TYPE_ns1__IssueHeaderData (34)
/* ns1:IssueHeaderData */
struct ns1__IssueHeaderData
{
	char *id;	/* required element of type xsd:integer */
	char *view_USCOREstate;	/* required element of type xsd:integer */
	time_t last_USCOREupdated;	/* required element of type xsd:dateTime */
	char *project;	/* required element of type xsd:integer */
	char *category;	/* required element of type xsd:string */
	char *priority;	/* required element of type xsd:integer */
	char *severity;	/* required element of type xsd:integer */
	char *status;	/* required element of type xsd:integer */
	char *reporter;	/* required element of type xsd:integer */
	char *summary;	/* required element of type xsd:string */
	char *handler;	/* required element of type xsd:integer */
	char *resolution;	/* required element of type xsd:integer */
	char *attachments_USCOREcount;	/* required element of type xsd:integer */
	char *notes_USCOREcount;	/* required element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__ProjectData
#define SOAP_TYPE_ns1__ProjectData (35)
/* ns1:ProjectData */
struct ns1__ProjectData
{
	char *id;	/* optional element of type xsd:integer */
	char *name;	/* optional element of type xsd:string */
	struct ns1__ObjectRef *status;	/* optional element of type ns1:ObjectRef */
	enum xsd__boolean *enabled;	/* optional element of type xsd:boolean */
	struct ns1__ObjectRef *view_USCOREstate;	/* optional element of type ns1:ObjectRef */
	struct ns1__ObjectRef *access_USCOREmin;	/* optional element of type ns1:ObjectRef */
	char *file_USCOREpath;	/* optional element of type xsd:string */
	char *description;	/* optional element of type xsd:string */
	struct ProjectDataArray *subprojects;	/* optional element of type ArrayOfProjectData */
};
#endif

#ifndef SOAP_TYPE_ns1__ProjectVersionData
#define SOAP_TYPE_ns1__ProjectVersionData (39)
/* ns1:ProjectVersionData */
struct ns1__ProjectVersionData
{
	char *id;	/* optional element of type xsd:integer */
	char *name;	/* optional element of type xsd:string */
	char *project_USCOREid;	/* optional element of type xsd:integer */
	time_t *date_USCOREorder;	/* optional element of type xsd:dateTime */
	char *description;	/* optional element of type xsd:string */
	enum xsd__boolean *released;	/* optional element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__FilterData
#define SOAP_TYPE_ns1__FilterData (40)
/* ns1:FilterData */
struct ns1__FilterData
{
	char *id;	/* optional element of type xsd:integer */
	struct ns1__AccountData *owner;	/* optional element of type ns1:AccountData */
	char *project_USCOREid;	/* optional element of type xsd:integer */
	enum xsd__boolean *is_USCOREpublic;	/* optional element of type xsd:boolean */
	char *name;	/* optional element of type xsd:string */
	char *filter_USCOREstring;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__CustomFieldDefinitionData
#define SOAP_TYPE_ns1__CustomFieldDefinitionData (41)
/* ns1:CustomFieldDefinitionData */
struct ns1__CustomFieldDefinitionData
{
	struct ns1__ObjectRef *field;	/* optional element of type ns1:ObjectRef */
	char *type;	/* optional element of type xsd:integer */
	char *possible_USCOREvalues;	/* optional element of type xsd:string */
	char *default_USCOREvalue;	/* optional element of type xsd:string */
	char *valid_USCOREregexp;	/* optional element of type xsd:string */
	char *access_USCORElevel_USCOREr;	/* optional element of type xsd:integer */
	char *access_USCORElevel_USCORErw;	/* optional element of type xsd:integer */
	char *length_USCOREmin;	/* optional element of type xsd:integer */
	char *length_USCOREmax;	/* optional element of type xsd:integer */
	enum xsd__boolean *advanced;	/* optional element of type xsd:boolean */
	enum xsd__boolean *display_USCOREreport;	/* optional element of type xsd:boolean */
	enum xsd__boolean *display_USCOREupdate;	/* optional element of type xsd:boolean */
	enum xsd__boolean *display_USCOREresolved;	/* optional element of type xsd:boolean */
	enum xsd__boolean *display_USCOREclosed;	/* optional element of type xsd:boolean */
	enum xsd__boolean *require_USCOREreport;	/* optional element of type xsd:boolean */
	enum xsd__boolean *require_USCOREupdate;	/* optional element of type xsd:boolean */
	enum xsd__boolean *require_USCOREresolved;	/* optional element of type xsd:boolean */
	enum xsd__boolean *require_USCOREclosed;	/* optional element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__CustomFieldLinkForProjectData
#define SOAP_TYPE_ns1__CustomFieldLinkForProjectData (42)
/* ns1:CustomFieldLinkForProjectData */
struct ns1__CustomFieldLinkForProjectData
{
	struct ns1__ObjectRef *field;	/* optional element of type ns1:ObjectRef */
	char *sequence;	/* optional element of type xsd:byte */
};
#endif

#ifndef SOAP_TYPE_ns1__CustomFieldValueForIssueData
#define SOAP_TYPE_ns1__CustomFieldValueForIssueData (44)
/* ns1:CustomFieldValueForIssueData */
struct ns1__CustomFieldValueForIssueData
{
	struct ns1__ObjectRef *field;	/* optional element of type ns1:ObjectRef */
	char *value;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_StringArray
#define SOAP_TYPE_StringArray (45)
/* SOAP encoded array of xsd:string schema type: */
struct StringArray
{
	char **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ObjectRefArray
#define SOAP_TYPE_ObjectRefArray (47)
/* SOAP encoded array of ns1:ObjectRef schema type: */
struct ObjectRefArray
{
	struct ns1__ObjectRef **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_AccountDataArray
#define SOAP_TYPE_AccountDataArray (49)
/* SOAP encoded array of ns1:AccountData schema type: */
struct AccountDataArray
{
	struct ns1__AccountData **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_AttachmentDataArray
#define SOAP_TYPE_AttachmentDataArray (26)
/* SOAP encoded array of ns1:AttachmentData schema type: */
struct AttachmentDataArray
{
	struct ns1__AttachmentData **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ProjectAttachmentDataArray
#define SOAP_TYPE_ProjectAttachmentDataArray (53)
/* SOAP encoded array of ns1:ProjectAttachmentData schema type: */
struct ProjectAttachmentDataArray
{
	struct ns1__ProjectAttachmentData **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_RelationshipDataArray
#define SOAP_TYPE_RelationshipDataArray (28)
/* SOAP encoded array of ns1:RelationshipData schema type: */
struct RelationshipDataArray
{
	struct ns1__RelationshipData **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_IssueNoteDataArray
#define SOAP_TYPE_IssueNoteDataArray (30)
/* SOAP encoded array of ns1:IssueNoteData schema type: */
struct IssueNoteDataArray
{
	struct ns1__IssueNoteData **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_IssueDataArray
#define SOAP_TYPE_IssueDataArray (60)
/* SOAP encoded array of ns1:IssueData schema type: */
struct IssueDataArray
{
	struct ns1__IssueData **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_IssueHeaderDataArray
#define SOAP_TYPE_IssueHeaderDataArray (63)
/* SOAP encoded array of ns1:IssueHeaderData schema type: */
struct IssueHeaderDataArray
{
	struct ns1__IssueHeaderData **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ProjectDataArray
#define SOAP_TYPE_ProjectDataArray (37)
/* SOAP encoded array of ns1:ProjectData schema type: */
struct ProjectDataArray
{
	struct ns1__ProjectData **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ProjectVersionDataArray
#define SOAP_TYPE_ProjectVersionDataArray (68)
/* SOAP encoded array of ns1:ProjectVersionData schema type: */
struct ProjectVersionDataArray
{
	struct ns1__ProjectVersionData **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_FilterDataArray
#define SOAP_TYPE_FilterDataArray (71)
/* SOAP encoded array of ns1:FilterData schema type: */
struct FilterDataArray
{
	struct ns1__FilterData **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_CustomFieldDefinitionDataArray
#define SOAP_TYPE_CustomFieldDefinitionDataArray (74)
/* SOAP encoded array of ns1:CustomFieldDefinitionData schema type: */
struct CustomFieldDefinitionDataArray
{
	struct ns1__CustomFieldDefinitionData **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_CustomFieldLinkForProjectDataArray
#define SOAP_TYPE_CustomFieldLinkForProjectDataArray (77)
/* SOAP encoded array of ns1:CustomFieldLinkForProjectData schema type: */
struct CustomFieldLinkForProjectDataArray
{
	struct ns1__CustomFieldLinkForProjectData **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_CustomFieldValueForIssueDataArray
#define SOAP_TYPE_CustomFieldValueForIssueDataArray (32)
/* SOAP encoded array of ns1:CustomFieldValueForIssueData schema type: */
struct CustomFieldValueForIssueDataArray
{
	struct ns1__CustomFieldValueForIssueData **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREversionResponse
#define SOAP_TYPE_ns1__mc_USCOREversionResponse (83)
/* ns1:mc_versionResponse */
struct ns1__mc_USCOREversionResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREversion
#define SOAP_TYPE_ns1__mc_USCOREversion (84)
/* ns1:mc_version */
struct ns1__mc_USCOREversion
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREstatusResponse
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREstatusResponse (85)
/* ns1:mc_enum_statusResponse */
struct ns1__mc_USCOREenum_USCOREstatusResponse
{
	struct ObjectRefArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfObjectRef */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREstatus
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREstatus (89)
/* ns1:mc_enum_status */
struct ns1__mc_USCOREenum_USCOREstatus
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREprioritiesResponse
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREprioritiesResponse (90)
/* ns1:mc_enum_prioritiesResponse */
struct ns1__mc_USCOREenum_USCOREprioritiesResponse
{
	struct ObjectRefArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfObjectRef */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREpriorities
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREpriorities (93)
/* ns1:mc_enum_priorities */
struct ns1__mc_USCOREenum_USCOREpriorities
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREseveritiesResponse
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREseveritiesResponse (94)
/* ns1:mc_enum_severitiesResponse */
struct ns1__mc_USCOREenum_USCOREseveritiesResponse
{
	struct ObjectRefArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfObjectRef */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREseverities
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREseverities (97)
/* ns1:mc_enum_severities */
struct ns1__mc_USCOREenum_USCOREseverities
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREreproducibilitiesResponse
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREreproducibilitiesResponse (98)
/* ns1:mc_enum_reproducibilitiesResponse */
struct ns1__mc_USCOREenum_USCOREreproducibilitiesResponse
{
	struct ObjectRefArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfObjectRef */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREreproducibilities
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREreproducibilities (101)
/* ns1:mc_enum_reproducibilities */
struct ns1__mc_USCOREenum_USCOREreproducibilities
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREprojectionsResponse
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREprojectionsResponse (102)
/* ns1:mc_enum_projectionsResponse */
struct ns1__mc_USCOREenum_USCOREprojectionsResponse
{
	struct ObjectRefArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfObjectRef */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREprojections
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREprojections (105)
/* ns1:mc_enum_projections */
struct ns1__mc_USCOREenum_USCOREprojections
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREetasResponse
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREetasResponse (106)
/* ns1:mc_enum_etasResponse */
struct ns1__mc_USCOREenum_USCOREetasResponse
{
	struct ObjectRefArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfObjectRef */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREetas
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREetas (109)
/* ns1:mc_enum_etas */
struct ns1__mc_USCOREenum_USCOREetas
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREresolutionsResponse
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREresolutionsResponse (110)
/* ns1:mc_enum_resolutionsResponse */
struct ns1__mc_USCOREenum_USCOREresolutionsResponse
{
	struct ObjectRefArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfObjectRef */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREresolutions
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREresolutions (113)
/* ns1:mc_enum_resolutions */
struct ns1__mc_USCOREenum_USCOREresolutions
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREaccess_USCORElevelsResponse
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREaccess_USCORElevelsResponse (114)
/* ns1:mc_enum_access_levelsResponse */
struct ns1__mc_USCOREenum_USCOREaccess_USCORElevelsResponse
{
	struct ObjectRefArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfObjectRef */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREaccess_USCORElevels
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREaccess_USCORElevels (117)
/* ns1:mc_enum_access_levels */
struct ns1__mc_USCOREenum_USCOREaccess_USCORElevels
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREproject_USCOREstatusResponse
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREproject_USCOREstatusResponse (118)
/* ns1:mc_enum_project_statusResponse */
struct ns1__mc_USCOREenum_USCOREproject_USCOREstatusResponse
{
	struct ObjectRefArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfObjectRef */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREproject_USCOREstatus
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREproject_USCOREstatus (121)
/* ns1:mc_enum_project_status */
struct ns1__mc_USCOREenum_USCOREproject_USCOREstatus
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREproject_USCOREview_USCOREstatesResponse
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREproject_USCOREview_USCOREstatesResponse (122)
/* ns1:mc_enum_project_view_statesResponse */
struct ns1__mc_USCOREenum_USCOREproject_USCOREview_USCOREstatesResponse
{
	struct ObjectRefArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfObjectRef */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREproject_USCOREview_USCOREstates
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREproject_USCOREview_USCOREstates (125)
/* ns1:mc_enum_project_view_states */
struct ns1__mc_USCOREenum_USCOREproject_USCOREview_USCOREstates
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREview_USCOREstatesResponse
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREview_USCOREstatesResponse (126)
/* ns1:mc_enum_view_statesResponse */
struct ns1__mc_USCOREenum_USCOREview_USCOREstatesResponse
{
	struct ObjectRefArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfObjectRef */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREview_USCOREstates
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREview_USCOREstates (129)
/* ns1:mc_enum_view_states */
struct ns1__mc_USCOREenum_USCOREview_USCOREstates
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREcustom_USCOREfield_USCOREtypesResponse
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREcustom_USCOREfield_USCOREtypesResponse (130)
/* ns1:mc_enum_custom_field_typesResponse */
struct ns1__mc_USCOREenum_USCOREcustom_USCOREfield_USCOREtypesResponse
{
	struct ObjectRefArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfObjectRef */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREcustom_USCOREfield_USCOREtypes
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREcustom_USCOREfield_USCOREtypes (133)
/* ns1:mc_enum_custom_field_types */
struct ns1__mc_USCOREenum_USCOREcustom_USCOREfield_USCOREtypes
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREgetResponse
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREgetResponse (135)
/* ns1:mc_enum_getResponse */
struct ns1__mc_USCOREenum_USCOREgetResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREenum_USCOREget
#define SOAP_TYPE_ns1__mc_USCOREenum_USCOREget (136)
/* ns1:mc_enum_get */
struct ns1__mc_USCOREenum_USCOREget
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *enumeration;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREexistsResponse
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREexistsResponse (138)
/* ns1:mc_issue_existsResponse */
struct ns1__mc_USCOREissue_USCOREexistsResponse
{
	enum xsd__boolean *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREexists
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREexists (139)
/* ns1:mc_issue_exists */
struct ns1__mc_USCOREissue_USCOREexists
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *issue_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREgetResponse
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREgetResponse (140)
/* ns1:mc_issue_getResponse */
struct ns1__mc_USCOREissue_USCOREgetResponse
{
	struct ns1__IssueData *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:IssueData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREget
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREget (143)
/* ns1:mc_issue_get */
struct ns1__mc_USCOREissue_USCOREget
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *issue_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREget_USCOREbiggest_USCOREidResponse
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREget_USCOREbiggest_USCOREidResponse (146)
/* ns1:mc_issue_get_biggest_idResponse */
struct ns1__mc_USCOREissue_USCOREget_USCOREbiggest_USCOREidResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREget_USCOREbiggest_USCOREid
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREget_USCOREbiggest_USCOREid (147)
/* ns1:mc_issue_get_biggest_id */
struct ns1__mc_USCOREissue_USCOREget_USCOREbiggest_USCOREid
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREget_USCOREid_USCOREfrom_USCOREsummaryResponse
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREget_USCOREid_USCOREfrom_USCOREsummaryResponse (149)
/* ns1:mc_issue_get_id_from_summaryResponse */
struct ns1__mc_USCOREissue_USCOREget_USCOREid_USCOREfrom_USCOREsummaryResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREget_USCOREid_USCOREfrom_USCOREsummary
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREget_USCOREid_USCOREfrom_USCOREsummary (150)
/* ns1:mc_issue_get_id_from_summary */
struct ns1__mc_USCOREissue_USCOREget_USCOREid_USCOREfrom_USCOREsummary
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *summary;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREaddResponse
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREaddResponse (152)
/* ns1:mc_issue_addResponse */
struct ns1__mc_USCOREissue_USCOREaddResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREadd
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREadd (153)
/* ns1:mc_issue_add */
struct ns1__mc_USCOREissue_USCOREadd
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	struct ns1__IssueData *issue;	/* optional element of type ns1:IssueData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREupdateResponse
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREupdateResponse (155)
/* ns1:mc_issue_updateResponse */
struct ns1__mc_USCOREissue_USCOREupdateResponse
{
	enum xsd__boolean *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREupdate
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREupdate (156)
/* ns1:mc_issue_update */
struct ns1__mc_USCOREissue_USCOREupdate
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *issueId;	/* optional element of type xsd:integer */
	struct ns1__IssueData *issue;	/* optional element of type ns1:IssueData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREdeleteResponse
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREdeleteResponse (158)
/* ns1:mc_issue_deleteResponse */
struct ns1__mc_USCOREissue_USCOREdeleteResponse
{
	enum xsd__boolean *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREdelete
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREdelete (159)
/* ns1:mc_issue_delete */
struct ns1__mc_USCOREissue_USCOREdelete
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *issue_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREnote_USCOREaddResponse
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREnote_USCOREaddResponse (161)
/* ns1:mc_issue_note_addResponse */
struct ns1__mc_USCOREissue_USCOREnote_USCOREaddResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREnote_USCOREadd
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREnote_USCOREadd (162)
/* ns1:mc_issue_note_add */
struct ns1__mc_USCOREissue_USCOREnote_USCOREadd
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *issue_USCOREid;	/* optional element of type xsd:integer */
	struct ns1__IssueNoteData *note;	/* optional element of type ns1:IssueNoteData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREnote_USCOREdeleteResponse
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREnote_USCOREdeleteResponse (164)
/* ns1:mc_issue_note_deleteResponse */
struct ns1__mc_USCOREissue_USCOREnote_USCOREdeleteResponse
{
	enum xsd__boolean *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREnote_USCOREdelete
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREnote_USCOREdelete (165)
/* ns1:mc_issue_note_delete */
struct ns1__mc_USCOREissue_USCOREnote_USCOREdelete
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *issue_USCOREnote_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCORErelationship_USCOREaddResponse
#define SOAP_TYPE_ns1__mc_USCOREissue_USCORErelationship_USCOREaddResponse (167)
/* ns1:mc_issue_relationship_addResponse */
struct ns1__mc_USCOREissue_USCORErelationship_USCOREaddResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCORErelationship_USCOREadd
#define SOAP_TYPE_ns1__mc_USCOREissue_USCORErelationship_USCOREadd (168)
/* ns1:mc_issue_relationship_add */
struct ns1__mc_USCOREissue_USCORErelationship_USCOREadd
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *issue_USCOREid;	/* optional element of type xsd:integer */
	struct ns1__RelationshipData *relationship;	/* optional element of type ns1:RelationshipData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCORErelationship_USCOREdeleteResponse
#define SOAP_TYPE_ns1__mc_USCOREissue_USCORErelationship_USCOREdeleteResponse (170)
/* ns1:mc_issue_relationship_deleteResponse */
struct ns1__mc_USCOREissue_USCORErelationship_USCOREdeleteResponse
{
	enum xsd__boolean *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCORErelationship_USCOREdelete
#define SOAP_TYPE_ns1__mc_USCOREissue_USCORErelationship_USCOREdelete (171)
/* ns1:mc_issue_relationship_delete */
struct ns1__mc_USCOREissue_USCORErelationship_USCOREdelete
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *issue_USCOREid;	/* optional element of type xsd:integer */
	char *relationship_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREattachment_USCOREaddResponse
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREattachment_USCOREaddResponse (173)
/* ns1:mc_issue_attachment_addResponse */
struct ns1__mc_USCOREissue_USCOREattachment_USCOREaddResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREattachment_USCOREadd
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREattachment_USCOREadd (174)
/* ns1:mc_issue_attachment_add */
struct ns1__mc_USCOREissue_USCOREattachment_USCOREadd
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *issue_USCOREid;	/* optional element of type xsd:integer */
	char *name;	/* optional element of type xsd:string */
	char *file_USCOREtype;	/* optional element of type xsd:string */
	struct xsd__base64Binary content;	/* required element of type xsd:base64Binary */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREattachment_USCOREdeleteResponse
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREattachment_USCOREdeleteResponse (176)
/* ns1:mc_issue_attachment_deleteResponse */
struct ns1__mc_USCOREissue_USCOREattachment_USCOREdeleteResponse
{
	enum xsd__boolean *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREattachment_USCOREdelete
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREattachment_USCOREdelete (177)
/* ns1:mc_issue_attachment_delete */
struct ns1__mc_USCOREissue_USCOREattachment_USCOREdelete
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *issue_USCOREattachment_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREattachment_USCOREgetResponse
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREattachment_USCOREgetResponse (180)
/* ns1:mc_issue_attachment_getResponse */
struct ns1__mc_USCOREissue_USCOREattachment_USCOREgetResponse
{
	struct xsd__base64Binary *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:base64Binary */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREattachment_USCOREget
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREattachment_USCOREget (181)
/* ns1:mc_issue_attachment_get */
struct ns1__mc_USCOREissue_USCOREattachment_USCOREget
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *issue_USCOREattachment_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREaddResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREaddResponse (183)
/* ns1:mc_project_addResponse */
struct ns1__mc_USCOREproject_USCOREaddResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREadd
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREadd (184)
/* ns1:mc_project_add */
struct ns1__mc_USCOREproject_USCOREadd
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	struct ns1__ProjectData *project;	/* optional element of type ns1:ProjectData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREdeleteResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREdeleteResponse (186)
/* ns1:mc_project_deleteResponse */
struct ns1__mc_USCOREproject_USCOREdeleteResponse
{
	enum xsd__boolean *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREdelete
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREdelete (187)
/* ns1:mc_project_delete */
struct ns1__mc_USCOREproject_USCOREdelete
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREissuesResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREissuesResponse (188)
/* ns1:mc_project_get_issuesResponse */
struct ns1__mc_USCOREproject_USCOREget_USCOREissuesResponse
{
	struct IssueDataArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfIssueData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREissues
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREissues (192)
/* ns1:mc_project_get_issues */
struct ns1__mc_USCOREproject_USCOREget_USCOREissues
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREid;	/* optional element of type xsd:integer */
	char *page_USCOREnumber;	/* optional element of type xsd:integer */
	char *per_USCOREpage;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREissue_USCOREheadersResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREissue_USCOREheadersResponse (193)
/* ns1:mc_project_get_issue_headersResponse */
struct ns1__mc_USCOREproject_USCOREget_USCOREissue_USCOREheadersResponse
{
	struct IssueHeaderDataArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfIssueHeaderData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREissue_USCOREheaders
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREissue_USCOREheaders (197)
/* ns1:mc_project_get_issue_headers */
struct ns1__mc_USCOREproject_USCOREget_USCOREissue_USCOREheaders
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREid;	/* optional element of type xsd:integer */
	char *page_USCOREnumber;	/* optional element of type xsd:integer */
	char *per_USCOREpage;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREusersResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREusersResponse (198)
/* ns1:mc_project_get_usersResponse */
struct ns1__mc_USCOREproject_USCOREget_USCOREusersResponse
{
	struct AccountDataArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfAccountData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREusers
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREusers (202)
/* ns1:mc_project_get_users */
struct ns1__mc_USCOREproject_USCOREget_USCOREusers
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREid;	/* optional element of type xsd:integer */
	char *access;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREprojects_USCOREget_USCOREuser_USCOREaccessibleResponse
#define SOAP_TYPE_ns1__mc_USCOREprojects_USCOREget_USCOREuser_USCOREaccessibleResponse (203)
/* ns1:mc_projects_get_user_accessibleResponse */
struct ns1__mc_USCOREprojects_USCOREget_USCOREuser_USCOREaccessibleResponse
{
	struct ProjectDataArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfProjectData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREprojects_USCOREget_USCOREuser_USCOREaccessible
#define SOAP_TYPE_ns1__mc_USCOREprojects_USCOREget_USCOREuser_USCOREaccessible (206)
/* ns1:mc_projects_get_user_accessible */
struct ns1__mc_USCOREprojects_USCOREget_USCOREuser_USCOREaccessible
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREcategoriesResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREcategoriesResponse (207)
/* ns1:mc_project_get_categoriesResponse */
struct ns1__mc_USCOREproject_USCOREget_USCOREcategoriesResponse
{
	struct StringArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREcategories
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREcategories (211)
/* ns1:mc_project_get_categories */
struct ns1__mc_USCOREproject_USCOREget_USCOREcategories
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREversionsResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREversionsResponse (212)
/* ns1:mc_project_get_versionsResponse */
struct ns1__mc_USCOREproject_USCOREget_USCOREversionsResponse
{
	struct ProjectVersionDataArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfProjectVersionData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREversions
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREversions (216)
/* ns1:mc_project_get_versions */
struct ns1__mc_USCOREproject_USCOREget_USCOREversions
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREversion_USCOREaddResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREversion_USCOREaddResponse (218)
/* ns1:mc_project_version_addResponse */
struct ns1__mc_USCOREproject_USCOREversion_USCOREaddResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREversion_USCOREadd
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREversion_USCOREadd (219)
/* ns1:mc_project_version_add */
struct ns1__mc_USCOREproject_USCOREversion_USCOREadd
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	struct ns1__ProjectVersionData *version;	/* optional element of type ns1:ProjectVersionData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREversion_USCOREupdateResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREversion_USCOREupdateResponse (221)
/* ns1:mc_project_version_updateResponse */
struct ns1__mc_USCOREproject_USCOREversion_USCOREupdateResponse
{
	enum xsd__boolean *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREversion_USCOREupdate
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREversion_USCOREupdate (222)
/* ns1:mc_project_version_update */
struct ns1__mc_USCOREproject_USCOREversion_USCOREupdate
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *version_USCOREid;	/* optional element of type xsd:integer */
	struct ns1__ProjectVersionData *version;	/* optional element of type ns1:ProjectVersionData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREversion_USCOREdeleteResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREversion_USCOREdeleteResponse (224)
/* ns1:mc_project_version_deleteResponse */
struct ns1__mc_USCOREproject_USCOREversion_USCOREdeleteResponse
{
	enum xsd__boolean *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREversion_USCOREdelete
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREversion_USCOREdelete (225)
/* ns1:mc_project_version_delete */
struct ns1__mc_USCOREproject_USCOREversion_USCOREdelete
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *version_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREreleased_USCOREversionsResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREreleased_USCOREversionsResponse (226)
/* ns1:mc_project_get_released_versionsResponse */
struct ns1__mc_USCOREproject_USCOREget_USCOREreleased_USCOREversionsResponse
{
	struct ProjectVersionDataArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfProjectVersionData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREreleased_USCOREversions
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREreleased_USCOREversions (229)
/* ns1:mc_project_get_released_versions */
struct ns1__mc_USCOREproject_USCOREget_USCOREreleased_USCOREversions
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREunreleased_USCOREversionsResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREunreleased_USCOREversionsResponse (230)
/* ns1:mc_project_get_unreleased_versionsResponse */
struct ns1__mc_USCOREproject_USCOREget_USCOREunreleased_USCOREversionsResponse
{
	struct ProjectVersionDataArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfProjectVersionData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREunreleased_USCOREversions
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREunreleased_USCOREversions (233)
/* ns1:mc_project_get_unreleased_versions */
struct ns1__mc_USCOREproject_USCOREget_USCOREunreleased_USCOREversions
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREattachmentsResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREattachmentsResponse (234)
/* ns1:mc_project_get_attachmentsResponse */
struct ns1__mc_USCOREproject_USCOREget_USCOREattachmentsResponse
{
	struct ProjectAttachmentDataArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfProjectAttachmentData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREattachments
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREattachments (238)
/* ns1:mc_project_get_attachments */
struct ns1__mc_USCOREproject_USCOREget_USCOREattachments
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREcustom_USCOREfieldsResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREcustom_USCOREfieldsResponse (239)
/* ns1:mc_project_get_custom_fieldsResponse */
struct ns1__mc_USCOREproject_USCOREget_USCOREcustom_USCOREfieldsResponse
{
	struct CustomFieldDefinitionDataArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfCustomFieldDefinitionData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREcustom_USCOREfields
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREget_USCOREcustom_USCOREfields (243)
/* ns1:mc_project_get_custom_fields */
struct ns1__mc_USCOREproject_USCOREget_USCOREcustom_USCOREfields
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREattachment_USCOREgetResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREattachment_USCOREgetResponse (245)
/* ns1:mc_project_attachment_getResponse */
struct ns1__mc_USCOREproject_USCOREattachment_USCOREgetResponse
{
	struct xsd__base64Binary *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:base64Binary */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREattachment_USCOREget
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREattachment_USCOREget (246)
/* ns1:mc_project_attachment_get */
struct ns1__mc_USCOREproject_USCOREattachment_USCOREget
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREattachment_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREattachment_USCOREaddResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREattachment_USCOREaddResponse (248)
/* ns1:mc_project_attachment_addResponse */
struct ns1__mc_USCOREproject_USCOREattachment_USCOREaddResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREattachment_USCOREadd
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREattachment_USCOREadd (249)
/* ns1:mc_project_attachment_add */
struct ns1__mc_USCOREproject_USCOREattachment_USCOREadd
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREid;	/* optional element of type xsd:integer */
	char *name;	/* optional element of type xsd:string */
	char *title;	/* optional element of type xsd:string */
	char *description;	/* optional element of type xsd:string */
	char *file_USCOREtype;	/* optional element of type xsd:string */
	struct xsd__base64Binary content;	/* required element of type xsd:base64Binary */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREattachment_USCOREdeleteResponse
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREattachment_USCOREdeleteResponse (251)
/* ns1:mc_project_attachment_deleteResponse */
struct ns1__mc_USCOREproject_USCOREattachment_USCOREdeleteResponse
{
	enum xsd__boolean *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREproject_USCOREattachment_USCOREdelete
#define SOAP_TYPE_ns1__mc_USCOREproject_USCOREattachment_USCOREdelete (252)
/* ns1:mc_project_attachment_delete */
struct ns1__mc_USCOREproject_USCOREattachment_USCOREdelete
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREattachment_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREfilter_USCOREgetResponse
#define SOAP_TYPE_ns1__mc_USCOREfilter_USCOREgetResponse (253)
/* ns1:mc_filter_getResponse */
struct ns1__mc_USCOREfilter_USCOREgetResponse
{
	struct FilterDataArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfFilterData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREfilter_USCOREget
#define SOAP_TYPE_ns1__mc_USCOREfilter_USCOREget (257)
/* ns1:mc_filter_get */
struct ns1__mc_USCOREfilter_USCOREget
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREid;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREfilter_USCOREget_USCOREissuesResponse
#define SOAP_TYPE_ns1__mc_USCOREfilter_USCOREget_USCOREissuesResponse (258)
/* ns1:mc_filter_get_issuesResponse */
struct ns1__mc_USCOREfilter_USCOREget_USCOREissuesResponse
{
	struct IssueDataArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfIssueData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREfilter_USCOREget_USCOREissues
#define SOAP_TYPE_ns1__mc_USCOREfilter_USCOREget_USCOREissues (261)
/* ns1:mc_filter_get_issues */
struct ns1__mc_USCOREfilter_USCOREget_USCOREissues
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREid;	/* optional element of type xsd:integer */
	char *filter_USCOREid;	/* optional element of type xsd:integer */
	char *page_USCOREnumber;	/* optional element of type xsd:integer */
	char *per_USCOREpage;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREfilter_USCOREget_USCOREissue_USCOREheadersResponse
#define SOAP_TYPE_ns1__mc_USCOREfilter_USCOREget_USCOREissue_USCOREheadersResponse (262)
/* ns1:mc_filter_get_issue_headersResponse */
struct ns1__mc_USCOREfilter_USCOREget_USCOREissue_USCOREheadersResponse
{
	struct IssueHeaderDataArray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfIssueHeaderData */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREfilter_USCOREget_USCOREissue_USCOREheaders
#define SOAP_TYPE_ns1__mc_USCOREfilter_USCOREget_USCOREissue_USCOREheaders (265)
/* ns1:mc_filter_get_issue_headers */
struct ns1__mc_USCOREfilter_USCOREget_USCOREissue_USCOREheaders
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *project_USCOREid;	/* optional element of type xsd:integer */
	char *filter_USCOREid;	/* optional element of type xsd:integer */
	char *page_USCOREnumber;	/* optional element of type xsd:integer */
	char *per_USCOREpage;	/* optional element of type xsd:integer */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREconfig_USCOREget_USCOREstringResponse
#define SOAP_TYPE_ns1__mc_USCOREconfig_USCOREget_USCOREstringResponse (267)
/* ns1:mc_config_get_stringResponse */
struct ns1__mc_USCOREconfig_USCOREget_USCOREstringResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREconfig_USCOREget_USCOREstring
#define SOAP_TYPE_ns1__mc_USCOREconfig_USCOREget_USCOREstring (268)
/* ns1:mc_config_get_string */
struct ns1__mc_USCOREconfig_USCOREget_USCOREstring
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *config_USCOREvar;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREcheckinResponse
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREcheckinResponse (270)
/* ns1:mc_issue_checkinResponse */
struct ns1__mc_USCOREissue_USCOREcheckinResponse
{
	enum xsd__boolean *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns1__mc_USCOREissue_USCOREcheckin
#define SOAP_TYPE_ns1__mc_USCOREissue_USCOREcheckin (271)
/* ns1:mc_issue_checkin */
struct ns1__mc_USCOREissue_USCOREcheckin
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *issue_USCOREid;	/* optional element of type xsd:integer */
	char *comment;	/* optional element of type xsd:string */
	enum xsd__boolean fixed;	/* required element of type xsd:boolean */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (272)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (273)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (275)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (278)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (279)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (7)
typedef char *xsd__anyURI;
#endif

#ifndef SOAP_TYPE_xsd__byte
#define SOAP_TYPE_xsd__byte (13)
typedef char xsd__byte;
#endif

#ifndef SOAP_TYPE_xsd__integer
#define SOAP_TYPE_xsd__integer (14)
typedef char *xsd__integer;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREversion(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREenum_USCOREstatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, struct ns1__mc_USCOREenum_USCOREstatusResponse *_param_1);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREenum_USCOREpriorities(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, struct ns1__mc_USCOREenum_USCOREprioritiesResponse *_param_2);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREenum_USCOREseverities(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, struct ns1__mc_USCOREenum_USCOREseveritiesResponse *_param_3);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREenum_USCOREreproducibilities(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, struct ns1__mc_USCOREenum_USCOREreproducibilitiesResponse *_param_4);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREenum_USCOREprojections(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, struct ns1__mc_USCOREenum_USCOREprojectionsResponse *_param_5);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREenum_USCOREetas(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, struct ns1__mc_USCOREenum_USCOREetasResponse *_param_6);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREenum_USCOREresolutions(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, struct ns1__mc_USCOREenum_USCOREresolutionsResponse *_param_7);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREenum_USCOREaccess_USCORElevels(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, struct ns1__mc_USCOREenum_USCOREaccess_USCORElevelsResponse *_param_8);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREenum_USCOREproject_USCOREstatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, struct ns1__mc_USCOREenum_USCOREproject_USCOREstatusResponse *_param_9);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREenum_USCOREproject_USCOREview_USCOREstates(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, struct ns1__mc_USCOREenum_USCOREproject_USCOREview_USCOREstatesResponse *_param_10);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREenum_USCOREview_USCOREstates(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, struct ns1__mc_USCOREenum_USCOREview_USCOREstatesResponse *_param_11);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREenum_USCOREcustom_USCOREfield_USCOREtypes(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, struct ns1__mc_USCOREenum_USCOREcustom_USCOREfield_USCOREtypesResponse *_param_12);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREenum_USCOREget(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *enumeration, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREissue_USCOREexists(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *issue_USCOREid, enum xsd__boolean *return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREissue_USCOREget(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *issue_USCOREid, struct ns1__mc_USCOREissue_USCOREgetResponse *_param_13);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREissue_USCOREget_USCOREbiggest_USCOREid(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREid, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREissue_USCOREget_USCOREid_USCOREfrom_USCOREsummary(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *summary, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREissue_USCOREadd(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, struct ns1__IssueData *issue, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREissue_USCOREupdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *issueId, struct ns1__IssueData *issue, enum xsd__boolean *return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREissue_USCOREdelete(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *issue_USCOREid, enum xsd__boolean *return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREissue_USCOREnote_USCOREadd(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *issue_USCOREid, struct ns1__IssueNoteData *note, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREissue_USCOREnote_USCOREdelete(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *issue_USCOREnote_USCOREid, enum xsd__boolean *return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREissue_USCORErelationship_USCOREadd(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *issue_USCOREid, struct ns1__RelationshipData *relationship, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREissue_USCORErelationship_USCOREdelete(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *issue_USCOREid, char *relationship_USCOREid, enum xsd__boolean *return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREissue_USCOREattachment_USCOREadd(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *issue_USCOREid, char *name, char *file_USCOREtype, struct xsd__base64Binary content, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREissue_USCOREattachment_USCOREdelete(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *issue_USCOREattachment_USCOREid, enum xsd__boolean *return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREissue_USCOREattachment_USCOREget(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *issue_USCOREattachment_USCOREid, struct xsd__base64Binary *return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREadd(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, struct ns1__ProjectData *project, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREdelete(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREid, enum xsd__boolean *return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREget_USCOREissues(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREid, char *page_USCOREnumber, char *per_USCOREpage, struct ns1__mc_USCOREproject_USCOREget_USCOREissuesResponse *_param_14);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREget_USCOREissue_USCOREheaders(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREid, char *page_USCOREnumber, char *per_USCOREpage, struct ns1__mc_USCOREproject_USCOREget_USCOREissue_USCOREheadersResponse *_param_15);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREget_USCOREusers(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREid, char *access, struct ns1__mc_USCOREproject_USCOREget_USCOREusersResponse *_param_16);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREprojects_USCOREget_USCOREuser_USCOREaccessible(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, struct ns1__mc_USCOREprojects_USCOREget_USCOREuser_USCOREaccessibleResponse *_param_17);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREget_USCOREcategories(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREid, struct ns1__mc_USCOREproject_USCOREget_USCOREcategoriesResponse *_param_18);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREget_USCOREversions(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREid, struct ns1__mc_USCOREproject_USCOREget_USCOREversionsResponse *_param_19);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREversion_USCOREadd(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, struct ns1__ProjectVersionData *version, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREversion_USCOREupdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *version_USCOREid, struct ns1__ProjectVersionData *version, enum xsd__boolean *return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREversion_USCOREdelete(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *version_USCOREid, enum xsd__boolean *return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREget_USCOREreleased_USCOREversions(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREid, struct ns1__mc_USCOREproject_USCOREget_USCOREreleased_USCOREversionsResponse *_param_20);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREget_USCOREunreleased_USCOREversions(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREid, struct ns1__mc_USCOREproject_USCOREget_USCOREunreleased_USCOREversionsResponse *_param_21);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREget_USCOREattachments(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREid, struct ns1__mc_USCOREproject_USCOREget_USCOREattachmentsResponse *_param_22);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREget_USCOREcustom_USCOREfields(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREid, struct ns1__mc_USCOREproject_USCOREget_USCOREcustom_USCOREfieldsResponse *_param_23);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREattachment_USCOREget(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREattachment_USCOREid, struct xsd__base64Binary *return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREattachment_USCOREadd(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREid, char *name, char *title, char *description, char *file_USCOREtype, struct xsd__base64Binary content, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREproject_USCOREattachment_USCOREdelete(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREattachment_USCOREid, enum xsd__boolean *return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREfilter_USCOREget(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREid, struct ns1__mc_USCOREfilter_USCOREgetResponse *_param_24);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREfilter_USCOREget_USCOREissues(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREid, char *filter_USCOREid, char *page_USCOREnumber, char *per_USCOREpage, struct ns1__mc_USCOREfilter_USCOREget_USCOREissuesResponse *_param_25);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREfilter_USCOREget_USCOREissue_USCOREheaders(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *project_USCOREid, char *filter_USCOREid, char *page_USCOREnumber, char *per_USCOREpage, struct ns1__mc_USCOREfilter_USCOREget_USCOREissue_USCOREheadersResponse *_param_26);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREconfig_USCOREget_USCOREstring(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *config_USCOREvar, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__mc_USCOREissue_USCOREcheckin(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *username, char *password, char *issue_USCOREid, char *comment, enum xsd__boolean fixed, enum xsd__boolean *return_);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
