

MAIN
  DEFINE ans CHAR

  DISPLAY "Hello world " AT 10, 20 
	  ATTRIBUTE (
		  WHITE,YELLOW,MAGENTA,CYAN,GREEN,BLUE,BLACK,RED,NORMAL,BOLD,DIM,
			NORMAL,REVERSE,BLINK,UNDERLINE
		)
	#PROMPT "" FOR CHAR ans
END MAIN
